### ISSUE TITLE
Limit amount of data in a message

### ISSUE THREAD

**Issue by davedoesdev** [primus/primus#107]
I'm thinking there may be a way of attacking a server by sending a very large message. Primus should drop the connection if too much data is being sent (which would result in large memory usage).
Maybe it already does this?

**Comment by lpinca** [comment]
This has been partially addressed in 5e996a63f208e9f77c93f6f39e4acf2c761bbcc9 and 8846739ec7b6298194ce78e82f43c934fd47259a.
`browserchannel` and `sockjs` (when not using WebSocket) do not have an option to limit the maximum message size.

**Comment by davedoesdev** [comment]
Find to close then?

**Comment by lpinca** [comment]
Yes, I think it's fine to close this. I'm not sure if it's possible to fix the issue for the two transformers mentioned above (`browserchannel` and `sockjs`) but it's probably better to fix the issue upstream anyway.
