### ISSUE TITLE
Predefine breaks compatibility with some plugins

### ISSUE THREAD

**Issue by ruimarinho** [primus/primus#125]
Hi,

Commit ebc7a842815cd26a43c299ac8282a90d1dff42ad introduces a new way of defining setters and getters using the `predefine` module. However, some `Spark` methods, such as `initialise` have now been marked as read-only, which breaks plugins that rely on overrides to extend Spark (see `primus-emitter`, for instance).

There is also no way to properly extend Spark through plugins now (actually, Sparky), because it does not expose the `extend` method from `predefine`.

Personally, I like the way extend works on Backbone and it could be a neat way for plugins to add functionality to Spark in a simple and elegant form, but this would require a version bump.

What do you suggest in this case @3rd-Eden?

**Comment by SruthiDevarachetty** [comment]
I am getting the following error. I have primus@7.0.2 installed.
var initialise = Spark.prototype.initialise;
                        ^

TypeError: Cannot read property 'prototype' of undefined
    at spark (C:\..\..\node_modules\primus-emitter\lib\spark.js:8:25)
    at PrimusEmitter (C:\..\..\node_modules\primus-emitter\lib\index.js:50:10)
    at Primus.use (C:\..\..\node_modules\primus\index.js:812:13)

**Comment by SruthiDevarachetty** [comment]
I am getting the following error and have primus@7.0.2 installed.

**Comment by VR99** [comment]
Using primus@7.0.2 and primus-emitter. Getting the following error. 

var initialise = Spark.prototype.initialise;
                        ^
TypeError: Cannot read property 'prototype' of undefined
