### ISSUE TITLE
Sticky Sessions

### ISSUE THREAD

**Issue by bendytree** [primus/primus#147]
First off - _huge_ fan of Primus. It literally saved me from a socket.io disaster back in August.

The [readme](https://github.com/primus/primus#what-is-the-best-way-to-scale-primus) says that scaling requires your load balancer to support sticky sessions.

As far as I can tell, ~~[Modulus](http://blog.modulus.io/try-out-new-load-balancer#comment-1232253568),~~ [Heroku](https://devcenter.heroku.com/articles/java-faq#what-constraints-should-i-be-aware-of-when-developing-applications-on-heroku), and [ELB](http://johan.heapsource.com/post/31047804966/the-state-of-websockets-ssl-and-sticky-sessions-in) don't support sticky sessions.

Would someone mind explaining why Primus needs sticky sessions? Is there a work-around?

**Comment by xavriley** [comment]
Since this was filed sticky sessions are now in Beta on Heroku with https://devcenter.heroku.com/articles/session-affinity
