### ISSUE TITLE
primus.authorize(req,done) gives no req.address || is req.headers[sec-websocket-key] available for all transports ?

### ISSUE THREAD

**Issue by gcmartijn** [primus/primus#169]
I'm trying to setup a connection where there is a admin and users.

The first connection is always a admin, and his first connection point at the server is primus.authorize(req,done).

But req does not have much data like `primus.on('connection',function(spark){});`
for example spark.address (ipadress) and spark.id

And I want to know wich spark.id is a admin.

The only info I get inside a primus.authorize(req,done) are only:
- the headers
- the uri
- a uri query

for example the req.headers are:
`
 { upgrade: 'websocket',
  connection: 'Upgrade',
  host: '-hidden-:8090',
  origin: 'http://-hidden-',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  'sec-websocket-key': '5g+N64Z0jw3hOY+S8bVHhA==',
  'sec-websocket-version': '13',
  'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits, x-webkit-deflate-frame',
  'user-agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.146 Safari/537.36' }
`

But there is one thing I can use inside the header I see:
`
 'sec-websocket-key': '5g+N64Z0jw3hOY+S8bVHhA==',
`

This is the same after a good auth done() so I can say something like this:

1.) a admin connects

``` js
primus.authorize(req,done){
 if admin then save header[sec-websocket-key] for a second
done() 
}
```

2.)

``` js
primus.on('connection',function(spark){
 if spark.header[sec-websocket-key] == admin then
 spark.id = a admin
});
```

Now a full connection is made and now I know that spark.id is a admin using the header[sec-websocket-key] 

But is it good to use that ? 
Does every transport layer give me that key ? is it future proof ?

A other option would to use req.uri.query and send some extra data like ?isadmin=true but I don't like that very much.

Or make a connection and send extra info when a connection is made.

UPDATE:
I think its oke to use it, after reading this: https://tools.ietf.org/html/rfc6455#section-11.3.1

**Comment by breandr** [comment]
I'm sorry, but I don't think the question of "where can I set the req.headers['authorization'] ?" was answered. Adding `token` to the querystring does not address this. If you can't set an `Authorization` header, should the authorization example be changed? Otherwise it's very misleading.

**Comment by lpinca** [comment]
@breandr I think that https://github.com/primus/primus#can-i-send-custom-headers-to-the-server answers the question, but there are cases, for example when using the `websocket` transformer and the node client, where it is possible to add custom headers. The authorization example was probably forged with this in mind.
