### ISSUE TITLE
Primus session sharing with Express.js

### ISSUE THREAD

**Issue by rubymaniac** [primus/primus#236]
I don't know if I should write this here (because I do not know if this is a bug) but there you go. 

I am trying to implement a Primus middleware that will expose the session data on a `spark.request.session` object. The configuration on the Express.js app is something like this:

``` javascript
var sessionConfig = {
        key: 'sid',
        secret: config.Session.secret,
        cookie: { httpOnly: true, secure: true },
        store: new RedisStore({ client: redisClient })
};

app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.set('views', path.join(__dirname, 'views'));
    app.enable('trust proxy');

    app.use(express.favicon(path.join(__dirname, 'favicon.ico')));
    app.use(express.json());
    app.use(express.urlencoded());
    app.use(express.cookieParser(config.Cookies.secret));
    app.use(express.session(sessionConfig));
    app.use(app.router);
    app.use('/api/v1', API({ database: config.Database }));
});

var server = app.listen(app.get('port'));
var primus = new Primus(
   transformer: 'engine.io',
   cluster: { redis: function() { return redisClient; } }
});
primus.use('emitter', PrimusEmitter);
primus.use('cluster', PrimusCluster);
primus.library();
primus.save(distDir + '/scripts/vendor/primus.js', function save (err) {
    if (err) logger.error({ err: err });
});

primus.before('cookies', express.cookieParser(config.Cookies.secret));
primus.before('session', wsSessionMiddleware, sessionConfig);
```

And the middleware implementation I have so far is:

``` javascript
'use strict';

var connect = require('express/node_modules/connect');
var Session = connect.session.Session;

module.exports = function configure(options) {
    var key = options.key || 'connect.sid',
        store = options.store,
        secret = options.secret,
        primus = this;

    function sessionMiddleware(req, res, next) {
        if (req.session) return next();

        // grab the session cookie value and check the signature
        var rawCookie = req.cookies[key];

        // get signedCookies for backwards compat with signed cookies
        var unsignedCookie = req.signedCookies[key];

        if (!unsignedCookie && rawCookie) {
            unsignedCookie = connect.utils.parseSignedCookie(rawCookie, secret);
        }

        if (!unsignedCookie) return next();

        req.sessionID = unsignedCookie;
        req.sessionStore = store;

        store.get(req.sessionID, function (err, session) {
            if (err) {
                primus.emit('log', 'error', err);
            } else if (session) {
                store.createSession(req, session);
            }
            return next();
        });
    }

    return sessionMiddleware;
};
```

The frontend part just opens a websocket connection and sends some ol' XHR requests to the Express.js API. The weird thing is that when I first load the page everything seems to work as expected. The second time I reload the page though, every (XHR) request on the API has its `req.session` undefined. When I delete the line 

``` javascript
primus.before('session', wsSessionMiddleware, sessionConfig);
```

every XHR request goes back to normal, having the correct `req.session` object.

Any help will be much appreciated because I am near to start doing drugs :/

P.S. I had a look at this: https://github.com/primus/primus/blob/master/examples/middleware/session.js but it won't work because it needs `req.signedCookies` and I haven't.

**Comment by carlitux** [comment]
primus 3.2.1

    function _session (options) {
      var key = options.key || 'connect.sid'
        , store = options.store
        , primus = this;

      if (!store) {
        //
        // Throw an error when the session store is not passed.
        //
        var message = 'Session middleware configuration failed due to missing '
          + '`store` option';
        throw new Error(message, this);
      }

      //
      // The actual session middleware. This middleware is async so we need 3
      // arguments.
      //
      function session(req, res, next) {
        //
        // The session id is stored in the cookies.
        // `req.signedCookies` is assigned by the `cookie-parser` middleware.
        //
        var sid = req.signedCookies[key];

        //
        // Default to an empty session.
        //
        req.session = {};

        //
        // If we don't have a session id we are done.
        //
        if (!sid) {
          return next();
        }

        //
        // Pause the request before retrieving the session. This ensures that no
        // `data` event is lost while we perform our async call.
        //
        req.pause();

        //
        // Grab the session from the store.
        //
        store.get(sid, function (err, sess) {
          //
          // We don't want to kill the connection when we get an error from the
          // session store so we just log the error.
          //
          if (err) {
            primus.emit('log', 'error', err);
            return next();
          }

          if (sess) {
            store.createSession(req, sess);
            req.xsession = sess;
          }

          //
          // At this point the request stream can resume emitting `data` events.
          //
          req.resume();

          next();
        });
      }

      return session;
    }

And the result

    console.log('******************************');
    console.log(req.session);
    console.log(req.xsession);
    console.log('******************************');

is

******************************
n0fb4epc
{ cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  passport: { user: '55450fcde391f88dbde0179e' } }
******************************

Where req.session is just an string

**Comment by jubr** [comment]
Also note the call
```
primus.library();
```
renders the library contents to a string which it then discards.
Might want to remove it :)

**Comment by firasd** [comment]
Here's how I have it working currently (Express 4.13.4; Primus 4.0.5)

App.js:

```
var express = require('express');
var cookieParser = require('cookie-parser');
var session = require('express-session');

var sockjs = require('sockjs');
var http = require('http');
var Primus = require('primus');
var realtime_functions = require('./custom_modules/realtime_functions.js');

var app = express();

var app_secret_key = 'app secret';
var cookieparser = cookieParser(app_secret_key);
var sessionstore = new session.MemoryStore();

app.use(cookieparser);
app.use(session({
  secret: app_secret_key,
  saveUninitialized: false,
  resave: false,
  store: sessionstore
}));

realtime_functions(app, cookieparser, sessionstore);
```

realtime_functions.js

```

var primus_start = function(express, cookies, store) {

  var server = http.createServer(express);

  var primus = new Primus(server, {transformer: 'SockJS', parser: 'JSON'})
  primus.use('rooms', primusRooms)
  server.listen(3000, '0.0.0.0');

  primus.before('cookies', cookies);
  primus.before('session', function session(req, res, next) {
    try {
      var sid = req.signedCookies['connect.sid'];
      if (!sid) { return next(); }
      req.pause();
      store.get(sid, function (err, session) {
        if (err) {
          primus.emit('log', 'error', err);
          return next();
        }
        if(session) {
          req.sessionID = sid;
          req.sessionStore = store;
          req.thesession = store.createSession(req, session);
        }
        req.resume();
        next();
      });
    } catch(error) {
      console.log(error);
    }
  });

  primus.on('connection', function(spark) {
    spark.on('data', function(data) {
      spark.request.thesession.addthis = "save this to session";
      spark.request.thesession.save();
    });
  });
}
```

**Comment by reorg-hle** [comment]
I ran into an issue with this where ```var sid = req.signedCookies[key];``` always returned false. After a day of debugging, I've discovered that the issue is the secret keys: 

**The cookie secret and the session secret MUST be the same.**

```
var app_secret_key = 'app secret'; // MUST BE USED FOR BOTH
var cookieparser = cookieParser(app_secret_key);
var sessionstore = new session.MemoryStore();

app.use(cookieparser);
app.use(session({
  secret: app_secret_key,
  saveUninitialized: false,
  resave: false,
  store: sessionstore
}));
```
