### ISSUE TITLE
Client not receiving message

### ISSUE THREAD

**Issue by alexravard** [primus/primus#316]
I am having issues with some messages not being delivered. This happens sometimes, depending on the clients 'conditions' (different browsers, OS, network conditions...). 

But so far I've found Primus to be very unreliable, and I can't find a good way to debug this (can I know if a spark.write was successful? and if not, why?)

What I'm trying to accomplish is implement RabbitMQ together with Primus websockets, to accomplish the following:

Connect to rabbitmq using ampqlib, when a user connects to the node server, we create a channel to a queue and send the user the messages coming from rabbitmq using primus. But this doesn't work always.

Any help, pointers would be appreciated.

**Comment by mariusk** [comment]
I'll confirm this ticket has well; have really weird state issues when using engine.io, where my client would send but never receive data after a server restarted (triggering the reconnect feature in primus). Based on suggestions here I tried sockjs instead, and so far have been unable to trigger the same faulty behaviour.

**Comment by lpinca** [comment]
Closing as this issue is very old and may be no longer valid. Please post back if needed.
