### ISSUE TITLE
Deprecation of the end option of primus.destroy()

### ISSUE THREAD

**Issue by hugo-agbonon** [primus/primus#318]
Hello,

I'm trying to figure out why the `end` option was deprecated from `primus.destroy()` in v2.4.11.

We had an usecase for this option, which involved destroying primus before getting a server down for maintenance.
With the `end` option set to `false`, the users connected to this primus server were notified and able to gracefully reconnect to another server behind the same reverse proxy.

Why was this option removed? Is there another way we could (and should?) properly destroy the primus instance and get our users reconnected?

**Comment by akreienbring** [comment]
Hi, i'm using version 2.4.12 of your library. Each time the server starts the client library gets generated.
But in that library I can't find the destroy method.
Is this becaus it will be refactored and is currently not part of the client library?

**Comment by 3rd-Eden** [comment]
@akreienbring The client method doesn't have a destroy method yet. It will be included in the next release (which is currently staging in master until we fix a race condition)
