### ISSUE TITLE
spark.address produces TypeError if called after client has disconnected

### ISSUE THREAD

**Issue by grind086** [primus/primus#333]
Appears to be caused by spark.request becoming undefined after the client disconnects. You can reproduce the error with the following:

```js
var Primus = require('primus')

var primus = Primus.createServer({
	port: 8080,
	iknowhttpsisbetter: true
});
primus.on('connection', function(spark) {
	// Works
	console.log(spark.address);

	spark.end();
	setTimeout(function() {
		// TypeError
		console.log(spark.address);
	}, 250)
});
primus.on('disconnection', function(spark) {
	// Works
	console.log(spark.address);
});

var client = new primus.Socket('http://localhost:8080');
```

This may not be a common error, but I wasn't expecting to run into an error here and a fix is easy enough. I'm not too familiar with this library, but if simply preventing the error is acceptable you could do something like this:

```js
// spark.js:94
Spark.get('address', function address() {
  if (this.request !== undefined) {
    return this.request.forwarded || forwarded(this.remote, this.headers, this.primus.whitelist);
  }
  return undefined;
});
```

Though still being able to actually get the (former) client's address could be useful.

**Comment by lpinca** [comment]
@grind086 good find. This happens because we free some potentially heavy objects when the spark closes https://github.com/primus/primus/blob/a13b215803a3b42973c7650f244ebe0b53c9deed/spark.js#L271-L275.
To have the property always available we should avoid to lazy load it or change the clean up to not release the relevant references.

**Comment by lpinca** [comment]
Another option is something like this:
```diff
diff --git a/spark.js b/spark.js
index 598a779..2b9160f 100644
--- a/spark.js
+++ b/spark.js
@@ -47,6 +47,14 @@ function Spark(primus, headers, address, query, id, request) {
   writable('ultron', new Ultron(this)); // Our event listening cleanup.
 
   //
+  // Lazy parse interface for IP address information. As nobody is always
+  // interested in this, we're going to defer parsing until it's actually needed.
+  //
+  Object.defineProperty(this, 'address', { get: function address() {
+    return request.forwarded || forwarded(address, headers, primus.whitelist);
+  }});
+
+  //
   // Parse our query string.
   //
   if ('string' === typeof this.query) {
@@ -87,14 +95,6 @@ Spark.readable('readyState', {
 
 Spark.writable('__readyState', Spark.OPEN);
 
-//
-// Lazy parse interface for IP address information. As nobody is always
-// interested in this, we're going to defer parsing until it's actually needed.
-//
-Spark.get('address', function address() {
-  return this.request.forwarded || forwarded(this.remote, this.headers, this.primus.whitelist);
-});
-
 /**
  * Set a timer to forcibly disconnect the spark if no data is received from the
  * client within the given timeout.
```
but it's no different from not releasing the references.

**Comment by 3rd-Eden** [comment]
I kinda disagree with the fact that this is marked as a bug. You're trying to access properties that are already removed. Once the connection is ended you should not interact with the spark anymore. Getting an address of a ended connection is silly anyways as your trying to get it from non existing socket.

But I do agree that returning a type error might not be the nicest thing to do. But returning undefined or anything else just masks the problem in your code, and that is trying to access something that is non existing.

**Comment by 3rd-Eden** [comment]
Also, you could just check the Spark readystate before accessing the property..

```js
setTimeout(function () {
  if (spark.readyState !== primus.Spark.CLOSED) console.log(spark.address);
});
```

**Comment by lpinca** [comment]
That's correct, I also think that it is not exactly a bug but there wasn't a label to tag the issue.
I shouldn't have added it in the first place.

**Comment by grind086** [comment]
Fair enough. I'll try to be more careful with my async code in the future. A note in the docs might be helpful for anyone encountering this in the future.

**Comment by lpinca** [comment]
@grind086 pull requests to improve documentation are usually instantly merged :)

**Comment by STRML** [comment]
Just an FYI - I've seen this happen if you have async `'connection'` middleware and the connection closes midway. Something to keep in mind - it may make sense to guard on `spark.readyState !== primus.Spark.CLOSED` in your later handlers.
