### ISSUE TITLE
Primus.require fails with new npm install algorithm

### ISSUE THREAD

**Issue by dignifiedquire** [primus/primus#334]
When trying to use the `sockjs-client` inside a nested dependency on node.js `primus.require` fails, because the new `npm install` does some deduplication work, resulting in only one primus install at the top level (as the top level module requires primus as well). 

I'm not entirely sure if this is a bug of npm or primus, but I think it needs some thought and fixing from some side.

In the repository below you can find a reproduction, trying to use `primus.require` results in an undefined result, as it can not find the nested `sockjs-client-node` module from the top level `primus` installation. 

npm version: `2.1.18`

**Full Structure**

```
|-- node_modules
|  |-- primus
|  `-- dep1
|     `-- node_modules
|        |-- primus
|        `-- sockjs-client-node
|
|-- index.js
```

**Deduped Structure**

```
|-- node_modules
|  |-- primus
|  |-- dep1
|     |-- node_modules
|        `-- sockjs-client-node
|
|-- index.js
```

**Repro Repository**
https://github.com/Dignifiedquire/npm-primus-bug

**Comment by 3rd-Eden** [comment]
I guess it's because you only specified primus in the first package.json and not sockjs-client-node package.

**Comment by Dignifiedquire** [comment]
Yes, but that's the point, I don't want to add it as a dependency in the first package.json, as that one does not use the `sockjs-client-node` package.
I use the `dep1` package in multiple different locations with different requirements, so the requirement of `sockjs-client-node` should be fully contained inside the `dep1` package.

**Comment by 3rd-Eden** [comment]
Well yea, I get your point, but there's really nothing we can do about it as far as I know except depending on every single framework & client module we ship. I don't know if that's a wise thing to do as it adds a considerable amount of module bloat.

**Comment by BrighTide** [comment]
Have run into significant issues with this problem, which as far as I can tell occurs because the compiled primus.js looks for the ws module in the root directory the module is being called from, rather than whatever module has primus as a dependency. For instance

`
1 some_rad_module
2 |__node_modules
     |___application_communications_wrapper
            |____node_modules
                     |____primus
                     |____ws

`

primus won't look amoungst it's siblings, it'll look in the root

**Comment by 3rd-Eden** [comment]
I'm closing this issue as npm@3 flattens and dedups the `node_modules` folder.
