### ISSUE TITLE
Can I use websocket connect to primus server using SockJS transformer

### ISSUE THREAD

**Issue by TangMonk** [primus/primus#338]
I am focus on mobile development.

I used Socket.io, there are some Socket.io client for mobile, but not compatible for socket.io 1.x.

So I switch to Sockjs, because of the nice feature: [Connecting to SockJS without the client](https://github.com/sockjs/sockjs-client#connecting-to-sockjs-without-the-client), Another device can connect SockJS server only use websocket, that is awesome! But SockJS is low level, It don't provide auto reconnect feature, room feature, auth feature, and maybe more...

So I found primus from [node-ws issue list](https://github.com/einaros/ws/issues/263), It support SockJS and provide above features, so I am wanna to know, Can I connect SockJS transformer with without the SockJS client?

**Comment by 3rd-Eden** [comment]
Please don't submit issues with empty bodys by stuffing everything in the header. It's super annoying and frustrating to read.

I also don't understand your question. Please provide more details of what your trying achieve here.

**Comment by TangMonk** [comment]
@3rd-Eden I am sorry for my hurry, I updated my question and title, thanks :D

**Comment by 3rd-Eden** [comment]
You cannot connect a with a regular WebSocket as the SockJS framework requires a custom HTTP handshake and custom message encoding.
