### ISSUE TITLE
Can primus talk to a vanilla WebSocket client?

### ISSUE THREAD

**Issue by naartjie** [primus/primus#340]
Hi, I am trying to connect my iOS / Android apps to a primus server. Until now, I have been using engine.io transport for web clients.

1) Is there a way to connect to primus from a vanilla WebSocket client implementation, rather than a primus wrapper? 

2) Or maybe I am missing the Android primus implementation. For iOS I have found [Primus-Objc](https://github.com/seegno/primus-objc) (which is without engine.io support), but all I could find for android is this project: https://github.com/epoqueapp/primus-rxjava.

**Comment by 3rd-Eden** [comment]
Howdy,

Primus can talk to a vanilla WebSocket if you are using the `websocket` transformer. If you are already using `engine.io` you would need to find an engine.io compatible library for android/iOS.

(and you might need to do some extra protocol handling to support our primus::* related messages).

As far as I'm aware, there's only the Primus-Objc library at the moment for iOS.

**Comment by naartjie** [comment]
Thanks for the info.

It seems like right now the easiest way would be to keep engine.io for web clients, and add an additional primus instance for WebSocket connections from native iOS / Android, as WebSocket seems to have much more support / coverage.

The primus::* messages: are they described anywhere in more detail than [here]?(https://github.com/primus/primus#heartbeats-and-latency).

**Comment by 3rd-Eden** [comment]
@naartjie i'll add a dedicated section to the docs about the messages we send, i'll report back once done

**Comment by naartjie** [comment]
That would be awesome!! Thanks!!

**Comment by 3rd-Eden** [comment]
Added some documentation about it in the commit above, with indication from which side the message is send. Hope this helps.

**Comment by naartjie** [comment]
Many thank yous!!
