### ISSUE TITLE
encountering error code 426 when accessing primus.js

### ISSUE THREAD

**Issue by reidlai** [primus/primus#341]
After deployment, I try to access http://<<server url>>/primus/primus.js but encounter the following error (HTTP error code 426).  How can i download primus.js?  Thanks for your advice.

Failed to load resource: the server responded with a status of 426 (Upgrade Required)

**Comment by lpinca** [comment]
Did you customize the pathname or remove the `primus.js` middleware?
Your request seems valid but please share your Primus server configuration to get better help.

**Comment by 3rd-Eden** [comment]
We don't really send out 426 status codes so it seems that maybe a proxy or firewall is interfering here. Instead of downloading the library from `/primus/primus.js` you can also use the `Primus.save()` API method on the server to save the library to disk.

See https://github.com/primus/primus#client-library for more details on this.

**Comment by lpinca** [comment]
@3rd-Eden we do https://github.com/primus/primus/blob/master/transformers/websockets/server.js#L72

**Comment by 3rd-Eden** [comment]
@lpinca Thanks for the correction sir.

**Comment by blackbumer** [comment]
I have same problem.
I'm trying implement JWT token for primus.
Please look at https://gist.github.com/blackbumer/0fea5df3e7fd96cd1eea
I have couple questions:
1)How to store decoded token in spark instance?
2)How to do upgrade correctly?

**Comment by blackbumer** [comment]
'use strict';
var Primus = require('primus.io'),
    authParser = require('parse-bearer-token'),
    config = require('../../../config'),
    debug = require('debug')('myprimus'),
    jwt = require('jsonwebtoken');
 
function authCheck(token, req, done){
    jwt.verify(token, config.jwt_secret, function(err, decoded) {
        if (err) {
            debug('authCheck failed');
            done(err);
        } else {
            debug('authCheck passed');
            req.decoded_token = decoded;
            done();
        }
 
    });
}
 
function setup(server){
    var primus = new Primus(server, { transformer: 'websockets', parser: 'JSON' , timeout: 630000});
 
    primus.authorize(function (req, done) {
        var token;
 
        try { token = authParser(req) }
        catch (ex) { return done(ex) }
        authCheck(token, req, done);
    });
 
    primus.on('connection', function (spark) {
        debug('primus client connected');
    });
}
 
module.exports.setup = setup;

**Comment by lpinca** [comment]
@blackbumer you are using https://github.com/cayasso/primus.io, so make sure that your client is loading the correct library: `/primus/primus.io.js`.
If you try to load `/primus/primus.js` with https://github.com/cayasso/primus.io you'll get a 426 error.

**Comment by 3rd-Eden** [comment]
Based on the findings mentioned above i'm going to close this issue. If this issue can be reproduced in primus it self. Please re-open the issue with example code.

**Comment by Ghirigoro** [comment]
@3rd-Eden: Not sure if this related, but I'm having the same problem while using the standard primus (not the io variant). When I try to connect to a local server I get a 426 error (this is running on macOs 10.12.5, Node 8.1.0, Chrome 59.0.3071.115, Primus 7.1.0 from npm). 

Here's the relevant code. Am I doing something boneheaded or is it worth reopening this issue?

Given the following test project:

**server.js**
```
const Primus = require('primus');
const http = require('http');
const fs = require('fs');

const port = 3000;

const server = http.createServer(requestHandler);
server.listen(port);

const primus = new Primus(server);
primus.save(__dirname +'/primus.js');

function requestHandler(req, res) {
    fs.readFile(__dirname + '/index.html', function(err, data) {
        res.writeHead(err ? 500 : 200);
        res.end(err ? "Could not find page" : data);
    });
}
```
**index.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Primus Test</title>
    <script src="primus.js"></script>
</head>
<body>
</body>
</html>
```

**Comment by lpinca** [comment]
@Ghirigoro there are a couple of issues in your code:

1. Your request handler always uses the same response for all requests. This prevents you from loading js files on the client for example.

2. In your client code you are using `<script src="primus.js"></script>`. This creates a GET request to `http://<host>/primus.js`. This request is captured by primus as the pathname starts with `primus` and is passed to the transformer. It isn't an upgrade request and you are using a WebSocket only transformer so you get back a 426 error. To work around this issue you can use `<script src="/primus/primus.js"></script>`, use a custom pathname, change the name of your generated library (`primus.save(__dirname +'/primus.js');`) or put it in a subdirectory.

**Comment by Ghirigoro** [comment]
Boneheadedness it is... Thanks for taking the time to set me straight.
