### ISSUE TITLE
Using spark#pipe from primus-objc 

### ISSUE THREAD

**Issue by blackbumer** [primus/primus#343]
I wonder how to use Spark#pipe from objective-C client. How to upload file using streams?
I use Mongo GridFS stream library ( https://github.com/aheckmann/gridfs-stream )

```javascript
//server side
spark.on('fileUpload', function (data) {
        var writestream = gfs.createWriteStream();
        spark.pipe(writestream);
});
```
```swift
//client side (swift code)

// data = binary
socket.write(["data": ["fileUpload", data], "type": 0])
```

**Comment by 3rd-Eden** [comment]
I'm sorry for the late response, I completely missed this issue. I would suggest asking this question at objc project as I absolutely have no clue how it works :p
