### ISSUE TITLE
Primus Android

### ISSUE THREAD

**Issue by growlsworth** [primus/primus#346]
Hey Primus,

I've been a big fan for a while.

I need to support web and mobile now. I saw there's a [community iOS pod](https://github.com/seegno/primus-objc), but I couldn't find a good library for Android. So I made one! And put it here: https://github.com/cine-io/primus-android. It doesn't have all the features of the web client, but it does work. I was thinking of putting something in the README.md about community mobile libraries. What are your thoughts?

Thanks for all your hard work on Primus.

**Comment by lpinca** [comment]
@growlsworth awesome!
Add it [here](https://github.com/primus/primus#other-languages) right after `primus-objc`.
