### ISSUE TITLE
NPM release?

### ISSUE THREAD

**Issue by STRML** [primus/primus#352]
It's been almost 3 months since the last point release, and there have been a lot of changes, such as SockJS 1.0 support, compression, protocol-level `ping` support, lots of dep updates, and so on.

Is there anything blocking a release?

**Comment by lpinca** [comment]
`sockjs-client` is still in beta.

**Comment by 3rd-Eden** [comment]
I think we're just going to pull the trigger and release it and the end of this week.

**Comment by 3rd-Eden** [comment]
Released 3.0.(0/1)
