### ISSUE TITLE
Connection from Node does not work with custom path

### ISSUE THREAD

**Issue by tkurki** [primus/primus#354]
I have trouble connecting to Primus running ws with a custom path from Node. Http server is Express 4.10.5.

The client code at https://gist.github.com/tkurki/cea8ca6d0bee52214a44 does not give any debug or console output, unless I comment out the server's custom path as shown in the gist. 

If there is no custom path on the server the client configured with the custom path connects.

**Comment by lpinca** [comment]
@tkurki you have to use the `pathname` option in the `createSocket` method:
```js
// server.js
'use strict';

var Primus = require('primus')
  , primus
  , server;

server = require('http').createServer();
primus = new Primus(server, { pathname: '/signalk/stream' });

primus.on('connection', function connection(spark) {
  console.log(spark.id + ' connected');
});

server.listen(3000, function () {
  console.log('listening on port 3000');
});
```
```js
// client.js
'use strict';

var Primus = require('primus');

var Socket = Primus.createSocket({ pathname: '/signalk/stream' })
  , primus = new Socket('http://localhost:3000');

primus.on('open', function yay() {
  console.log('yay');
});
```

**Comment by tkurki** [comment]
Works like charm - thanks!
