### ISSUE TITLE
Maximum concurrent connection?

### ISSUE THREAD

**Issue by vinhjs** [primus/primus#355]
Server:
```
'use strict';

var express = require('express')
  , Primus = require('primus')
  , app = express();
  var http = require("http");

var server = http.createServer(app)
  , primus = new Primus(server, { authorization: null, transformer: "websockets"  });
primus.on('connection', function (socket) {
	
});
server.listen(8080);
primus.save(__dirname +'/primus.js');  
```

Client:

```
var Primus = require('./primus')
var async = require('async');

var count = 0;

async.whilst(
    function () { return count < 5000; },
    function (callback) {
        var primus = new Primus('http://localhost:8080/?query=string');
        primus.on('open', function(){
            count++;
            console.log('connections: ' + count);
            callback();
        })
    },
    function (err) {
        console.log('DONE');
    }
);
```
I am trying to run a code on Client but it stopped when var "count" increase to 1013.
I tried many times but still keep this result. Please help to explain the reason and help to give the solution to adjust this.
Many thanks.

**Comment by 3rd-Eden** [comment]
This is typical file descriptor limit that your reaching. I'm assuming that the maximum amount of file descriptors on your system is 1024. If you bump the limit (which is usually done using `ulimit -n 9999`) it will be able to handle more. (Please do note that this is not a limitation of Primus but the limitation of your operating system.)

**Comment by vinhjs** [comment]
Thanks. But I want to ask how to bump the limit on Ubuntu 14.04. I am researching Primus to replace our current lib.

**Comment by vinhjs** [comment]
I tried this command successfully (ulimit -n 9999) but still get this problem (Stopped when reaching to 1013)

**Comment by 3rd-Eden** [comment]
Have you tried changing it using the root account? Also in ubuntu there might other limits that need to be raised. You might need to bump it in `/etc/security/limits.conf` as well. But bumping file descriptor and other operating system limits is pretty well documented.

**Comment by vinhjs** [comment]
Thank you so much

**Comment by nikhilmahesh** [comment]
I am facing similar issue while making the connections from Mac, max is going till 1000. ulimit is unlimited.

**Comment by little-buddy** [comment]
@vinhjs Hi，buddy，How did you solve it in the end? I am facing similar issue

**Comment by JasonZigelbaum** [comment]
@little-buddy you can increase your file limit by entering ulimit -n 100000 in the console. There are several other settings you may need to configure as well to get maximum throughput. This article may help: https://www.zigpoll.com/blog/max-concurrent-socket-connections-node-express
