### ISSUE TITLE
Ideas for Primus + Heroku + Multiple Dynos?

### ISSUE THREAD

**Issue by varmint09** [primus/primus#361]
Hi,

I notice the sticky sessions issue, is that also why my App seems to crash after a minute or so?

Is there not a way to get Primus working on Heroku? Could someone point me to some materials to help fix my problem (and ideally not just a different host!).

Many thanks!

**Comment by akreienbring** [comment]
Have you read this issue: https://github.com/primus/primus/issues/345
Sticky sessions should not be an issue if you only use one dyno. 
Currently Heroko seems to test sticky sessions. Someone of the support crew added me to the test. I'll post into the mentioned issue as soon as I know more.

**Comment by varmint09** [comment]
Yes I did, but I want to use more than one dyno or the App will go idle.

I would imagine Heroku would be keen for this too, as its the difference between a paying customer and not!

@akreienbring Any idea what sort of ETA there might be?

**Comment by varmint09** [comment]
I have joined the test too, so this can be closed, or if left open I can update with my findings in a few days.

**Comment by lpinca** [comment]
@varmint09 I close this.
Feel free to post your findings here or in #345. Other people might find it useful.

**Comment by hunterloftis** [comment]
Feel free to ping me (hunter@heroku.com) if you're interested in joining the beta.
