### ISSUE TITLE
Connection works but receiving data doesnt

### ISSUE THREAD

**Issue by peterwilli** [primus/primus#369]
Hi,

I have used Primus many times over the years and am very happy with it! Recently I really got stuck in a problem where I just couldnt get it to work in a new project.

I pulled out the primus part and made a test-project to see if it works. It does connect, but data won't be either send or received! I tried in Chrome and Firefox.

I have also tried Node v0.12 and 0.12.2.
See below for full project + example code.
I literally copied the example and it still didnt work.
The primus version I use is 3.0.2 and engine.io is 1.5.1

**HTML**

    <html>

        <script src="http://localhost:8080/primus/primus.js"></script>
        <script>
            var primus = Primus.connect("http://localhost:8080");
            primus.on('connection', function (spark) {
                // spark is the new connection.
                console.log("connection");
                setInterval(function() {
                    spark.write("Hello?");

                }, 1000)
            });
            primus.on('error', function error(err) {
              console.error('Something horrible has happened', err.stack);
            });
        </script>

    </html> 

**Javascript (on Node)**
  
    var Primus;

    Primus = require('primus');

    Primus.createServer((function(spark) {
      console.log("connected");
      spark.on('data', function(d) {
        console.log('data', d);
      });
    }), {
      port: 8080,
      transformer: 'engine.io'
    });

I included the demo project which didn't work in a gzip file (https://mega.co.nz/#!udpSFDIS!WyPFoIdthOkK0dBThakcZ8vRbXyLudgwNr-zQ0uVDb8). I hope someone might be able to help. Thanks!

**Comment by lpinca** [comment]
There is no `connection` event on the client.
Rewrite this part:
```js
primus.on('connection', function (spark) {
  // spark is the new connection.
  console.log("connection");
  setInterval(function() {
    spark.write("Hello?");
  }, 1000)
});
```
like this:
```js
primus.on('open', function () {
  console.log('client connection');
  setInterval(function() {
    primus.write('Hello?');
  }, 1000)
});
```

**Comment by peterwilli** [comment]
Oh wow thanks @lpinca  I can't believe that didn't catch my attention! I guess because I haven't looked at a full example.
