### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by IngwiePhoenix** [primus/primus#372]
Hey there!

I am currently exploring my way outside of Socket.IO since I ran into a rather unpleasant problem; size. Socket.IO's client library weights 300kb uncompressed. In my final result, with all libraries and such thrown together and then compressed, I come to a 72kb file...assuming that all browsers support gzip, of course.

So I decided to take a stroll around and see what else there is. Primus was suggested to me by another developer that I know. He said it might be an alternative for me, but he currently is gone so I am going to ask here instead - if that is okay. :)

As already mentioned, I use Socket.IO currently. However, a while ago I had joined an organization, that provides a structure which is literally written for RPC purposes: http://github.com/hprose . Now, I'd like to use this.

hprose provides me with a few functions, but a given structure. The basic structure is, that:

- 4 bytes: They represent the length of the string
- 1 byte: The magnificent token. It indicates what this package is gonna be (A call, return value, ...)
- A structure similar but compacter and less human-friendly than JSON, on purpose.
- Each package ends with a z.
- If the **entire** packet contains 'z' only (one "z" character), then this means that the other party wants a function list. This is a special case.

And here is my first question: When I hook up to intercept incoming data, what would be a good idea to verify that the package is complete? Is it guaranteed that two packets arent jammed together in a way?

Next on, I wrote a little clustering module that implements sticky sessions. Would you say that NodeJS's latest `cluster` implementation is good enough? Alternatively, my module can use `child_process.fork` with sticky sessions too.

Then, when across workers or processes, how would I go about broadcasting data to all clients and not just to the one at hand?

If I was to use hprose for the transformation part, how can I use it on the client-side?

Sorry for all the many questions!
Kind regards,
Ingwie

**Comment by lpinca** [comment]
Hello @IngwiePhoenix,
take my answers with a grain of salt as I don't know what are your specific requirements.

> When I hook up to intercept incoming data, what would be a good idea to verify that the package is complete?

I would use a message transformer for this, see https://github.com/primus/primus#transforming-and-intercepting-messages.

> Is it guaranteed that two packets arent jammed together in a way?

Can you elaborate a little more here? I'm not sure if I understand this correctly.

> Would you say that NodeJS's latest cluster implementation is good enough? Alternatively, my module can use child_process.fork with sticky sessions too.

We don't recommend to use the cluster module for the reasons described here https://github.com/primus/primus#can-i-use-cluster. If you are not affected by those limitations then go ahead.

> Then, when across workers or processes, how would I go about broadcasting data to all clients and not just to the one at hand?

Take a look at https://github.com/primus/metroplex and https://github.com/primus/omega-supreme or a third party plugin like https://github.com/neoziro/primus-cluster.

> If I was to use hprose for the transformation part, how can I use it on the client-side?

Again, this sounds like a good use case for a message transformer https://github.com/primus/primus#transforming-and-intercepting-messages or a whole plugin.

**Comment by lpinca** [comment]
I close this, please post back if needed.
