### ISSUE TITLE
How to write end2end tests for a server?

### ISSUE THREAD

**Issue by episodeyang** [primus/primus#373]
Hi All, 

I am trying to write some tests. Right now for the json rest api I use mocha, supertest and superagent.

What is the best way to write test for the socket connection in primus? Pardon me if I missed this in the documentation.

Thanks!

**Comment by 3rd-Eden** [comment]
You can use the `.Socket` instance of the generated Primus server instance or the `primus.createSocket` API. See https://github.com/primus/primus#connecting-from-the-server for additional information.

**Comment by episodeyang** [comment]
Thanks! I saw that in the built-in test but wasn't sure about it. I will use this to write tests then!
