### ISSUE TITLE
Negative ping on set timeout

### ISSUE THREAD

**Issue by witem** [primus/primus#380]
On set property "timeout" when createSocket, client options "ping" has negative value. Test case:
```javascript
  var Socket, client;

  Socket = new Primus.createSocket({
    transformer: 'engine.io',
    timeout: 3000
  });

  client = Socket('http://192.168.0.1:1400');

  console.log(client.options);
```
**console.log out:**
```
 { queueSize: Infinity,
  timeout: 10000,
  reconnect: {},
  ping: -7000,
  pong: 10000,
  strategy: 'disconnect,online,timeout',
  transport: {} }
```

PS: the documentation says nothing about the fact that function **Socket**(in example) can take the second parameter of options. Example: 
```javascript
  var Socket, client;

  Socket = new Primus.createSocket({
    transformer: 'engine.io',
    timeout: 3000
  });

  client = Socket('http://192.168.0.1:1400', {
    reconnect: {
      max: 3000,
      min: 500,
      retries: Infinity
    }
  });
```

**Comment by lpinca** [comment]
> On set property "timeout" when createSocket, client options "ping" has negative value.

Yes, we subtract [`10000`](https://github.com/primus/primus/blob/5c056bf79eb2862402dcd1f35ddd359fd65057b4/index.js#L547) from the value of the heartbeat timeout, so if this value is `< 10000` you'll get a negative `ping` value on the client.
We've chosen this value with our defaults in mind and considering a max latency of `5` seconds.
Anyway you can override the `ping` value on the client. You only have to specify the `ping` option.
```js
var primus = new Primus(url, { ping: 1000 });
```
> the documentation says nothing about the fact that function Socket(in example) can take the second parameter of options.

`primus.Socket` or `Primus.createSocket()` return a constructor that is equivalent to the one used for the [browser](https://github.com/primus/primus#connecting-from-the-browser). You are probably correct here saying that it is not clear enough.
Pull requests are always welcomed!
