### ISSUE TITLE
Build script in package.json creates -p folder on Windows

### ISSUE THREAD

**Issue by axelboc** [primus/primus#382]
When executed, the following command from Primus' build script (in package.json) creates a `-p` directory on Windows :

    mkdir -p dist

This seems to be a common problem:
- https://github.com/jashkenas/coffeescript/issues/2027
- http://superuser.com/questions/816325/what-does-mkdir-p-create-as-the-parent-directory-or-way-to-see-its-effect

**Comment by 3rd-Eden** [comment]
@axelboc How is the problem as users never actually need to run the build script. As this is done only during releases.

**Comment by lpinca** [comment]
This will fix the issue:
```diff
diff --git a/package.json b/package.json
index fd0bbbf..f4ec689 100644
--- a/package.json
+++ b/package.json
@@ -5,7 +5,7 @@
   "main": "index.js",
   "scripts": {
     "integration": "npm run build && mocha $(find test -name '*.integration.js')",
-    "build": "mkdir -p dist && browserify primus.js -s Primus -p deumdify | derequire > dist/primus.js",
+    "build": "mkdirp dist && browserify primus.js -s Primus -p deumdify | derequire > dist/primus.js",
     "prepublish": "npm run build",
     "test": "npm run build && mocha $(find test -name '*.test.js')",
     "update": "find transformers -name update.sh -exec bash {} \\;"
@@ -80,6 +80,7 @@
     "engine.io-client": "1.5.x",
     "faye-websocket": "0.9.x",
     "jsonh": "0.0.x",
+    "mkdirp": "0.5.x",
     "mocha": "2.2.x",
     "pre-commit": "1.0.x",
     "primus-socket.io-client": "1.0.x",

```
but there are other bash scripts that will not work in Windows so I'm -1 with this change.

**Comment by axelboc** [comment]
@3rd-Eden I haven't reached the production stage yet, so I'm using the very convenient route provided by Primus to load the client library: `<script src="/primus/primus.js"></script>`.

However, when I do end up writing a release script, it will still be a bit dirty to have to add a step to delete the `-p` folder...

@lpinca Thanks for the diff. Would the other bash scripts you mention also be needed by Primus users (like this one is) as opposed to contributors? I haven't run into any other issue so far.

**Comment by lpinca** [comment]
@axelboc all the scripts, including the one to build the client, should only be used by Primus developers. It's not clear to me why you, as user, need to run the build script. Can you provide more details?

**Comment by 3rd-Eden** [comment]
The command you're referring to should only be called if you make actual changes to the Primus code base. If you are just looking to save the client so you upload it a CDN or re-compile it with code from plugins please use the `primus.library()` and `primus.save()` methods instead.

See https://github.com/primus/primus#client-library for more information.

**Comment by axelboc** [comment]
Well, that's the weird thing, I'm not actually calling this build script myself from anywhere. I just run my server with `node app` and the folder gets created. I don't call `primus.library()` or `primus.save()` either, which is why my first thought was that it was called internally by Primus in order to make the client library available to clients via `<script src="/primus/primus.js"></script>`. I'll investigate further and get back to you.

**Comment by axelboc** [comment]
Okay, I found the guilty module, and it's not Primus! Apologies for the confusion... Definitely not worth implementing this change. Nonetheless, thanks for pointing me to `mkdirp`. I'll use it to fix the issue in the other module.
