### ISSUE TITLE
Requiring client library - Cannot set property 'Primus' of undefined

### ISSUE THREAD

**Issue by ddennis** [primus/primus#383]
Hi.

It seems when i require the client library the UMDish IIFE is missing it's context, when i require it with browserify.

    Uncaught TypeError: Cannot set property 'Primus' of undefined

I saved out my client library.

    primus = new Primus(server ,{ parser: 'JSON' });
    primus.save(path.join(__dirname, '../../app/src/core/primus.js')  , function save(err) {
           console.log ("primus lib saved " );
    });

Inside my angular service i try to require it;

    var PrimusLib = require('../core/primus');

I dont really know how to fix it, without leaking to the global namespace.
But setting context = global, seems to fix it.

**Comment by lpinca** [comment]
This probably happens because `this` is `undefined` in the context where you require Primus.
See this comment https://github.com/primus/primus/issues/376#issuecomment-107242638.

**Comment by kkemple** [comment]
In case anyone else runs into this:
https://github.com/kkemple/primus-webpack-plugin
