### ISSUE TITLE
Authentication with Basic/JWT?

### ISSUE THREAD

**Issue by chrismbeckett** [primus/primus#385]
The examples in the documentation show using basic authentication. I am building a pure API, so the client application never authenticates their browser session with my API. I don't see anywhere when making a connection from the client to the server that you can set the Authorization header on the connection manually (you can only set query parameters).

My preferred method of authenticating would be to provide a REST API to login the user and return a JWT. The token can be added to the connection query string, and then could be validated that way.

In the broadcast example, it shows the query parameters have been parsed and are available on the spark:

```js
spark.query.foo !== 'bar'
```

Can I get the query parameters from the req in the authorize hook? The docs say the authorize hook is fired on every message, will the connection string parameters be available every time?

Any examples of suggestions on how to get Basic or Token to work with a pure API?

**Comment by lpinca** [comment]
@chrismbeckett take a look at this [example(]https://github.com/primus/primus/tree/master/examples/authorization)

**Comment by chrismbeckett** [comment]
@lpinca Perfect... just what I needed - I can grab the token from the connection string. Thank you.
