### ISSUE TITLE
Change query parameters after initial connection

### ISSUE THREAD

**Issue by axelboc** [primus/primus#386]
Is there any way to change the query parameters of the URL on the client after the initial connection has been made? I'd like to pass some sort of ID parameter when reconnecting, but I don't know that ID until the initial connection is successful.

Here is the scenario in details: let's say that the client initially connects with http://localhost:8080. After the connection succeeds, the server sends an identifier to the client. Now the server crashes then restarts, and the client manages to reconnect. How can the client pass the identifier as a query parameter during the reconnection?

**Comment by lpinca** [comment]
Hi, you can listen to the `outgoing::url` event in the client. It is fired every time the client tries to connect.
```js
primus.on('outgoing::url', function (url) {
  //
  // Change the query-string too 'foo=bar'.
  //
  url.query = 'foo=bar';
});
```

**Comment by axelboc** [comment]
Thanks!!

**Comment by episodeyang** [comment]
Hi @lpinca 

I am trying to use this, and it turned out that if I just do what you mentioned, I couldn't really change the query string. 

In the end I tried :


```javascript
    function attachJwtToken (url) {
        //console.log(primus);
        //if (!accounts.user || !accounts.user.accessToken) return;
        //if (url.query) url.query = url.query + '&access_token=' + accounts.user.accessToken;
        primus.url.query = '?access_token=' + accounts.user.accessToken;
    }
```
and it allowed me to patch the query string with this access token. 

Is this normal, and what was wrong?
