### ISSUE TITLE
Can I get a client library in CommonJS style for Webpack?

### ISSUE THREAD

**Issue by jiyinyiyong** [primus/primus#390]
We are using Webpack and primius's generated `client.js` file triggers Webpack's warnning on every page load. I there a CommonJS copy I can import in my project please?

![screen shot 2015-08-20 at 1 42 02 pm](https://cloud.githubusercontent.com/assets/449224/9376564/6198249a-4741-11e5-87c2-764cc6cec6a3.png)

**Comment by lpinca** [comment]
The short answer is no. The client needs to be "compiled" to include the plugins, the parser, the transformer, etc. and the "compiler" only returns the bundle.

**Comment by lpinca** [comment]
Closing this, please post back if needed.

**Comment by jiyinyiyong** [comment]
Any alternative approches for the case?

**Comment by lpinca** [comment]
I think that ignoring the warnings is the only way atm, assuming that everything works fine.

**Comment by 3rd-Eden** [comment]
This is something that should be solved in WebPack, not in this library. It's not up to us to fix the invalid warnings that they generate. I suggest opening an issue in the WebPack project asking for a way to opt-out of these debug messages.

**Comment by jiyinyiyong** [comment]
I think Webpack is right about giving warning about package libraries even being annoying. And it's actually out fault to use packaged code as source code. I'll try to find a solution in Webpack.

**Comment by crossman** [comment]
For what it's worth, I ran into the same issue and just ended up loading the compiled client lib with the [script-loader module](https://github.com/webpack/script-loader). I don't get any warnings and everything works perfectly.

```js
import "!script!./lib/sockets/client.js"
```

**Comment by jiyinyiyong** [comment]
@crossman thanks. Good reason to try it.
