### ISSUE TITLE
error handling on spark.write

### ISSUE THREAD

**Issue by siddo420** [primus/primus#393]
What happens when spark.write is executed but the connection has already failed on that spark (making the spark object invalid by the time it is called). 

Does primus throw an exception or not? In other words, is it recommended to put the spark.write call in a try/catch block or there is a better/valid way to deal with this?

**Comment by lpinca** [comment]
If the connection is closed `spark.write` will return `false`, no exception is thrown.

**Comment by siddo420** [comment]
Ok, so "This method always returns true so back pressure isn't handled." at https://github.com/primus/primus#sparkwritedata is a bit confusing. 

Instead, something like below would make more sense.
"This method always returns 'true' on success and 'false' on failure, so back..."

Is there a limit (or recommendation) for the max size/bytes of data that should be transported in one go?

**Comment by lpinca** [comment]
There is no limit in Primus itself but some of the underlying realtime frameworks may have one. For example the `faye` transformer sets this limit to 64 MiB.

**Comment by lpinca** [comment]
Closing this, please post back if needed.

**Comment by siddo420** [comment]
Is it possible to verify if a spark object is in/valid without calling .write()? I am looking for .isValid() or .isConnected() type method.

**Comment by lpinca** [comment]
You can use the `readyState` property:
```js
if (spark.readyState === Spark.OPEN) {
  // Do stuff.
}
```
