### ISSUE TITLE
Connecting two node apps: createSocket does not work for us

### ISSUE THREAD

**Issue by AleCaste** [primus/primus#396]
We have two node applications (let's call them nodeapp1 and nodeapp2).
Both are running Express.
nodeapp1 is behind an nginx reverse proxy taking care of SSL connections.
nodeapp1 runs the primus server-side library using sockjs as the transformer.

From a browser (we tested this on Chrome) we loaded the primus.js client-side library and tried to connect to nodeapp1:
```
  primus = new Primus('https://nodeapp1domain');
  primus.write('hello');
```
The above test was successful.

Now we wanted to do the same (connect to nodeapp1) but not from the browser but from nodeapp2.
To do so we did the following:
```
  Socket = new Primus.createSocket();
  primus = new Socket('https://nodeapp1domain', {
    transformer: 'sockjs',
    pathname: '/primus',
    parser: 'JSON',
    timeout: 35000
  });
  primus.write('hello');
```
The above does NOT work!
nodeapp1 does never receive the message from nodeapp2.
Are we doing something wrong?
Why is it that we can connect from the browser but not from nodeapp2 ?

NOTE: we can get the specs from nodeapp1 server visiting:
```
https://nodeapp1domain/primus/spec
```
... and we get the following:
```
{"version":"3.1.1","pathname":"/primus","timeout":35000,"parser":"json","transformer":"sockjs"}
```

**Comment by AleCaste** [comment]
**Update:** We tried to perform the test without SSL. We did the following from nodeapp2:
```
  Socket = new Primus.createSocket();
  primus = new Socket('http://nodeapp1domain', {
    transformer: 'sockjs',
    pathname: '/primus',
    parser: 'JSON',
    timeout: 35000
  });
  primus.write('hello');
```
... which did NOT work. But doing the following:
```
  Socket = new Primus.createSocket({
    transformer: 'sockjs',
    pathname: '/primus',
    parser: 'JSON',
    timeout: 35000
  });
  primus = new Socket('http://nodeapp1domain');
  primus.write('hello');
```
... DID work indeed. Any idea why? Aren't the two ways equivalent?
In any case this works when not using SSL.
If we use SSL none of the above ways work (but then again, connecting from the browser DOES work).

Please help...

**Comment by 3rd-Eden** [comment]
The last example you posted works as that is the intended API. See https://github.com/primus/primus#connecting-from-the-server
