### ISSUE TITLE
Transformer initialise should pass context to "previous" events

### ISSUE THREAD

**Issue by colinbate** [primus/primus#397]
**Version:** 3.2.3
**Environment:**
 - **OS:** Mac OSX 10.10.5
 - **io.js:** 3.0.0
 - **npm:** 2.13.3
 - **browser:** Any

**Expected results:**
Non-primus requests to be passed to the underlying server and handled correctly including the context of the handler.

**Actual results:**
`TypeError`s in the original `request` handler when trying to use properties on `this`.

This is particular to the case when the underlying server passed to Primus is a sub-class of `http.Server` which defines `request` handlers on itself using the assumption that `this` is the default context. When those handler functions are set as handlers to `previous::request` on the Transformer they lose their original default context.

**Steps to reproduce:**
1. Open terminal and create a new folder called `primus-context-loss`
2. `cd primus-context-loss`
3. `npm install primus@3.2.3`
4. `npm install ws`
5. Create and open for editing a file called `index.js`
6. Add the code which follows step 10 in this list to `index.js` and save it
7. `node index.js`
8. Hit http://localhost:8000 in any browser (or curl or whatever)
9. You will see a stack trace in your terminal starting with `TypeError: Cannot read property 'name' of undefined`.
10. If you comment out the second last line in the `index.js` file (removing Primus), and repeat steps 7-8, you should see `Name: MyServer` in the browser.

```js
var http = require('http'),
    util = require('util'),
    Primus = require('primus');

function MyServer() {
  http.Server.call(this);

  this.opts = {
    name: 'MyServer'
  };

  this.on('request', this.handle);
}

util.inherits(MyServer, http.Server);

MyServer.prototype.handle = function (req, res) {
  if (req.url === '/') {
    res.end('Name: ' + this.opts.name);
  }
}

var server = new MyServer();
var primus = new Primus(server, { transformer: 'websockets' });
server.listen(8000);
```

**The Fix (as I see it)**
If you change `transformer.js:58` to the following it should fix the issue. A similar change would be made on line 63 for upgrade.

```js
transformer.on('previous::request', fn, server);
```

Happy to make a PR if desired.

**Comment by 3rd-Eden** [comment]
First of all, thanks for taking the time to write such a extensive bug report and providing us with a fix for the issue!

We'll patch it up and it will be in the next release!

**Comment by lpinca** [comment]
This bug report is top-notch. Thank you @colinbate!
