### ISSUE TITLE
Usage with JSPM

### ISSUE THREAD

**Issue by perrin4869** [primus/primus#402]
I'd be interested in using the Primus client as a JSPM and System.JS, and include it in my bundle... I don't want to use it as a global. Is there any way to do that?

**Comment by lpinca** [comment]
I don't know about JSPM but it is possible with browserify or webpack.
With browserify you have to require the compiled primus client like a module.

**Comment by perrin4869** [comment]
I see! Sounds good, I'll try to use it with System.JS and then report back with the results :)

**Comment by roblabla** [comment]
In your `config.js`'s : 
```
System.config({
  // ...
  map: {
    "primus": "/primus/primus.js"
  }
  // ...
});
```

This well tell SystemJS (the dep loader of JSPM) to load /primus/primus.js when you import "primus".
