### ISSUE TITLE
include file in browserify bundle

### ISSUE THREAD

**Issue by episodeyang** [primus/primus#407]
Hi, 

I am trying to use browserify to bundle up my client-side javascript. I saw here #122 that there is currently not a way to bundle primus. Is this still the case?

Thanks for this great library!
Ge

**Comment by lpinca** [comment]
Hey,
bundling primus with browserify should work. You have to build the client as defined [here](https://github.com/primus/primus#client-library) and then require the "compile" library.

**Comment by episodeyang** [comment]
Thanks @lpinca!

I guess it is a bit tricky since in this cause one need to:

1. run a node script that `primus.save('/src/components/primus/primus.js')`
2. run gulp, so that `/src/**/primus.js` got copied to `/dist/**/primus.js`

or I can just make a separate request for the primus.js like how I do it now. Except that now my api server is actually in a different sub domain.

How do you guys use it at work?

and thanks!
Ge

**Comment by lpinca** [comment]
> I guess it is a bit tricky since in this cause one need to:

> 1. run a node script that primus.save('/src/components/primus/primus.js')
> 2. run gulp, so that `/src/**/primus.js` got browserified to `/dist/**/bundle.min.js`

That's how I use it except for gulp. You have to build the client only once (unless you change the primus configuration) so it's not very different from other libraries that work with browserify.

**Comment by episodeyang** [comment]
kk got it! I will do it this way then.

**Comment by django43ru** [comment]
It doesn't work to me. It works, if I include primus.js directly on the webpage, but it doesn't work with browserify. I tried both methods to import Primus (in the typescript: import {Primus} from './primus' or var Primus=require('./primus')). Browserify includes primus.js into the result file without any warnings, but in the console on the webpage I see "Primus is not defined"...

**Comment by django43ru** [comment]
Well, I found a solution here: https://github.com/substack/node-browserify/issues/868 "You should just do global.jQuery = require("jquery")." So, I added the string **global.Primus = require("./primus")** on the top of my file and now it works.

**Comment by lpinca** [comment]
Can you show an excerpt of how you use it? I'm not sure why you need to add a `Primus `property to the `window` object if you are using browserify.

**Comment by django43ru** [comment]
I only wrote global.Primus=require('./primus') instead var Primus=require('./primus') on the top of the javascript file.

**Comment by lpinca** [comment]
Yes, but when and where do you call `new Primus()`?

**Comment by django43ru** [comment]
Ok, my file looks like this: 

```
/// <reference path="./../../../typings/primus/primus-client.d.ts"/>
import {DesktopDef} from  './gameAbstract'
import {ICommunication} from  './communication'
import {GameCommon} from  './gameCommon'
import {Utils} from  './../utils/utils'

//var Primus = require('./../utils/primus');

global.Primus = require('./../utils/primus'); 

export module GameBroker {
  export class Broker{
       private primus: Primus;
    .......

    constructor(){
        this.primus = new Primus();
    }
  }
}
```
?..

**Comment by lpinca** [comment]
Looks legit, I don't know what's wrong, it should work with just `var Primus = require('./../utils/primus');`.

**Comment by django43ru** [comment]
Yes,I'm confused too, but don't have enough time to dig into it. However, thank you, guys, for you excelent job!

**Comment by django43ru** [comment]
By the way, Visual Studio Code intellisense doesn't see module Primus in the primus.js, in other cases it see everything very well.

**Comment by halodevcr** [comment]
Any idea why this is working with the global approach?
