### ISSUE TITLE
removing event listeners and wildcards in event names

### ISSUE THREAD

**Issue by siddo420** [primus/primus#409]
How do I remove event listeners on server and client? Is there a .off() method too?

Is it possible to listen to events using wildcards in event names like primus.on( 'msg-*', ... )? This may be a feature request

**Comment by lpinca** [comment]
Internall Primus uses [`eventemitter3`](https://github.com/primus/eventemitter3) which has the same interface of the [`EventEmitter`](https://nodejs.org/api/events.html#events_class_events_eventemitter) built-in in Node.js.

 > Is it possible to listen to events using wildcards in event names like primus.on( 'msg-*', ... )?

No, `eventemitter3` does not support this feature.
