### ISSUE TITLE
Typescript definition mappings?

### ISSUE THREAD

**Issue by YLivay** [primus/primus#410]
Primus is too great to not be available for Typescript users with proper definitions.
One time hassle, only needs to update on API changes.
Is there any chance we might see them in the future?

**Comment by 3rd-Eden** [comment]
I am not a typescript user my self, so if you want to see this happen, it should be contributed by the community and i'll be more than happy to merge it in.

**Comment by 3rd-Eden** [comment]
TS mapping are available in 4.0.5!

**Comment by django43ru** [comment]
Yes, and the def file has name **primus.d.ts** and it placed in the root of primus github directory. https://github.com/primus/primus/blob/master/primus.d.ts
