### ISSUE TITLE
how to add JWT access token to all outgoing streams?

### ISSUE THREAD

**Issue by episodeyang** [primus/primus#412]
Hi @lpinca 

I am trying to switch to Json web token for my authentication, and it turned out that if I just do what you mentioned here at #386 , I couldn't really change the query string. 
The I do what you said in #386, I keep getting the following request which is missing the access_token field I added:

```shell
http://localhost:8000/api/v1/stream/?_primuscb=L4UDWrS&EIO=3&transport=polling&t=1447910837596-3&b64=1
```

In the end I tried :

```javascript
    function attachJwtToken (url) {
        //console.log(primus);
        //if (!accounts.user || !accounts.user.accessToken) return;
        //if (url.query) url.query = url.query + '&access_token=' + accounts.user.accessToken;
        primus.url.query = '?access_token=' + accounts.user.accessToken;
    }
```
and it allowed me to patch the query string with this access token. 

Is this normal, and what was wrong?

**Comment by episodeyang** [comment]
So it turned that that the example is intact working, but I just have to use the native primus.on method, instead of the angular-primes $on method. 

I was using the angular-primus $on method. [angular-primus issue #10](https://github.com/neoziro/angular-primus/issues/10)

**Comment by episodeyang** [comment]
@lpinca 

Although it looks like this is a problem with angular-primus, I looked at their source and there isn't anything obviously wrong there. Their wrapper function for the primus.on function is the following: what could be the source of the bug?

```javascript
    primus.$on = function $on(event, listener) {
      // run the listener in Angular context
      primus.on(event, listenerInAngularContext);

      function listenerInAngularContext() {
        var args = arguments;
        $rootScope.$evalAsync(function () {
          listener.apply(null, args);
        });
      }

      // Return the deregistration function
      return function $off() {
        primus.removeListener(event, listenerInAngularContext);
      };
    };

```

**Comment by episodeyang** [comment]
I think I know the problem now. They used a evalAsync.

**Comment by lpinca** [comment]
I guess that `$evalAsync` call the listener asynchronously, right (I don't know angular)?

**Comment by episodeyang** [comment]
That's right! so changing it to $eval fixed the issue!
