### ISSUE TITLE
Help - Replace socketio code with primus 

### ISSUE THREAD

**Issue by pnreddysvu** [primus/primus#415]
I am new to Primus. Can any one tell me how to rewrite the below code with Primus and SockJs-Client
with automatic reconnection?

https://github.com/andyet/SimpleWebRTC/blob/master/socketioconnection.js

**Comment by lpinca** [comment]
Hi,
the problem here is that the above code is designed to talk with a Socket.IO 1.x server.
You can't use Primus and the sockjs transformer to connect to a Socket.IO server.

**Comment by pnreddysvu** [comment]
@lpinca thank you for the reply.
I have already modified the server part. Now the server is developed using spring-boot websockets which uses SockJS internally. So I want to convert the client code to use sockjs too. I thought of modifying the client to use Primus with SockJS so that automatic re-connection works seamlessly.

**Comment by pnreddysvu** [comment]
And also there was a PR to pass any type of connection.
https://github.com/andyet/SimpleWebRTC/pull/210

So I assume Primus should work if we modify 
https://github.com/andyet/SimpleWebRTC/blob/master/socketioconnection.js

**Comment by lpinca** [comment]
@pnreddysvu you also need a Primus server because you have to:

- handle the heartbeats.
- include the emitter plugin.
- encode and decode the messages with the same parser used by the client.

**Comment by pnreddysvu** [comment]
oh ok. I thought Primus is a wrapper and works with any type of server. Seems my understanding was not correct. I cannot include Primus server. Seems I have to sockjs-client only.

Thanks for the information. I will close this.

**Comment by lpinca** [comment]
@pnreddysvu we use [recovery](https://github.com/unshiftio/recovery) in Primus to handle the reconnection. I don't know but maybe you can you use that module to implement a reconnection system on top of SockJS-client.
