### ISSUE TITLE
How to reconnect to a different URL?

### ISSUE THREAD

**Issue by Unitech** [primus/primus#416]
Thanks for this lib!
Is there any way to re connect to a different URL with the instancied primus object?

**Comment by 3rd-Eden** [comment]
I would say no, but yes, it should be possible. But it's not easy though. The client emits an `outgoing::url` event for each time an URL has been requested. You could check during this event, if it's reconnecting and change the details in the supplied object so it generates a new URL for the request.

**Comment by Unitech** [comment]
It may be interesting to have this method in the future. For now I will call the .destroy method and re instanciate a new primus object with the new url,

thanks

**Comment by 3rd-Eden** [comment]
See https://github.com/primus/primus/blob/66b5272041be41562ea1af46e340b3cb98c1fcb4/examples/authorization/public/js/client.js#L15-L21for an example. But destroying and recreating also works, but you will not be able to benefit from the reconnection functionality inside of primus.
