### ISSUE TITLE
Monitoring metrics

### ISSUE THREAD

**Issue by Unitech** [primus/primus#417]
We successfully integrated Primus in keymetrics.io to replace our old socket.io (0.9.x) realtime system! It's running on staging for some day before we publish it in production. 

Thanks for this awesome lib!

Now I would like to [monitor some "key metrics"](http://docs.keymetrics.io/docs/pages/custom-metrics/) by getting data from Primus internals. I already put custom metrics to monitor number of socket opened,

Which metrics would make sense to measure over the time? Can we extract some latency metrics from Primus?

**Comment by 3rd-Eden** [comment]
Have you seen https://github.com/primus/primus-analytics ?

**Comment by Unitech** [comment]
Interesting I didn't know this module. 
I'm thinking about injecting some code in the client lib then doing some sort of measurement to see the latency of message sent between the server and client,

**Comment by 3rd-Eden** [comment]
You can also check the latency property on the client. It uses the ping transmission between server and client to calculate the latency. 

Arnout Kazemier

**Comment by Unitech** [comment]
I found this also: https://github.com/Fishrock123/primus-spark-latency
