### ISSUE TITLE
How to specify headers or cookies to send with connection requests from Node.js

### ISSUE THREAD

**Issue by cflynn07** [primus/primus#419]
I'm connecting to a primus server from another node.js process and I need to attach a session cookie to the initial http request. When connecting from a browser cookies are automatically attached. I can't seem to find any documentation on how to do this from a non-browser/Node.js client. The transformer I'm using is `websockets`

**Comment by lpinca** [comment]
You can use the `transport` option. See https://github.com/primus/primus#connecting-from-the-browser
For example in your case:
```js
'use strict';

const Primus = require('primus');
const http = require('http');

const server = http.createServer();
const primus = new Primus(server);

primus.authorize((req, done) => {
  console.log(req.headers.cookie);
  done();
});

primus.on('connection', spark => console.log(spark.id + ' connected'));
primus.on('disconnection', spark => console.log(spark.id + ' disconnected'));

server.listen(3000, () => {
  new primus.Socket('http://localhost:3000', {
    transport: {
      headers: { 'Cookie': 'foo=bar' }
    }
  });
});
```

**Comment by lpinca** [comment]
The list of options supported by `ws` is documented [here](https://github.com/websockets/ws/blob/master/doc/ws.md#new-wswebsocketaddress-protocols-options).

**Comment by lpinca** [comment]
Closing this, please post back if needed.

**Comment by vinnymac** [comment]
@lpinca Above you mention how one would do this for `websockets`. I see you can do something similar [here](https://github.com/socketio/engine.io-client#nodejs-with-extraheaders) for `engine.io`. Any idea how one would send cookies via nodejs for SockJS? I could not find any documentation on this.

**Comment by lpinca** [comment]
@vinnymac If I'm not wrong this is not supported by SockJS.

**Comment by vinnymac** [comment]
@lpinca fortunately this is node, and I can just do it manually. For anyone who comes across this. You can add headers to the initial `GET` request [here](https://github.com/sockjs/sockjs-client/blob/05c8404c626391ce054072991e8f702e9517c0d0/lib/transport/driver/xhr.js#L26), and you can add headers for the `websocket` connection [here](https://github.com/sockjs/sockjs-client/blob/master/lib/transport/websocket.js#L31). Just add a headers object to the options passed into the `WebsocketDriver `. Thanks for the prompt response pushing me in the right direction.
