### ISSUE TITLE
cannot set property query error

### ISSUE THREAD

**Issue by VarunBatraIT** [primus/primus#420]
I am using latest primus with total.js framework 

I am getting error as 
```
[09/01/2016 03:12:24.029] [LOG]   [TypeError: Cannot set property query of #<IncomingMessage> which has only a getter]
[09/01/2016 03:12:24.029] [LOG]   ======= 2016-01-09 03:12:24: TypeError: Cannot set property query of #<IncomingMessage> which has only a getter TypeError: Cannot set property query of #<IncomingMessage> which has only a getter
    at child.forEach (bla/node_modules/primus/transformer.js:107:13)
    at child.upgrade (bla/node_modules/primus/transformer.js:209:8)
    at emitThree (events.js:97:13)
    at Server.emit (events.js:175:7)
    at onParserExecuteCommon (_http_server.js:398:14)
    at HTTPParser.onParserExecute (_http_server.js:366:5)

```

It is from the line

https://github.com/primus/primus/blob/master/transformer.js#L107

I did this:

```js
framework.on('ready', function () {
    this.primus = new Primus(this.server);
    this.primus.save(F.path.public("/js/primus.js"));
 
    framework.eval(function () {
        Controller.prototype.primus = function () {
            return framework.primus;
        };
    });
});
```

So technicall I am doing exactly what one could have done in express.js 

Of course my js code is: 

```js
var primus = new Primus();
```

I did get a reqeust in backend and in primus files, however it just doesn't work because of the mentioned problem. 

If this is a bug in totaljs/primus or this is just a compatibility issue?

**Comment by lpinca** [comment]
I don't know total.js but my guess is that it sets a `query` property (a getter) on the request object under strict mode, so when primus tries to set the property an error is thrown.

**Comment by lpinca** [comment]
Replacing https://github.com/primus/primus/blob/9baed6cf65c3544928e767079d26a6cc6489f4fe/transformer.js#L107 with
```js
if (!('query' in req)) req.query = req.uri.query;
```
should fix this but I'm not totally happy with it.

**Comment by VarunBatraIT** [comment]
@Ipnica What would be the implications? I am noob sorry. 

And it isn't about happiness it is about making it work :) 

I will be speaking with the Totaljs guy. He is also a very proactive in these cases.

**Comment by lpinca** [comment]
There are no issues with the above approach but IMHO it's better to also provide a setter (it can be a noop function) when defining the `query` property on the request.

**Comment by VarunBatraIT** [comment]
For the time being I will do some hacks. However, I am very sure that next totaljs will have it. Do you think that it is a good idea that Primus should also take care of it with your proposed solution to avoid similar bugs in various other frameworks?

**Comment by VarunBatraIT** [comment]
But lets just wait for the comments perhaps it has been done in some different way :+1:

**Comment by lpinca** [comment]
We assume to receive a plain [`IncomingMessage`](https://nodejs.org/api/http.html#http_http_incomingmessage) object, not a spiced-up one, so I'm personally :-1: for fixing this in primus.

**Comment by VarunBatraIT** [comment]
I think most fraemwork spice it up to append some useful information https://github.com/totaljs/framework/blob/master/index.js#L14465 We do have something here. :) 

I will just wait for totaljs feedback on it.

**Comment by petersirka** [comment]
@VarunBatraIT I have fixed it, please install a latest beta version of total.js `npm install total.js@beta`.
@lpinca thanks again for the report.

**Comment by VarunBatraIT** [comment]
@petersirka @lpinca Thanks for the teamwork. :+1:
