### ISSUE TITLE
Client receiving heartbeat event + ping::pong after update to 4.0.4 

### ISSUE THREAD

**Issue by SaikiranDaripelli** [primus/primus#422]
Hi,
   We are using primus from about an year and recently i upgraded library from 2.x to 4.0.4 and noticed that client is receiving a hearbeat frame, and a ping::pong frame. 
I receive,
a["\"primus::pong::1452602792101\""] and a["{\"emit\":[\"heartbeat\"]}"] frames every time pong happens.
Is there any setting to only have ping::pong?
Is there any significance for both frames?

I am suspecting #359 + "primus-emit" plugin is causing this event to reach client.

**Comment by lpinca** [comment]
Hi,
good catch! Thank you for reporting this.

Fixed in a7a090f62761140a42cfea9246801d1f86dc0fb2.

**Comment by 3rd-Eden** [comment]
Fixed in 4.0.5 thanks for reporting
