### ISSUE TITLE
End event sometimes emits after connection on reconnect (server)

### ISSUE THREAD

**Issue by goldfire** [primus/primus#424]
**Version:** 4.0.5
**Node:** 4.2

**Client Settings:**

```javascript
{
  reconnect: {
    min: 250,
    retries: 50
  },
  ping: 25000
}
```

We mark users as connected when the server `connection` event fires and we add their socket to an array to keep track of. We then setup a listener:

```javascript
socket.on('end', function(){
    // splice the socket and mark user as offline
});
```

This generally works fine, but sometimes if a user briefly loses connection to the server, the `end` event gets emitted after the new `connection` event. I haven't been able to reproduce this locally, but I can reproduce fairly easily over a remote server by turning my wi-fi on/off.

I've been debugging this for a few hours and so far haven't been able to figure out why this is happening and where the bug might be. Anyone have any ideas?

**Comment by lpinca** [comment]
What transformer are you using?
I think that this happens because the `end` event (say https://github.com/primus/primus/blob/0809e1a507ae141e72bf5abe4b50115d135d53a7/transformers/websockets/server.js#L61) is not fired immediately if you simply unplug the network cable.

**Comment by goldfire** [comment]
Sorry, forgot to mention that we are using `ws`. Right, that is what I understood to be going on, but is there no workaround for this? It doesn't seem like it should be expected behavior to receive an `end` event from a client that has already reconnected.

**Comment by lpinca** [comment]
The re-connection is a whole new connection and the corresponding spark should have a different id.

I remember fighting with this as well some time ago, but if IIRC this happens also when using `ws` directly and we react on its `close` event.

The point is how we detect that the spark is dead if the underlying socket `ws` is this case does not emit the `close` event?

**Comment by goldfire** [comment]
Okay that makes sense. I keep thinking about it from a "user" perspective rather than a distinct connection perspective. Keeping track of both the previous and current socket ID for each user allows us to get around this problem well enough. Thanks!
