### ISSUE TITLE
plugin unable to determine if running in node.js or browser

### ISSUE THREAD

**Issue by brycekahle** [primus/primus#425]
I'm trying to create a node to node connection using `mirage`, `primus-emit`, and `primus-responder` as plugins.

I receive the following error when calling `Primus.createSocket`:
```
primus.js:3256
    _previousRoot = _window.uuid;
                           ^

TypeError: Cannot read property 'uuid' of null
    at primus.js:3256:28
    at primus.js:3266:3
    at libraryWrap (primus.js:3403:3)
    at primus.js:3404:3
    at Object.exports.runInContext (vm.js:44:17)
    at Function.compiler (/xxx/node_modules/load/index.js:56:6)
    at Primus.Object.defineProperty.get (/xxx/node_modules/primus/index.js:176:28)
    at Function.createSocket (/xxx/node_modules/primus/index.js:1059:16)
```

I traced it down to [this line](https://github.com/broofa/node-uuid/blob/309512573ec1c60143c257157479a20f7f1f51cd/uuid.js#L262) in `node-uuid` required by `primus-responder`. This code branch happens because `module` and `module.exports` are undefined, instead of using the branch designed for node.js. 

The root of this issue is when Primus is [generating the library](https://github.com/primus/primus/blob/0809e1a507ae141e72bf5abe4b50115d135d53a7/index.js#L176) for node.js, it runs the code within a `vm`. This vm does not contain the `module` global. 

Is defining `module` to be `{ exports: {} }` in the [options to `load.compiler`](https://github.com/primus/primus/blob/0809e1a507ae141e72bf5abe4b50115d135d53a7/index.js#L176)  sufficient, or is there a better solution?

Note: I wasn't sure if this should be addressed in Primus, or the [`load`](https://github.com/3rd-Eden/load) module.

**Comment by lpinca** [comment]
This is strange as `load` already adds the `module` global in the context, see https://github.com/3rd-Eden/load/blob/def8e93a0c1daee17a01d7ab69274d892e3d9311/index.js#L91-L97.

**Comment by lpinca** [comment]
Forget my previous comment.
I think it stopped working after this https://github.com/broofa/node-uuid/commit/c9760f931d36bf01143dd2a78110ca05061e39e7.

**Comment by lpinca** [comment]
Unfortunately setting the `module` global (`{ exports: {} }`) in the vm `context` does not help as `primus-responder` requires a globally defined `uuid`, see https://github.com/swissmanu/primus-responder/blob/6bb81f75ff5754b041b8fb28ed591475251fc243/lib/client/index.js#L146.

**Comment by lpinca** [comment]
https://github.com/swissmanu/primus-responder/pull/6 should fix the issue.

**Comment by brycekahle** [comment]
Awesome, thanks!
