### ISSUE TITLE
timing/availability of primus resources

### ISSUE THREAD

**Issue by afrozl** [primus/primus#427]
I'm trying to dynamically load content after a page loads, however I'm having issues with the timing of resource availability. For example, I have a page that only loads headers and a container for html content.  The js initializes primus and makes a request for content:

<pre>
        var rpc = Primus.connect();
        var rpcQuery = rpc.resource('query', false);
        var query = ({ page: 1 });
        rpcQuery.paginate(query, function(res) {
                conole.log(res);
            });
</pre>

However, no matter where I place this code, whether in a <pre>document.ready</pre>  block or not, I consistently get:

<pre>query.js:57 Uncaught TypeError: rpcQuery.paginate is not a function</pre>

Obviously typing the command in the console after the page loads works every time.

Any suggestions on how to fix this?

**Comment by lpinca** [comment]
@afrozl I can't help you with this as I'm not familiar with `primus-resource`, maybe you have to wait the [`ready`](https://github.com/cayasso/primus-resource#on-the-client) event?

**Comment by afrozl** [comment]
that was it!

thank you!. I guess I should rtfm... :)
