### ISSUE TITLE
session sharing across multiple hosts

### ISSUE THREAD

**Issue by afrozl** [primus/primus#428]
session sharing appears to work fine if I am using the same host + port  for primus and http. However, if I use different hosts/ports as in www.host.com and ws.host.com, there is a break.

the config I'm using:

<pre>var _session = app.get('express session');
var _cookies = cookieParser(app.get('cookie secret'));
primus.before('cookies', _cookies);
primus.before('session', _session);</pre>

when I use the same host/port everything is fine:

<pre>User 551ec0ced4a08d spark id ehj28ZnUFCgMIAKtAAAz  connected from x.x.x.x</pre>

request.sesion looks like:

<pre>{ path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  userId: '551ec0ced4a08d',
  flash: {} }</pre>

When I switch to a different host:

<pre>{ path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true } }

[10:50:32.648] [LOG]   Unauthorized access from spark s44Ae_mbYjvBXnoVAAAV at x.x.x.x</pre>

I check for user on connection:
<pre>
primus.on("connection", function(spark) {
  if ( !spark.request.session.userId ) {
        spark.write("Unauthorized Access!");
        spark.end();
}...</pre>

I suspect that I have something configured incorrectly. any suggestions?

**Comment by lpinca** [comment]
Hi,
don't use `express-session` as a primus middleware, it [doesn't work](https://gist.github.com/lpinca/11222004) or at least it didn't.

Check if  the session cookie is set when you use the other domain and see if it gets transmitted to a primus middleware.

Maybe this [example](https://github.com/primus/primus/tree/master/examples/middleware) can help.

**Comment by lpinca** [comment]
@afrozl any update on this?

**Comment by lpinca** [comment]
I close this due to inactivity. Please post back if needed.
