### ISSUE TITLE
auto reconnect on focus

### ISSUE THREAD

**Issue by siddo420** [primus/primus#429]
I have a question about primus auto connect

I have the following config options on browser client
```
var options = {       
  reconnect: { max: Infinity, min: 500, retries: 10 }     
, timeout:   10000 //ms     
, ping:      25000 //ms    
, pong:      10000 //ms     
, manual:    true // manually start connection using .open() rather than on connect     
, transport: {}      , queueSize: Infinity      
};
```

But even though the client is authenticated, connection completely dies after 10 attempts(retries=10) and does not come up again.

I wanted to know if theres a recommended way to deal with this problem ie. when user returns to site again then connection is established automatically for her.

Could this be a FR (if not already taken care of)?

**Comment by lpinca** [comment]
Maybe you can do something like this:
```
window.onfocus = function () {
  if (primus.readyState !== Primus.OPEN && !primus.recovery.reconnecting()) {
    primus.open();
  }
};
```

**Comment by siddo420** [comment]
I already had a similar code but didn't know about "!primus.recovery.reconnecting()".

I'm closing it for now but would be great if similar logic becomes part of the library itself.

**Comment by lpinca** [comment]
The reason for it not being included in core is that normally the connection works fine when the tab is in background, but in some cases the timers are throttled (see #348 #350) and this does not play well with out heartbeat system.

**Comment by siddo420** [comment]
Why are we not checking "(primus.readyState === Primus.CLOSED && !primus.recovery.reconnecting())" in .open() method itself? 

Can you include that in the code please, so we don't have to check it at different places?
