### ISSUE TITLE
separate space for un/authenticated users

### ISSUE THREAD

**Issue by siddo420** [primus/primus#430]
Primus does not support multiple paths rather path (eg. /primus) is hard-coded in client lib and its not a good idea to have multiple libs on client. 

The use-case is that I wanted both authenticated and unauthenticated users to communicate with server thru primus.

Obviously, there will be limitations and checks in place to avoid spam etc. However, I couldn't figure out a way to easily do that.

Please note that atm I have an authentication middleware that discards unauthenticated requests.

I need a way :
- for unauthenticated users to communicate with server (like a temp session etc)
- to securely and efficiently differentiate between both types of requests within primus
- to possibly, allow separate handlers for each type of request

**Comment by lpinca** [comment]
Instead of dropping the connection, in the auth middleware you could check whether the request comes from an authenticated user or not and react accordingly, for example setting `req.authenticated = true`.

**Comment by siddo420** [comment]
Will `.authenticated` be available on spark? If not, how would I access it in my handlers?

```
primus.on( 'connection', function( spark ){
  if( spark.authenitcated )...
});
```
Also, it wont let me identify the individual connection itself. I was thinking of using the `mirage` plugin and include an ID with each request that will be stored on client side (in localstorage etc) and be sent through query string to server. But, I was looking for an easy way to identify authenticated vs unauthenticated.

And, this `req.authenticated` should work if its accessible in handlers as well.

**Comment by lpinca** [comment]
Yes, it is. You can get it like this:
```js
primus.on('connection', (spark) => {
  if (spark.request.authenitcated) {
    // do stuff
  }
});
```

**Comment by lpinca** [comment]
@siddo420 any update here? Can this be closed?

**Comment by siddo420** [comment]
Yes.

Sorry, couldn't keep track of it.
