### ISSUE TITLE
primus.require fails when called from node console or node-webkit

### ISSUE THREAD

**Issue by BrighTide** [primus/primus#434]
**Version: 4.0.5**

**Environment:**
  - **Operating system: Windows 10**
  - **Browser: N/A**
  - **Node.js: 5.3.0**

**Expected result: primus.require finds ws module**

**Actual result: Error: Cannot find module 'ws'**

**Steps to reproduce:

- Have a node module, A with dependency B
- B has 2 dependencies primus, and ws
- A requires and executes B
- B attempts to create a ws socket connection

If A is executed from the node command line (or more realistically, in a execution environment that wraps node, such as node-webkit or electron)  the ws cannot be found, as primus.js is looking in A node_modules, rather than in B's node_modules. If B is executed in this way, things work as expected. If you add ws as a direct dependency of A, the require resolves.
**

**Comment by lpinca** [comment]
@BrighTide can you try to apply this patch https://github.com/3rd-Eden/load/pull/3 and see if it fixes the issue?

**Comment by BrighTide** [comment]
Did the trick, nice one!

**Comment by 3rd-Eden** [comment]
Released a new version of load, so a fresh installation of primus should now also fix this issue.
