### ISSUE TITLE
Android/Java to Primus only sends one byte

### ISSUE THREAD

**Issue by gurpreet-** [primus/primus#437]
I'm developing an Android client for Primus backed by the superb [nv-websocket-client](https://github.com/TakahikoKawasaki/nv-websocket-client) library. I have managed to maintain a stable connection to the server (which is hosted on my local network), however, everytime I send a byte array I only get the first byte as an integer logged on the server.

Here's an example:

#### Android/Java Client
```java
...

WebSocketAdapter websocketAdapter = new WebSocketAdapter() {
        @Override
        public void onConnected(WebSocket websocket, Map<String, List<String>> headers) throws Exception {
            super.onConnected(websocket, headers);
            l("Websocket connected");
            byte[] b = "Hello".getBytes();
            websocket.sendBinary(b);
        }

websocket.addListener(websocketAdapter);

// Setup things, perform connection, etc...
...
```

#### NodeJS Server

```javascript
var Primus = require('primus');
var server_port = 10001;

var binaryServer = Primus.createServer(listener,
    {
        port: server_port,
        transformer: 'websockets',
        parser: 'binary',
        plugin: {
            'my-emitter': require('primus-emit'),
            'rooms': require('primus-rooms')
        }
    }
);

function listener(spark) {
    spark.on('data', function (data) {
        console.log("Got data: " + data);
        // Logs 72 which is 'H' when converted
    });
}
```

The main point of the above is to show that when sending a byte array, the first byte is the only one that's sent from the client, converted into an integer and then logged. The rest of the bytes are seemingly lost. I do not believe that the client code is to blame as I have actually also implemented the client in another library ([async-http-client](https://github.com/AsyncHttpClient/async-http-client)) and even in that implementation the same thing happens but I may be wrong in these deductions.

I would appreciate any pointers. Have I missed something glaringly obvious that I'm doing wrong? Is this even a Primus specific problem or one that is more Java specific? I can provide more code if needed.

**Note:** If I change the `parser` to `JSON`, `websocket.sendBinary("Hello".getBytes())` works.

**Note 2:** `websocket.sendText("anyString")` does not work with any of the two parsers (`JSON`/`binary`) I use.

**Note 3:** Not sure if this is related but whenever I have the `parser` set to `binary` and I send from the server to the client I always get an erroneous byte at the start. For example:

```
// Server
spark.write("Hi from server");

// Client
System.out.println("Binary Message from server: " + new String(binary));
// Binary Message from server: �Hi from server
```

**Note 4:** Removing the plugins has no effect.

**Note 5:** I've trawled the Internet and looked through both Primus' and websockets/ws's issues and have found nothing that is similar to this issue. Also looked through the source code but couldn't find anything odd. Surely I'm missing something.

**Note 6:** I can't use `JSON` as for my use-case I need speed and serialising/deserialising would be too costly.

**Note 7:** I can send byte arrays from the browser (i.e. javascript) to the server and they are fully intact. Therefore I can only assume something happens when the byte array lands for pre-processing on the server side of things.

<hr />
**Primus version:** 4.0.5
**JDK version:** 1.8
**package.json:**
```json
  ...
  "dependencies": {
    "browserify": "^13.0.0",
    "canvas-to-buffer": "^1.0.7",
    "http": "0.0.0",
    "primus": "^4.0.5",
    "primus-emit": "^1.0.0",
    "primus-rooms": "^3.3.0",
    "ws": "^1.0.1"
  }
 ...
```

Great library by the way :+1:

**Comment by lpinca** [comment]
It sounds like an issue with the binary parser.
Try to add a listener for the `incoming::data` event on the spark and see if all the data gets through.
```js
spark.on('incoming::data', raw => console.log(raw));
```

**Comment by gurpreet-** [comment]
I have set the listener as suggested and the binary data from Java comes through perfectly!

I have created a [basic gist](https://gist.github.com/gurpreet-/24b850639dc32e655792) that can replicate this issue (and to help others who are wanting to develop Java + Primus applications). Maven must be installed so that the `pom.xml` file can correctly download the required dependencies for the client.

**Comment by lpinca** [comment]
I guess the binary data is not compatible with [`binary-pack`](https://github.com/primus/binary-pack) and it will fail to [parse](https://github.com/primus/primus/blob/36d758352f19732f2ff65d8e9aa6fc011fab5ee6/parsers/binary.js#L31-L32) it.

**Comment by gurpreet-** [comment]
Okay thank you. I see that indeed `binary-pack`does fail to parse it on the second iteration of `Unpacker.unpack()`.

Is there a way to send data from Java to Primus and make it so that Primus/`binary-pack` does not parse it, just send it on to listening clients?

**Comment by lpinca** [comment]
You can try to use a custom parser:
```js
const parser = {
  encoder: function (data, callback) {}
  decoder: function (data, callback) { }
};

const primus = new Primus(server, { parser });
```

**Comment by gurpreet-** [comment]
Perfect!! It works very well.

Just a note for those Android/Java users wanting to send text/JSON to Primus, the above parser enables you to do so. I've updated the [gist](https://gist.github.com/gurpreet-/24b850639dc32e655792) to help others who travel down this path. Perhaps there's room for a `raw` parser in Primus.

Anyway, thank you :smile:

**Comment by lpinca** [comment]
@gurpreet- can this be closed?

**Comment by gurpreet-** [comment]
Sure. Thanks again.
