### ISSUE TITLE
ping requests from client hitting primus auth layer on server?

### ISSUE THREAD

**Issue by siddo420** [primus/primus#445]
**Version:**
4.0.5
**Environment:**
  - **Operating system:** MacOSX
  - **Browser:** Chrome (incognito mode)
  - **Node.js:** 5.7.1

I just wanted to confirm if ping requests from client always hit the auth layer or not. The reason is, server is hitting DB to confirm client's session etc and it'd be painful for DB to handle such load.

Is it normal? Can this be handled in such a way that client somehow checks the existence of connection w/o hitting auth layer on server (since its an already established connection)? I'll be using a caching layer but still want to know if this can be minimized somehow.

**Comment by lpinca** [comment]
Yes this is intended and cannot be avoided when using polling transports. It doesn't happen when using WebSocket.

**Comment by siddo420** [comment]
thanks
