### ISSUE TITLE
Primus js on sub path (sub uri) on Nginx Proxy Server

### ISSUE THREAD

**Issue by lalitlogical** [primus/primus#446]
**Version:**
3.2.3

**Environment:**
  - **Operating system:** Mac OSX
  - **Browser:** Crome
  - **Node.js:** v0.12.0

**Expected result:**
Primus should be work on sub path of Nginx.

**Actual result:**
It is falling back to localhost.

**Steps to reproduce:**
I want to use Primus with Node JS server behind Nginx at sub path (or sub uri) as real-time. So I have made changes in nginx.conf as below.

```
upstream realtime {
        ip_hash;
        server localhost:1967;
}
```

```
        location /real-time/ {
          proxy_pass http://realtime/;
          proxy_redirect      off;
          proxy_set_header    Host              $host;
          proxy_set_header    X-Real-IP         $remote_addr;
          proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header    X-Forwarded-Proto $scheme;

          # WebSocket specific
          proxy_http_version 1.1;
          proxy_set_header    Upgrade           $http_upgrade;
          proxy_set_header    Connection        "upgrade";

          #
          # Specific for comet or long running HTTP requests, don't buffer up the
          # response from origin servers but send them directly to the client.
          #
          proxy_buffering     off;

          #
          # Bump the timeout's so someting sensible so our connections don't
          # disconnect automatically. We've set it to 12 hours.
          #
          proxy_connect_timeout 43200000;
          proxy_read_timeout    43200000;
          proxy_send_timeout    43200000;
        }
```

Now I am able to get primus.js file at http://localhost/real-time/primus/primus.js. But when I will try make connection as below.

```
primus = Primus.connect("http://localhost/real-time?some_query_string, {
   transformer: 'SockJS'
});
```

It fall back to localhost as below and getting following error.

`GET http://localhost/primus/info?some_query_string&_primuscb=LDur-1u&t=1458021326978 404 (Not Found)`

Without Nginx, It works fine using http://localhost:1967. 
(I am running the node js server on 1967 port.)

How can I properly configure Primus with Nginx? 
Thanks

**Comment by lalitlogical** [comment]
I have also used the pathname options on the server as below.

`var primus = new Primus(server, { transformer: 'SockJS', pathname: 'real-time/primus' });`

But It misses the sub path as below.

`GET http://localhost/real-time/primus/info?some_query_string&_primuscb=LDuxrIA&t=1458022864019 404 (Not Found)`

It should by like below.

`http://localhost/real-time/real-time/primus/info?some_query_string&_primuscb=LDuxrIA&t=1458022864019 `

**Comment by lpinca** [comment]
If you configured the pathname to be `/real-time/primus`, your location location in nginx should be `/real-time/primus/`.

On the client you don't have to specify the pathname and the `transformer` option is only valid on the server.

**Comment by lalitlogical** [comment]
Actually I have tried your suggestion. But then I have to get primus.js file at `http://localhost/realtime/primus/realtime/primus/primus.js`

So I have configured the Nginx conf file as below.

```
location /realtime/primus/ {
          proxy_redirect      off;
          proxy_set_header    Host              $host;
          proxy_set_header    X-Real-IP         $remote_addr;
          proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header    X-Forwarded-Proto $scheme;
          proxy_pass http://127.0.0.1:1967/realtime/primus/;

          # WebSocket specific
          proxy_http_version 1.1;
          proxy_set_header    Upgrade           $http_upgrade;
          proxy_set_header    Connection        "upgrade";

          #
          # Specific for comet or long running HTTP requests, don't buffer up the
          # response from origin servers but send them directly to the client.
          #
          proxy_buffering     off;

          #
          # Bump the timeout's so someting sensible so our connections don't
          # disconnect automatically. We've set it to 12 hours.
          #
          proxy_connect_timeout 43200000;
          proxy_read_timeout    43200000;
          proxy_send_timeout    43200000;
        }
```

Now everything working fine. Thanks for reply.
Let me know if we can refine the Nginx configuration.

**Comment by lpinca** [comment]
I'm not sure why you need to repeat the pathname like this:
```
proxy_pass http://127.0.0.1:1967/realtime/primus/
```
If you configured the pathname to be `/realtime/primus`, the following should work:
```
proxy_pass http://127.0.0.1:1967
```

**Comment by lalitlogical** [comment]
No, It is not working becuase We need to server all request from Nginx sub path. So When browser make request to `/realtime/primus/` it will not goes to node js server. So we need to add sub path `/realtime/primus/` which we define in Nginx Conf file.

So It will make as `/realtime/primus/realtime/primus/`.
One `/realtime/primus/` is Nginx sub path and another `/realtime/primus/` will your primus pathname where we intract with primus.

So removing one `/realtime/primus/` from url I have modified the `proxy_pass` as above.

**Comment by lpinca** [comment]
@lalitlogical I close this. Please post back if needed.

**Comment by mauron85** [comment]
I think pathname should be also configurable from client.
The reason for it is following. Imagine nginx as reverse proxy with following configuration:

```
upstream ws_upstream {
  server ws:8882;
}

server {
  listen *:80 default_server;

  location /ws/ {
    proxy_pass  http://ws_upstream/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```
So basically nginx will proxy any request from:
http://myserver.com/ws -> http://localhost:4444

But if client wants to connect it will initiate connection to url:

http://myserver.com/connection not http://myserver.com/ws/connection (/ws part is stripped by nginx intentionally), which will obviously fail with 404.

Quote from nginx
>If the proxy_pass directive is specified with a URI, then when a request is passed to the server, the part of a normalized request URI matching the location is replaced by a URI specified in the directive:
location /name/ {
    proxy_pass http://127.0.0.1/remote/;
}
