### ISSUE TITLE
Is there a way to call `off` on the spark object or something similar?

### ISSUE THREAD

**Issue by ekryski** [primus/primus#449]

**Comment by lpinca** [comment]
This a bit vague, what do you mean?
`Spark` inherits from `EventEmitter` so you have almost all the methods of the Node.js [`EventEmitter`](https://nodejs.org/api/events.html).
I say almost because we actually use [`eventemitter3`](https://github.com/primus/eventemitter3). In `eventemitter3`, `off` is an alias for `removeListener`.

**Comment by joshuajabbour** [comment]
So, I'm not entirely clear yet on how Primus is architected, but I can't seem to find the `off` method on the EventEmitter:

```
EventEmitter {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined }
```
```
domain
_events
_eventsCount
_maxListeners
setMaxListeners
getMaxListeners
emit
addListener
on
once
removeListener
removeAllListeners
listeners
listenerCount
```

Maybe this isn't an issue with Spark, but tests are failing in Feathers because there is no `off` method (though there is a `removeListener` method).

**Comment by ekryski** [comment]
@lpinca Yes sorry, I have been pretty busy and forgot to follow up here. I'll have to check and see which event emitter we are using in Feathers, and which version of Primus we are using (I'm pretty sure the latest) but I wasn't able to find the `off` method on the Spark object either.

I'll have to dig a bit deeper but I guess we could always just call `removeEventListener` explicitly @joshuajabbour.

**Comment by lpinca** [comment]
Wooops my bad, `Spark` inherits from [`Stream`](https://github.com/primus/primus/blob/1a7d1437f6a3534472b4f9776c7e66e2d7650f62/spark.js#L63) so there is no `off` method.

**Comment by ekryski** [comment]
@lpinca ahhh ok. That makes a lot of sense then. ok so we just need to call `removeListener` or create our own `off` alias inside feathers that calls that. Thanks!
