### ISSUE TITLE
Sticky sessions not working when using Primus.createSocket - using engine.io transfomer

### ISSUE THREAD

**Issue by necccc** [primus/primus#452]
**Version:** 5.0.1

**Server Environment:**
  - **Operating system:** Debian wheezy
  - **Browser:** no
  - **Node.js:** 4.2.2
  - **Transformer:** engine.io 1.6.8

**Client Environment:**
  - **Operating system:** OSX 10.10.5
  - **Browser:** no
  - **Node.js:** 4.2.2
  - **Transformer:** engine.io 1.6.8
 
**Expected result:** when using the primus client from node ( via Primus.createSocket ) it should handle sticky sessions over haproxy loadbalancer the same way as the browser client

**Actual result:** If I run two instances of primus on a remote server (lets say on port 1112 and 1113), behind a haproxy,  the browser client connects to the instance, where the haproxy directs it, (lets say it connects to 1112) and it stays there, the sticky session is working

If I do the same from node, using Primus.createSocket, I can see the connection starts on one instance ( on port 1112) then the second or third, or *nth* packet hits the **other** instance ( on port 1113) and the client receives an error:

```
[Error: xhr poll error] type: 'TransportError', description: 400
```

This cannot be reproduced using the "websockets" transformer, so I'm unsure if it's directly engine.io related.

**Steps to reproduce:** run two instances, with engine.io behind a haproxy, and try to connect them from node using Primus.createSocket

**Comment by necccc** [comment]
Managed to get the haproxy config we use in this case:

```
        mode http
        timeout server 30s
        timeout tunnel 600s
        option http-keep-alive
        option httpchk HEAD /status HTTP/1.1\r\nHost:\ primus-test.myhost.com\r\nUser-Agent:\ haproxy
        balance leastconn
        cookie PROXYID insert indirect nocache maxidle 1h maxlife 2h
        rspirep ^Server:\ (.*) Server:\ test/primus
        option forwardfor
        bind-process 5

        server primus-node-port-1112 192.168.0.10:1112 maxconn 10000 weight 50 check inter 5s fall 1 rise 2 slowstart 15s cookie s-test-1112
        server primus-node-port-1113 192.168.0.10:1113 maxconn 10000 weight 50 check inter 5s fall 1 rise 2 slowstart 15s cookie s-test-1113
```

**Comment by lpinca** [comment]
I wonder if this is an issue with how the sticky session is handled by haproxy. Does it use cookies?

**Comment by necccc** [comment]
Yes, it does it with cookies.

Meanwhile, I've checked the http requests in/out from the client. The incoming responses all come with the `Set-Cookie` header, telling the client about the `s-test-1112` and `s-test-1113` cookies, but there isn't a single outgoing request with these Cookies set. 

This issue works fine in the browser - but there the browser handles the Set-Cookie, I presume.

**Comment by lpinca** [comment]
Yeah, cookies are not saved when using the node client.

**Comment by necccc** [comment]
Is there any way around? Or should I monkeypatch http and handle the cookies?

**Comment by lpinca** [comment]
I think you can configure Haproxy to do session affinity without a cookie but I'm not sure if it is suitable for your use case.

**Comment by lpinca** [comment]
For example [`balance source`](https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-balance) may be an option but I guess it isn't very usefult because many client can share the same IP.

**Comment by lpinca** [comment]
@necccc did you find a workaround?

**Comment by necccc** [comment]
Yes, but would not say it's a nice or solid solution, but my usecase is a headless test tool for primus that emulate clients, so it's not mission-critical.

I wrapped the core node http module with shimmer so it would: 
- watch the set-cookie header in responses, and store them for the client session
- put these cookies to every outgoing request

**Comment by lpinca** [comment]
Ok, thanks for the update. I close this, please post back if needed.

**Comment by necccc** [comment]
I've put my workaround in a module if anyone needs it in the future

https://github.com/necccc/primus-headless-cookie
