### ISSUE TITLE
Replace lws with uws

### ISSUE THREAD

**Issue by alexhultman** [primus/primus#453]
Hi.

I'm looking at deprecating the lws module very soon. The uws module is 10x more lightweight and about 3x faster. Also, it behaves a lot more graceful than lws. I've talked with @lpinca.

I'm currently doing work to pass the integration tests and will then publish the module.

**Comment by lpinca** [comment]
I think we should release a new minor version where `uws` is added and `lws` is deprecated, then in the next major version we will get rid of `lws`.

Another option is to make `lws` an alias for `uws`.

**Comment by alexhultman** [comment]
Alias would do IMO. They target the same audience and have about the same properties.

**Comment by alexhultman** [comment]
All tests pass now. And since uws is imitating the ws interface all you need to do is to replace require('ws') with require('uws') in the transformer. But I need to clean things up and actually publish the module first. Maybe we could look at this tomorrow, or maybe later today?

**Comment by lpinca** [comment]
Does `uws` supports permessage deflate?
We should also find a way to create the alias, we don't have such feature at the moment.

**Comment by lpinca** [comment]
Hmm I guess the alias is not an option as the user also have to install the new module (`uws`).

**Comment by alexhultman** [comment]
SSL and permessage-deflate are missing right now. But you get graceful close at least :P

**Comment by alexhultman** [comment]
We can have the lws module up on npm, its no problem. But maybe mark it as deprecated (yes I have massive amounts of ADD :P). I'm not looking at doing anything with it anymore.

**Comment by lpinca** [comment]
I think it will just create confusion. I think it's better to have both `lws` and `uws` in `primus@5.1.0` and mark `lws` as deprecated both in npm and Primus.

**Comment by lpinca** [comment]
Closing as per #454.
