### ISSUE TITLE
In browserified client: TypeError: Cannot set property 'Primus' of undefined

### ISSUE THREAD

**Issue by marcelklehr** [primus/primus#456]
**Version:**5.1.0

**Environment:**
  - **Operating system:**Ubuntu 15.10
  - **Browser:** Chromium 49.0.2623.108
  - **Node.js:**5.6.0

**Expected result:**Page loads and Primus loads.

**Actual result:**Page and Primus don't load.

**Steps to reproduce:**
Add the output of primus.library() to a browserify bundle either as an entry file or as a dependency of some other js file. Load the bundle in your browser.

**Comment by lpinca** [comment]
Hi @marcelklehr,
I've just tried with a super simple test case. This is browserify entry file:
```js
'use strict';

var Primus = require('./primus');

var primus = new Primus();
```

where `primus.js` is a file containing the result of `primus.library()`. Then I created a bundle for the browser:

```
browserify entry.js > bundle.js
```

It works here.

Here is the server code:
```js
'use strict';

var Primus = require('primus')
  , http = require('http')
  , fs = require('fs')
  , primus
  , server;

server = http.createServer(function (req, res) {
  if (req.url === '/bundle.js') {
    res.setHeader('Content-Type', 'application/javascript');
    fs.createReadStream(__dirname + '/bundle.js').pipe(res);
    return;
  }
  res.setHeader('Content-Type', 'text/html');
  fs.createReadStream(__dirname + '/index.html').pipe(res);
});

primus = new Primus(server);
primus.save(__dirname + '/primus.js');

primus.on('connection', function (spark) {
  console.log(spark.id + ' connected');
});

server.listen(3000, function () {
  console.log('listening on port 3000');
});
```

**Comment by marcelklehr** [comment]
This seems to be a duplicate of #444
