### ISSUE TITLE
Client Library Dynamic Reconnect / Recovery Strategy Enabling

### ISSUE THREAD

**Issue by l0gicgate** [primus/primus#458]
### Preface
I went through the docs up and down to try and find a way to change the reconnection strategy on the fly and couldn't find a way to do it so I had to modify the client side library.

I can't create a pull request for this as the client side library isn't available on the git since it's dynamically generated.

### The Issue
On my application, I handle the logging in of the user using a socket. I do not want to have the socket try and reconnect if it encounters an error during the login process (such as a protocol error, etc.).

However, after I'm passed the login, I want to enable the reconnect strategy to have a persistent connection to my server. Primus does not seem to offer that at the moment (if there are reasons as to why it doesn't, please enlighten me). 

### The Solution
I did not want to have to handle the reconnection logic by hand. So I had to modify the source code:
[Click here to view the commit from my project](https://github.com/lgse/react-chat/commit/95a6c6a630dab42710a87d5552c17a204497dd28)

I essentially decoupled the event attaching from the constructor and separated it in a different function so I can attach the events dynamically and also created a function that would set the recovery options on the fly.

Hope this is a relevant issue to others.

**Comment by lpinca** [comment]
> I can't create a pull request for this as the client side library isn't available on the git since it's dynamically generated.

The client side lib is in `primus.js` under this repo.

> However, after I'm passed the login, I want to enable the reconnect strategy to have a persistent connection to my server. Primus does not seem to offer that at the moment (if there are reasons as to why it doesn't, please enlighten me). 

If you handle the login via Primus you already have a "persistent" connection (it actually depends on the transformer) so if the connection goes down why shouldn't Primus try to reconnect?

Also wouldn't you need to do everything again (disable reconnection / enable reconnection) If your connection gets interrupted after a successful login? Primus uses a new connection every time it tries to reconnect.

**Comment by l0gicgate** [comment]
The socket gets initialised with the login action as there is a server field for users input. If there are errors with the server name, or if it can't connect to the server for whatever reason, I don't want it to persist. 

There needs to be no reconmection strategy prior to the login/connection to the server. Once past that point, that's when I want to enable it.

**Comment by lpinca** [comment]
You can probably start with `strategy: false` and then change it:

```js
const primus = new Primus({ strategy: false });

primus.on('open', () => primus.options.strategy = 'disconnect,online');
```

**Comment by l0gicgate** [comment]
No, you cannot. Because as you can see in the initialise() function the event handlers on the Recovery object get attached there. Hence why I had to decouple that code from the initialise function so it can be called manually after. I'll do a pull request today.

**Comment by lpinca** [comment]
What's the problem with having the handlers attached if reconnection is never started?
The event handlers are attached also when reconnection is disabled (`strategy: false`).

**Comment by l0gicgate** [comment]
Because you cannot provide a new Recovery object to the instance. Which gets passed all of the options when you instantiate a new Primus() object. 

If you want to enable it on the fly, you need to create a new Recovery object with the options that you would pass to A new Primus() object.

**Comment by lpinca** [comment]
Sorry but I don't get it, you can pass all your reconnect options when creating the primus instance.

```js
const primus = new Primus({
  reconnect: {
    max: 10000,
    min: 100
  },
  strategy: false
});
```

**Comment by l0gicgate** [comment]
@lpinca I apologize, I clearly didn't read the source correctly. Your solution works for changing the strategy on the fly.

Regards.

**Comment by lpinca** [comment]
@l0gicgate no problem.
It's an hack as it messes with primus internals. We should add a proper way to change the strategies if we want to support this, but can work as workaround for now.

**Comment by l0gicgate** [comment]
Yes absolutely, ultimately an options Object could be dynamically regenerated on the fly.. with a `setOptions()` function perhaps. Changing properties on instantiated object is definitely not a clean solution but it does work for now.

**Comment by 3rd-Eden** [comment]
Options should **not** be changed or dynamically changed. There are simply things that cannot be dynamically changed in that object. Having an API to control reconnect behaviour, I see no reason why not.
