### ISSUE TITLE
Can't use uws with createSocket

### ISSUE THREAD

**Issue by porsager** [primus/primus#466]
**Version:**
5.2.1

**Environment:**
  - **Node.js:**

**Expected result:**
Use the uws library as transformer

**Actual result:**
An error is thrown saying:
Missing required `ws` module. Please run `npm install --save ws`

**Steps to reproduce:**
Primus.createSocket({ transformer: 'uws' })(url)

**Comment by porsager** [comment]
I just realized is probably because uws is only a websocket server and not a client?

**Comment by lpinca** [comment]
@porsager correct.
