### ISSUE TITLE
authorize fails - body not sent to client

### ISSUE THREAD

**Issue by ddennis** [primus/primus#471]
I have tried asking on IRC

**Version:** 5.2.2

**Environment:**
  - **Operating system**: Windows 8.1
  - **browser**: Chrome
  - **Nodejs**: 5.4.0
  - **Transformer**: WS

**Expected result:** 
I have implemented the ***outgoing::open*** and are handling the  ***unexpected-response*** on the server. i am using the WS transformer and the README states, that i should be able to get the error message on the client, when my authorize function fails. My authorization fails because my jwt token has expired. 

**Actual result:**
On the client I am not getting any thing usefull in my error handler.I would expect my primus.on('error', fn) was called with 'authorization failed: ' + res.statusCode

Error thrown in the browser:
WebSocket connection to 'ws://localhost:8080/primus?token=...&_primuscb=LLPfD-7' failed: Error during WebSocket handshake: Unexpected response code: 403

**Steps to reproduce:**
I have forked the repo and tried implementing outgoing::open here:
https://github.com/ddennis/primus/blob/master/examples/authorization/index.js#L41

Since the browser still throws an error i assume  i am not handling the "unexpected-response" correctly.

**Comment by lpinca** [comment]
The `unexpected-response` event is a feature of `ws` and is therefore only emitted if you are using the Node.js client. The browser uses its own WebSocket implementation, not `ws`.

**Comment by ddennis** [comment]
Thanks - conclusion from ReadMe : ***err won't contain any details about the authorization failure so you won't be able to distinguish it from other errors.*** when running in the browser. Correct?

I guess i need to handle the token validation before trying to connect. Any tips on other way to handle this?

/Dennis

**Comment by lpinca** [comment]
@ddennis if you can reliably get the status code in the error message you can use a custom status code on the auth hook:
```js
primus.authorize(function (req, done) {
  var err = new Error('foo');
  err.statusCode = 400;
  done(err);
})
```
This will use that status code for the HTTP response.

If this is not an option you can use an async listener for the `connection` event:

```js
primus.on('connection' function (spark, next) {
  //
  // Validate the token here and call `next` with an error accordingly.
  // If an error is passed to the `next` the connection will be closed.
  // You should also be able to send data to the client here.
  //
});

primus.on('connection', function (spark) {
  //
  // This is the usual connection handler.
  // It will be called only if the previous handler called `next` with a `falsy` error argument.
  //
});
```

**Comment by ddennis** [comment]
Thanks - I moved my token validation to away from ptimus, so it's refreshed before trying to connect.
