### ISSUE TITLE
Accept multiple transformers as an option

### ISSUE THREAD

**Issue by kripod** [primus/primus#473]
The `transformer` option could be an array, for example: `transformer: ['uws', 'websockets']`.

In the aforementioned example, Primus should try to load the `uws` transformer at first, but if that fails (most probably because of using Windows as a runtime platform), the second option could be used as a fallback.

**Comment by lpinca** [comment]
-1 from me as discussed on IRC.

**Comment by kripod** [comment]
Great, thanks for the quick reply, the solution should be useful.
