### ISSUE TITLE
Give the option to efficiently send binary data to and from the server

### ISSUE THREAD

**Issue by githubaccount624** [primus/primus#479]
I'm writing a game. I'm looking for a way to send types like `Int16Array` to the server and handle them as a `Buffer` on the server. Reasons:

1) The `binary` parser is four years old and spikes CPU usage to 100% and sometimes crashes the server when used. It's basically unusable if sending slightly large packets (arrays with 1000 elements, for example).

2) The server doesn't have to parse the data (either via binary-unpack or JSON.parse) and then re-encode (via binary-pack or JSON.stringify). Thus it can simply relay the packet extremely quickly.

3) Bandwidth efficiency: Instead of sending strings of numeric characters and commas, which quickly adds up for large arrays, we can simply send the packed numbers.

4) Slightly more secure because the packets cannot be viewed in browser developer consoles (can still be viewed in proxy monitoring applications like Burp suite but requires much more effort)

5) All underlying libraries that primus uses support it. Even [socket.io](http://socket.io/blog/introducing-socket-io-1-0/#binary) does. Native websockets in the browser does by setting `connection.binaryType = "arraybuffer";` We should be able to send binary data without it being stringified and parsed.

6) Browsers support it with typed arrays and node supports it with the Buffer.

7) People need this because browsers are becoming more powerful and websockets are increasingly being used for games/videos where efficiency is paramount.

8) In Primus data already arrives as a Buffer. I just want to keep it that way with no parsing.

I think the `ejson` parser supports it but I don't know what kind of overhead that has and it seems odd to still be using a `json` parser to be sending pure binary. Also I can't seem to find much information about `ejson` and either way, it's weird to be using a parser that's thousands of lines of code wherein all I really need is no parser at all.

**Comment by lpinca** [comment]
As discussed on IRC I suggest you to use a custom parser:
```js
const parser = {
  encoder: function encoder(data, fn) { fn(undefined, data); },
  decoder: function decoder(data, fn) { fn(undefined, data); }
};

const primus = new Primus(server, { parser });
```

and play with [`DataView`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView) on the client.
