### ISSUE TITLE
Remake the uws transformer

### ISSUE THREAD

**Issue by alexhultman** [primus/primus#480]
I'm thinking it would be best to replace the current mess that is the uws transformer and just stick to using the official ws interface. This way we won't get mismatching versions when I change the internal interface or add features or in other ways tweak the library.

The current upgradeReq object is broken and holds invalid socket data that should really be destroyed, this is not the case with the ws interface as I strip out what is broken and replace it with getters, etc.

I just added Windows support which also changes the interface a bit. Primus needs to work with a wide range of uws versions and this is not the case currently.

We could do some measurements in memory usage if that's interesting.

**Comment by lpinca** [comment]
> The current upgradeReq object is broken and holds invalid socket data that should really be destroyed, this is not the case with the ws interface as I strip out what is broken and replace it with getters, etc.

Can you please point where in the code? 

I don't want to use another wrapper, Primus is already a wrapper. The ws interface in uws is just useless bloat for us.

> Primus needs to work with a wide range of uws versions and this is not the case currently.

I know you only care about the ws interface for the Node.js part, but if you are making breaking changes to the addon interface you should public major versions because the addon is also public.

**Comment by alexhultman** [comment]
Sure I could use a more strict versioning but that still wouldn't fix the problem since there is really no version specified in primus. Users use the latest version of primus and the latest version of uws and this doesn't work at all currently.

Npm install primus
Npm install uws

This installs the latest version of both which result in a broken set up.

**Comment by lpinca** [comment]
We do the same for almost all transformers, and we always target the latest version.
You are right, right now the latest uws does not work with the latest primus but that's because we are about to release a major version and that has slowed us down a bit.
We can release primus@5.2.3 to add support for the latest uws but primus@6.0.0 should come out soon and hopefully we won't have a new major for a while.

**Comment by alexhultman** [comment]
So the upgradeReq needs to be stripped of various invalid things. Most importantly and most significant is all references of the net.Socket. That object is destroyed but cannot be collected since the upgradeReq refers to it multiple times. In uws I just strip away everything except for some common things, tou can see these in uws.js. When the socket gets removed you need to add getters for some common properties like remoteAddress and the like.

**Comment by lpinca** [comment]
We need full access to the `req` object as we use a middleware system where users can attach custom properties to it. What kind of impact those references to destroyed sockets have?

**Comment by alexhultman** [comment]
They are broken (destroyed) and are a humongous memory burden. If you remove them you get easily 5-10x better memory scaling.

**Comment by alexhultman** [comment]
knowing what to remove from the upgradeReq is kind of a guessing game. Thats why I just removed everything and added things on request from users. Now I have only a few things in that object and users are not complaining. It just works. That's also one readon to use the ws interface - we get better compatibility and I can remove unused things and add getters for used things. My guarantee is to provide a ws interface and do it as efficiently as I can so you dont need to tweak what you include and what you dont include. I have a faster development cycle than primus and can update the lib very fast on request.

**Comment by alexhultman** [comment]
One complex example is how my upgradeReq holds references to a getter function instead of the net.Socket. That is something very internal and not something primus should have to deal with. The ws interface is not only "a wrapper" but rather an extension of the addon that completes it as one supported module.

**Comment by lpinca** [comment]
> Thats why I just removed everything and added things on request from users.

That is another reason for us to not use the ws interface uws ships with.

Apart those "destroyed" `net.Socket` references there is nothing we should remove from the `req` object. This is consistent with the other transformers.

**Comment by lpinca** [comment]
`primus@6.0.0` has been released and it should work with the latest version of `uws`.
I'll see if we can do something about the destroyed sockets.
