### ISSUE TITLE
Primus in V8

### ISSUE THREAD

**Issue by ImmanuelSamuel** [primus/primus#482]
Hey guys I am trying to run Primus in V8 and I get the following error.
```
Error: Error: Missing required `ws` module. Please run `npm install --save ws`
Error:     at EventEmitter.client (c:\test\scripts\node_modules\Primus.js:3052:40)
```
Is this similar to #464. Any fixes? Any way to bundle everything in a single file?

**Comment by lpinca** [comment]
You can probably tell browserify or webpack to include the dep as an external dependency.

**Comment by lpinca** [comment]
I close this issue, please post back if needed.
