### ISSUE TITLE
Primus and angular 2

### ISSUE THREAD

**Issue by jaumard** [primus/primus#483]
**Version:**
4.0.4 

**Environment:**
  - **Operating system:All**
  - **Browser:All**
  - **Node.js:4**

**Expected result:**
 Having the possibility to use Primus with typescript for front purpose

**Actual result:**
 IDE and compiler keep telling `Primus is not defined`. 
If I use the `.d.ts` it's not working because the definition is for the server part when I need the client definition.

**Steps to reproduce:**
```js
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app',
  providers: [],
  directives: [],
  styleUrls: [],
  template: ''
})
export class AppComponent implements OnInit {
  ngOnInit() {
    this.initWebsockets();
  }

  private initWebsockets() {
    //
    // Tell primus to create a new connect to the current domain/port/protocol
    //
    const primus = new Primus('http://localhost:3000?token=....');

    //
    // Listen for incoming data and log it in our textarea.
    //
    primus.on('data', function received(data) {
      switch (data.action) {
        case 'create':
          console.log('create');
          break;
        case 'update':
          console.log('update');
          break;
        case 'destroy':
          console.log('destroy');
          break;
        case 'notification':
          console.log('notification');
          break;
      }
      console.log(data);
    });
    //
    // Listen for submits of the form so we can send the message to the server.
    //
    primus.write({action:'join', room:'notification'});
  }
}

```

**Comment by lpinca** [comment]
I'm a noob with both angular 2 and typescript so I can't be of help here.
If updating the definition can help feel free to do so and send a pr.

**Comment by jaumard** [comment]
Ha ha I'm a noob with primus angular 2 and typescript lol I was hoping someone will be able to help ^^ 
I think yes definition should be updated but don't know in witch way for working in both side... If I found something I'll let you know 
Thanks!

**Comment by lpinca** [comment]
Unrelated, but looking at the above code, you can probably remove the switch case in favor of `primus-emit` or `primus-emitter`.

**Comment by stormwin** [comment]
Get latest version of primus

In config.js where System.config is defined, put this:

 meta: {
    "primus": {
      "scriptLoad": true,
      "format": "amd",
      "exports": "primus",
      "build": false
    }
  }

and in map object put this:

"primus": "http://localhost:3000/primus/primus.js",

in angular:

import * as Primus from 'primus';
const primus = Primus.connect();

**Comment by jaumard** [comment]
@lpinca thanks ! I replace it by primus-emitter because I use primus-rooms ! :)
@stormwin I'll test this thanks a lot ! I'll let you know how it works.

**Comment by jaumard** [comment]
@stormwin I works great !!! Thanks a lot ! :) closing this as I don't have any problem.

**Comment by justinweathersby** [comment]
Does anyone have a working Plunker or example? @stormwin I dont have a config.js in my Angular 7 project. Or more than likely im just misunderstanding how you added that.

**Comment by stormwin** [comment]
@justinweathersby 3 years after my last comment and solution.... uhhh... lot of things have changed in Angular world since then.
Luckily for you, i am still using Angular + Primus and i have new method how to implement and use it in Angular 7.
First of all, save client library in some folder of your Angular 7 project. (you can extract it from backend side or start the backend server and get it by url, check the docs)
Then you can use it like
import * as Primus from 'place_to_the_file/primus.js';
Somewhere in your code do this for example:
this.primusInstance = Primus.connect(url); // Url is url to your site like 'ws://examplesite.abc';
use primusInstance for data handling, receiving, sending data....
