### ISSUE TITLE
Spark Queue doesn't get nulled

### ISSUE THREAD

**Issue by DerTieran** [primus/primus#488]
**Version:** 6.0.1

**Environment:**
  - **Operating system:** Windows 7
  - **Browser:** Chrome Version 51.0.2704.103 m
  - **Node.js:** 4.4.7

**Expected result:**
[`Spark transforms`](https://github.com/primus/primus/blob/master/spark.js#L327) => [`Emit Data`](https://github.com/primus/primus/blob/master/spark.js#L378)

**Actual result:**
[`Spark transforms`](https://github.com/primus/primus/blob/master/spark.js#L327) => [`Push to Queue`](https://github.com/primus/primus/blob/master/spark.js#L377)

I could trace it back to [`damn(err)`](https://github.com/primus/primus/blob/master/spark.js#L298) never getting called, because is never returned by [asyncemit here](https://github.com/primus/asyncemit/blob/master/index.js#L47) .
This happens beaucse [`done(err)`](https://github.com/primus/asyncemit/blob/master/index.js#L65) doesn't get called.
If I replace [Line 55-70](https://github.com/primus/asyncemit/blob/master/index.js#L55-L70) with just
```js
listener.fn.apply(listener.context, args);
return each(stack);
```
I get the expected result, but I think this isn't as intended.

**Note:**
I wanted to upgrade primus from 3.x to 6.x when I update it to 4.0.0 it works after that it I run into this problem.

**Comment by lpinca** [comment]
Thanks for the detailed report, I'm not sure why the `asyncemit` callback does not get called.
Are you able to create a minimal test case to reproduce the issue?

**Comment by DerTieran** [comment]
I will try. Do you think this could happen because of the way we use primus in our project or anything else?

**Comment by lpinca** [comment]
I wonder if you have an async listener for the `connection` event and somehow you are not calling the callback of that listener.

**Comment by lpinca** [comment]
If 4.0.0 works and 4.0.1doesn't work the issue has been probably introduced here https://github.com/primus/primus/pull/406 but nothing catches my attention in that pr.

**Comment by DerTieran** [comment]
I could not reproduce it on my system at home. I will try it tomorrow at work again.
But we use primus something like this:
```js
var _ = require('lodash');

function StrucdSocketConnection(spark) {
    this.spark = spark;
};

StrucdSocketConnection.prototype.emitError = function(err) {
    var errormsg = {
        messagetype: 'error',
        statusCode: err.statusCode || 500,
        error: err.message
    };

    this.spark.write(errormsg);
};

function StrucdPrimus(server) {
    this.primus = new Primus(server, { 
        transformer: 'websockets'
    });

    // Primus plugins & middleware here

    this.primus.on('connection', this.handleNewConnection.bind(this));
}

StrucdPrimus.prototype.handleNewConnection = function(spark, next) {
    if(_.isUndefined(spark) || _.isNull(spark)) {
        return next(new Error());
    }
    
    var strucdSpark = new StrucdSocketConnection(spark);

    strucdSpark.spark.on('data', function(message) {
        if(_.isUndefined(message.messagetype) || _.isNull(message.messagetype)) {
            //log Error
            return;
        }

        switch(message.messagetype) {
            // type handling here
            default:
                strucdSpark.emitError(new Error());
                return;
                break;
        }
    });
};
```
I don't know if this is helpful.
If I can't create a failing test case are there any useful logs I could provide?

**Comment by lpinca** [comment]
Not sure if you forgot it but in `StrucdPrimus.prototype.handleNewConnection` you should always call `next` not only when an error occurs (the `spark` here cannot be `undefined` or `null`).
If you don't call `next` the issue you posted occurs as the asyncemit [callback](https://github.com/primus/primus/blob/0cab38296fed5c655cd46d350648fbbc7077b22a/spark.js#L298) is not fired exactly how you described above.

**Comment by lpinca** [comment]
To clarify, your `StrucdPrimus.prototype.handleNewConnection` should look like this:

```js
StrucdPrimus.prototype.handleNewConnection = function(spark, next) {
  if(_.isUndefined(spark) || _.isNull(spark)) {
    return next(new Error());
  }

  var strucdSpark = new StrucdSocketConnection(spark);

  strucdSpark.spark.on('data', function(message) { /* do stuff */ });

  next(); // This is required
};
```

or like this:

```js
StrucdPrimus.prototype.handleNewConnection = function(spark) {
  var strucdSpark = new StrucdSocketConnection(spark);

  strucdSpark.spark.on('data', function(message) { /* do stuff */ });
};
```

which is better as the check on the spark is redundant.

**Comment by DerTieran** [comment]
Okay I will try this solution. I'm not really sure why there is another check this code was written by someone else awhile ago and I'm just trying to update the version and ran into this. Thanks in advance for your help.

**Comment by DerTieran** [comment]
Okay this solved the problem. Sorry for not reading you documentation properly.
I didn't thought about having buggy exciting code already, because it worked before.
Thanks so much for your time and help, much appreciated!

**Comment by lpinca** [comment]
Closing this, please post back if needed.
