### ISSUE TITLE
ws required when using uws

### ISSUE THREAD

**Issue by sabrehagen** [primus/primus#489]
I'm being asked to install `ws` as a dependency when using the `uws` transformer. Why is this? At no point in my code do I use the `websockets` transformer.

**Version:**
6.0.2

**Environment:**
  - **Operating system:**
  Alpine Linux 3.4
  - **Browser:**
  N/A
  - **Node.js:**
  v6.5.0

**Expected result:**
  No Error

**Actual result:**
  `Error: Missing required 'ws' module. Please run 'npm install --save ws'`

**Steps to reproduce:**
```
const Socket = Primus.createSocket({ transformer : 'uws' });
const socket = new Socket(`${host}:${port}`);
```
Gets error:

```
primus.js:3027
  throw err;
  ^

Error: Missing required `ws` module. Please run `npm install --save ws`
    at Primus.client (primus.js:3069:40)
    at Primus.initialise (primus.js:2419:10)
    at new Primus (primus.js:2051:10)
    at module.exports (userland code)
```

**Comment by lpinca** [comment]
`uws` does not work as WebSocket client, it is only a server so we need a WebSocket client to talk with it from Node.js, that client is `ws`.

**Comment by sabrehagen** [comment]
Thank you, sorry I missed it in your docs.
