### ISSUE TITLE
Not really an issue, just a query

### ISSUE THREAD

**Issue by c0debreaker** [primus/primus#490]
Hi,

What are your thoughts on 500 user live connections to a server running Primus? The primus might be serving a json with 3k or 18k bytes size. However, the big json data like the 18kbytes+ doesn't change a lot. The once that gets polled often are the json with size of 3-5k bytes, maybe it changes every 30seconds or 1 minute.

Do you think polling is better?

If you say use primus, why would you recommend it?

Btw, I've used primus in my Angular app 2 years ago from my previous job and love it. We only have less than 50 users.

Thanks!

**Comment by lpinca** [comment]
These questions are hard to answer without knowing the details.
It depends on many things like:

- If you want to keep the latency as small as possible.
- If your communication needs to be bidirectional or not.
- etc.

You should test both approaches and choose the one that suits you better.

**Comment by c0debreaker** [comment]
Thanks! I should try both.
