### ISSUE TITLE
Update README.md regarding Express 4

### ISSUE THREAD

**Issue by sabrehagen** [primus/primus#494]
Your docs state [Express 3's express() instance isn't a valid HTTP server.](https://github.com/primus/primus#how-do-i-use-primus-with-express-3)

Given that Express 3 is long out of date and most people use Express 4, is Express 4's `express()` instance a valid HTTP server?

**Comment by lpinca** [comment]
That section talks about express 3 but it is also valid for express 4, same stuff.
We should update it with something like express 3/4, PR's are welcome!

**Comment by sabrehagen** [comment]
I'm more than happy to do the edit grunt work, but I will have to trust that interoperability with express is still as per the docs - I'm no expert, just an edit monkey!

**Comment by lpinca** [comment]
The code example is also valid for express 4, so no changes are needed there.

**Comment by lpinca** [comment]
Fixed by #496, closing.
