### ISSUE TITLE
uws 0.10.x

### ISSUE THREAD

**Issue by lpinca** [primus/primus#498]
I've updated the uws transformer in #497 to make it work with `uws@0.10.x` but tests fail as the current version of uws ignores the `maxPayload` option which sets the maximum allowed size of a packet.

I've tried to report the issue but @alexhultman banned me everywhere so if you care about uws support please report the issue in the uws [repo](https://github.com/uWebSockets/uWebSockets).

**Comment by lpinca** [comment]
Since I can't answer on the https://github.com/uWebSockets/uWebSockets/issues/275 I want readers know why things are done the way they are in Primus.

> lot of overhead by copying buffers that are supposed to be zero-copy

In most cases the dev has to copy those buffer anyway. For example imagine a user sending an image. If buffers are zero copy each chunk of data has to be copied as it is only valid in its callback, so why doing this every time for every app you write when it can be done by the lib?
On top of this Primus has a streaming interface which makes working with zero copy buffers hard.

> they add full versions of EventEmitter

If you are using Node.js and you think that the EventEmitter is wrong you should start looking somewhere else as basically everything in Node.js is built on top of the EventEmitter.

> other stuff they call "the Spark"

The `spark` is our version of the server-side `ws` object you get from the `connection` event in `uws`. It inherits from `Stream`.

> they have full blown versions of upgradeReq

We store a reference to the upgrade request in the spark not because we like but because we have to. Primus has a middleware system which allows devs to add custom properties to the request or re-use existing express middleware to add cookies, sessions, etc. We can't use a fake `upgradeReq` object which stores only the most common stuff.
With this said everyone is free to do something like `spark.request = null;` if the `upgradeReq` object is such a problem. This is what uws does right after emitting the `connection` event.

> both maintainers are extremely hostile to the uws project in general

Lies, I saw a lot of potential in uws in the beginning and I helped the project in its early stage. I didn't do much honestly but I helped finding a couple of bugs in the parser, writing the JS interface, fixing the node-gyp configuration for macOS, etc, see https://github.com/uWebSockets/uWebSockets/pulls?q=is%3Apr+author%3Alpinca+is%3Aclosed. It's when the author started to insult `ws` developers for no reasons that I started to change my mind and realized that such a guy did not deserve any help.

> They also complain about the scalability and performance.

Where? How? Maybe this heated [discussion](https://github.com/uWebSockets/uWebSockets/issues/258), cause of my ban, but I didn't complain about performance. I did complain about the wrong numbers on uws README.

> They refuse to use the official interface, and instead rely on the low-level interface that is changing from time to time. This is not a good way of interfacing the uws module given that Primus does not enforce any particular version of uws and will thus continue to break from time to time.

This is a valid point. There are two reasons for using the native interface:

1. Performance. We are already a wrapper so why using the JS interface when the native one can be used directly? Hopefully with time things will stabilize and native interface won't change much.

2. The JS interface of uws is a mess.

**Comment by SEAPUNK** [comment]
So... `uws` detached fork when? :P

**Comment by alexhultman** [comment]
@lpinca Don't contact me again.

**Comment by lpinca** [comment]
@alexhultman ok no problem, and sorry if I contacted you via email yesterday. I only did it to report a bug as I had no other way to do it.

P.S. you are free to express your own opinions here, no one will delete your comments or censor you or ban you, like you did.

**Comment by alexhultman** [comment]
Appreciated.

**Comment by lpinca** [comment]
@SEAPUNK there is no need to maintain a fork as long as things keep to work :)

**Comment by lucidrains** [comment]
so... is this going to happen?

**Comment by lpinca** [comment]
@lucidrains #497.

**Comment by lucidrains** [comment]
👍
