### ISSUE TITLE
list of transformers as opposed to just one

### ISSUE THREAD

**Issue by siddo420** [primus/primus#499]
This may be a **feature request**.

Is it possible to somehow define an array (in priority order like localForage does it for its drivers) of transformers? So, the first one would be tried first and if not possible/available then the next one would be tried. 

This would help choose the most desired one like uWS first then fallback to Engine.io and so on etc.
I like the speed and performance of uWS but I also do not want to limit the target audience.

**Comment by lpinca** [comment]
What do you mean with "not possible/available"? If the required dependencies for a transformer are installed it will be available.

**Comment by lpinca** [comment]
You can make the `engine.io` transformer use `uws` though.

```
const primus = new Primus(server, {
  transformer: 'engine.io',
  transport: { wsEngine: 'uws' }
});
```

I didn't test it but it should work in `primus@>=6.0.0`.

**Comment by siddo420** [comment]
"possible/available" I meant not supported on the client

I will try the options you suggested. I'm on 6.0.0+ now (will set the evn var too).

Are there any potential issues you could think of?

**Comment by siddo420** [comment]
in addition to previous post:
uws seems to work but how do I make sure, uws is indeed used on the server side? Is there a message I can print on server when new data comes in?

**Comment by lpinca** [comment]
> Are there any potential issues you could think of?

I don't know as I didn't use this config in production but I know that it has been used for a while (without primus) by deepstream.io so it should be ok.

> Also, just to be doubly sure, the behaviour would still be to downgrade to polling, etc if the client has no support for websockets, right?

Yes.

> Is there anyway I could test this behaviour on newer browsers.

It should be possible with a command line flag or a an extension, for example `--disable-web-sockets` worked for Chrome. I don't know if it is still valid.
It is probably easier to just use `websockets: false` in the primus client options and see if it works.

> uws seems to work but how do I make sure, uws is indeed used on the server side?

`uws` sets the `server` header to `uWebSockets` in the upgrade response, so you can check that.

![screen shot 2016-10-23 at 08 08 47](https://cloud.githubusercontent.com/assets/1443911/19624474/0ad9d4be-98f8-11e6-9805-84728197bb22.png)

**Comment by lpinca** [comment]
Closing this, please comment or reopen if needed.
