### ISSUE TITLE
example production configurations and HAProxy config file

### ISSUE THREAD

**Issue by shahryargh** [primus/primus#500]
Can anyone share examples of their client configurations that are in use in production handling massive load?

Also, I wanted to get some examples for HAProxy configurations as well that are in production.

**Comment by 3rd-Eden** [comment]
While it would be nice have, that is really out of the scope of this project. Setting up a HAProxy configuration isn't that hard and quite good documented. An example of HAProxy config that works well with WebSockets is:

https://github.com/observing/balancerbattle/blob/master/haproxy.cfg
