### ISSUE TITLE
[doc][readme] Clarify connection method guessing

### ISSUE THREAD

**Issue by mk-pmb** [primus/primus#503]
**Version:** master

I tried to figure out whether primus will choose its connection method based on just browser features, or also network capabilities, e.g. old proxies doing strange stuff on long-running connections.
I couldn't figure it out from the readme within 2 minutes. I hope we can boast better. ;-)

**Comment by lpinca** [comment]
It depends on the transformer that is used. For example when using Engine.IO it will use the Engine.IO strategies, with SockJS the SockJS strategies, etc.

**Comment by mk-pmb** [comment]
Oh, I see, the default transformer is `websockets`. Somehow I had the impression that primus would select the best available protocol. Then maybe we can't boast better.

**Comment by lpinca** [comment]
If you think that something isn't clear in the documentation and clould be improved, please go ahead and send a PR :)

Thanks.

**Comment by lpinca** [comment]
Closing this, please comment or reopen if needed.
