### ISSUE TITLE
Stress Testing

### ISSUE THREAD

**Issue by omidh28** [primus/primus#504]
Might not exactly be related to Primus, But how one can test the Primus server under heavy load?

**Comment by ignasbernotas** [comment]
I've been wondering this myself. Thor doesn't seem to play nice, any tools that integrate with Primus?

**Comment by lpinca** [comment]
If you use a WebSocket only transformer, you can use any tool that work with WebSocket.
There are a few gotchas though:

- Disable the heartbeats.
- Remove all middleware.
- Use a "pass through" parser.

Something like this:

```js
'use strict';

const Primus = require('primus');
const http = require('http');

const passThrough = (data, fn) => fn(null, data);

const server = http.createServer();
const primus = new Primus(server, {
  transformer: 'uws',
  timeout: false, // Disable heartbeats
  pathname: '/',

  //
  // Use a "pass through" parser.
  //
  parser: {
    encoder: passThrough,
    decoder: passThrough
  }
});

//
// Remove middleware
//
primus.remove('cors');
primus.remove('primus.js');
primus.remove('spec');
primus.remove('authorization');
primus.remove('no-cache');
primus.remove('x-xss');

var cntr = 0;
primus.on('connection', (spark) => {
  if (++cntr === 1e5) console.log(process.memoryUsage());
  spark.on('data', (data) => spark.write(data));
});

server.listen(3000);
```

**Comment by ignasbernotas** [comment]
Any idea what needs to be done for SockJs?:)

**Comment by lpinca** [comment]
The setup will be basically the same but you need a SockJS client. You could test only the WebSocket transport in SockJS but I don't know how useful it is.
