### ISSUE TITLE
Webrtc with Primus

### ISSUE THREAD

**Issue by siddo420** [primus/primus#510]
I was looking at Webrtc recently and wanted to know if its possible to use Primus to support webrtc channels or if there is a plugin etc already available that does the trick?

Has anyone used Primus (possibly with other modules/plugins) to support audio/video calls?

**Comment by nanowizard** [comment]
WebRTC is a collection of protocols and APIs to allow browser's to communicate directly with each other. Therefore, an open "webrtc channel" doesn't involve a server at all. I think what you mean is to have Primus act as a signaling server to broker those connections.

I have used Primus to successfully act as the signaling server for [SimpleWebRTC](https://github.com/andyet/SimpleWebRTC). To be compatible with the library I used the [primus-emit](https://github.com/primus/primus-emit) module. Then it was just a matter of hooking up to the events on the server-side. For that I looked at their [signalmaster code](https://github.com/andyet/signalmaster/blob/master/sockets.js) and implemented those `client` event listeners on the `Spark`s in my`primus.on('connection',...)` listener. Pretty simple really.

I'm sure it wouldn't be hard to hook it up to other WebRTC implementations as well. To act as a signaling server, Primus basically just needs to forward messages between two clients until they establish an independent connection to each other.

**Comment by kevzettler** [comment]
Digging up an old thread but I am interested in this as well. 

The idea is not specific to using primus as a signaling server but using it as a medium for WebRTC Data channels. 

I have a project currently that uses WebRTC UDP data channels and falls back to WebSockets if not available

Ideally I would have one network library (Primus) instrumented that would handle the fallback

**Comment by indatawetrust** [comment]
https://github.com/indatawetrust/webrtc-signal-solution-with-primus
