### ISSUE TITLE
Client side primus.destroy() throwing null

### ISSUE THREAD

**Issue by toddbluhm** [primus/primus#516]
**Version: 6.0.6**

**Environment:**
  - **Operating system: Mac OS X Sierra**
  - **Browser: Latest Chrome**
  - **Node.js: v7**

**Expected result: Should not throw a null error, but should succeed in closing the primus connection/client**

**Actual result: A null exception error is thrown because `transformers` prop has already been nulled**

**Steps to reproduce:**
- Build the client side lib
- Start a primus server with websockets tranformer
- Have the client side call `primus.destroy()`

The issue appears to stem from this code here (which is generated when creating the client side lib):
```js
for (; i < keys.length; i++) {
  prop = keys[i];

  if (selfie[prop]) {
    if ('function' === typeof selfie[prop].destroy) selfie[prop].destroy();
    selfie[prop] = null;
  }
}

if (selfie.emit) selfie.emit('destroy');
run('after', selfie);
```
The issue with the above code is the `selfie.emit('destroy')` causes a write to occur which then uses the `primus.tranformers` prop on primus, but in the loop right before (shown above) we actually already nulled out `primus.transformers`.

Reversing this order seems to fix the issue, but I am not sure if its the correct order for destroying things

```js
if (selfie.emit) selfie.emit('destroy');  // call this before we null all the props in the loop below

for (; i < keys.length; i++) {
  prop = keys[i];

  if (selfie[prop]) {
    if ('function' === typeof selfie[prop].destroy) selfie[prop].destroy();
    selfie[prop] = null;
  }
}

run('after', selfie);
```

I am not super familiar with primus so maybe I am just doing something wrong or out of order. Any help with this would be appreciated.

**Comment by lpinca** [comment]
Hi and thanks for this report. `emit('destroy')` shouldn't trigger a write, is this something you are doing in a listener?

**Comment by 3rd-Eden** [comment]
@lpinca Well, actually it does. Because `destroy` calls `end` first which sends a final closing packet to the server to speed up the closing process on the server instead of waiting for a potential timeout of the socket's connection.

**Comment by lpinca** [comment]
@3rd-Eden you are correct, it does call [`primus.end()`](https://github.com/primus/primus/blob/3dfa647fbd40775dd9f2865cd70393be4058cda7/primus.js#L972) but that's [before](https://github.com/unshiftio/demolish/blob/5a452981c85751f18a3ae7b4c81a428b7a7d75e2/index.js#L55) nulling all the other properties and before emitting the `destroy` event no?

**Comment by 3rd-Eden** [comment]
@lpinca Yeah, thats what odd about it. I've digged through the demolish module and there's nothing that would allow a second `destroy` call to do another `end`. Maybe there is some race condition in `end` somewhere that would cause it call `transformers` again.

@toddbluhm Could you include the full stacktrace that you have so we could see the access pattern of the function?

**Comment by toddbluhm** [comment]
Sorry, forgot to include that stacktrace with the initial report. 

Here is the stacktrace:
<img width="1147" alt="screen shot 2016-12-08 at 12 17 29 pm" src="https://cloud.githubusercontent.com/assets/197282/21021956/74217280-bd40-11e6-963a-a6a43f83c760.png">

Here is the line where the null error is thrown:
<img width="886" alt="screen shot 2016-12-08 at 12 19 58 pm" src="https://cloud.githubusercontent.com/assets/197282/21022030/c14a93a2-bd40-11e6-8300-297acfd33ee8.png">

**Comment by lpinca** [comment]
@toddbluhm I have some questions:

- Did you register message transformers?
- What plugins are you using?
- Are you able to consistently reproduce this issue? If so can post a test case here or in a gist?
- Can you log what the client is trying to write after the call to `destroy`?

Thanks.

**Comment by toddbluhm** [comment]
Hey thanks for looking into this, but we have decided to move in a different direction and I no longer need to solve this issue. Going to close for now. To answer a few of your questions though:
- I registered the `websockets` transformer
- We were using these plugins here (in fact here is the creation code):
```js
var primus = new Primus(server, {
    pathname: '/primus',
    parser: 'json',
    transformer: 'websockets'
  });

  primus.plugin('emit', require('primus-emit'));
  primus.plugin('omega-supreme', require('omega-supreme'));
  primus.plugin('connection', connection);
  primus.plugin('propagate', propagate);

  primus.authorize(authHandler);
```
Unfortunately no answers for your last two questions as I did not have time to debug it further. Thank you so much for your help anyways. Hopefully this issue was just local to the project I was working on.
