### ISSUE TITLE
primus.recovery is not defined

### ISSUE THREAD

**Issue by omidh28** [primus/primus#521]
**Version:** 6.0.7

**Environment:**
  - **Operating system:** Mint 17
  - **Browser:** Chrome 56 and Firefox 49.0.2 
  - **Node.js:** 7.2.1 under harmony flag
  - Tried engine.io and uws

**Expected result:**
Primus should try to reconnect after offline network detection.

**Actual result:**

Primus throws this error:

>  Cannot read property 'reset' of null
>     at offline (primus-client.js:2562)

In source:
```

  primus.offlineHandler = function offline() {
    if (!primus.online) return; // Already or still offline, bailout.

    primus.online = false;
    primus.emit('offline');
    primus.end();

    //
    // It is certainly possible that we're in a reconnection loop and that the
    // user goes offline. In this case we want to kill the existing attempt so
    // when the user goes online, it will attempt to reconnect freshly again.
    //
    primus.recovery.reset();
  };

```

Problem is at `primus.recovery.reset();`  | recovery property does not exist on primus

**Steps to reproduce:**

Just make a connection then use chrome network throttle to go offline.

**Comment by lpinca** [comment]
Cannot reproduce on Chrome 55 with the following test.

<details>
<summary>server code</summary>

```js
'use strict';

const Primus = require('primus');
const http = require('http');
const fs = require('fs');

const server = http.createServer((req, res) => {
  if (req.url === '/client.js') {
    res.setHeader('Content-Type', 'application/javascript');
    fs.createReadStream(__dirname + '/client.js').pipe(res);
    return;
  }
  res.setHeader('Content-Type', 'text/html');
  fs.createReadStream(__dirname + '/index.html').pipe(res);
});

const primus = new Primus(server);

primus.on('connection', (spark) => console.log(spark.id, 'connected'));

server.listen(3000, () => console.log('listening on port 3000'));
```
</details>

<details>
<summary>client code</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script src="/primus/primus.js"></script>
    <script src="/client.js"></script>
  </body>
</html>
```

```js
(function () {
  var primus = new Primus();

  primus.on('open', function open() {
    console.log('open');
  });
})();
```
</details>

**Comment by omidh28** [comment]
@lpinca Try generating Primus client under harmony flag

**Comment by lpinca** [comment]
@omidh28 on node?

**Comment by omidh28** [comment]
@lpinca Yes

**Comment by lpinca** [comment]
Will do in a bit, after dinner.

**Comment by lpinca** [comment]
@omidh28 it still works.

**Comment by lpinca** [comment]
The `recovery` instance is added in the [constructor](https://github.com/primus/primus/blob/f1d4a4a37c6d8b5fae2809777fdfd2bc9472d587/primus.js#L132) and not removed unless you call `primus.destroy()` so I'm not sure why you get this error.

**Comment by omidh28** [comment]
@lpinca Thanks you were right, I was destroying Primus on 'end' event
