### ISSUE TITLE
spark.id in authorize method

### ISSUE THREAD

**Issue by utan** [primus/primus#522]
So I am playing with primus and primus.io and I would like to know how to get the spak.id in the auth hook?

Is it available at this point or only after authorization has been given?

is because I want to save to an array a pull it when I want to use to send data to this spark or when I want to disconnect it.

also how do you get the object where all sparks are located..  so I can do 

`objOfsparks[id].end();`

And where I set the allowed origin domain to access my app..?

I come from socket.io and trying to learn this one instead and see if it is more stable..

Thank for you help..

**Comment by lpinca** [comment]
> Is it available at this point or only after authorization has been given?

You can't get the spark id in the auth hook as there no spark at this point.

> also how do you get the object where all sparks are located.. so I can do

You can use `primus.spark(id)` to get a single spark or `primus.forEach(fn)` to iterate over them.

> And where I set the allowed origin domain to access my app..?

In the server options see https://github.com/primus/primus#getting-started. The `origins` is an array of a comma separated string with the allowed origins.

**Comment by utan** [comment]
@lpinca outstanding man.. this project seems to be great.. I like it already 

 thanks for your kind help...

 happy holidays
