### ISSUE TITLE
set some properties in authorization method?

### ISSUE THREAD

**Issue by utan** [primus/primus#523]
Hi guys,

Sorry again for bugging, is there a way to save some props, basically I just test my php session in this method and save the user in some global var then when authorized , pull it in the "connection" event and save the spark.id and check if already connected and update its properties accordingly..

I was trying to save in the "req" from your authorization example, and get it on the "spark" but I can't find it, undefined.. 

be aware that I am using Primus.io ..

Thanks .. happy holidays

**Comment by lpinca** [comment]
> I was trying to save in the "req" from your authorization example, and get it on the "spark" but I can't find it, undefined..

Yes, this should work, if you add custom properties to the `req` object in the auth hook, those should be available in `spark.request`.

**Comment by utan** [comment]
But i get undefined, very strange I will just use without Primus.io to see if works...

Will get back to u after testing..
