### ISSUE TITLE
disconnection event

### ISSUE THREAD

**Issue by utan** [primus/primus#524]
Hi guys,

So I was doing some client up in the disconnection event and wanted to send some object to clean at client side, and using the `spark.room('room').send('my_event', 'hello worrld');` didn't work, after sometime I decided to use  the Primus instance and it worked..

So it seems when the spark disconnected is not able to send and last payload to the client before complete dying correct?

Using primus.io haven't tried with only Primus.

thanks...

**Comment by lpinca** [comment]
When the `disconnection` event is emitted the `spark` is closed, so writing to it has no effect.

**Comment by utan** [comment]
Alright , thanks @lpinca Merry Christmas.

**Comment by lpinca** [comment]
You too!
