### ISSUE TITLE
authorize method printing twice console.log

### ISSUE THREAD

**Issue by utan** [primus/primus#525]
**Version:**
node v5.0.0
**Environment:**
  - **Operating system:**
Ubuntu server 14.04
  - **Browser:**
Firefox
  - **Node.js:**

**Expected result:**
Authorize should print console once 

**Actual result:**
It double print in console

**Steps to reproduce:**
https://github.com/utan/Primus-Authz

So, I notice it when doing some test at authorization method, using vanilla Primus.. if you can't duplicate there must be something in my environment doing it..

Can't pinpoint.. 

regards

**Comment by lpinca** [comment]
Didn't look at the code (**thanks** for creating a test case) but keep in mind that each request to the Primus server is authorized so if the transformer does more requests before establishing the connection (SockJS or Engine.IO) this is expected.

**Comment by utan** [comment]
ah, i see.. 
Then this must be spected behavior for this two transformers, "connection" event is fired once..

I will leave it open while I test the client side and don't get open events more that once..

regards mate

**Comment by lpinca** [comment]
Another case where the auth hook is called multiple times is when the transformer uses HTTP polling.

**Comment by utan** [comment]
@lpinca, should be included in the read me at the hook example so some noobies like me don't go crazy and drop the project because they think is flawed.. which is not..

**Comment by lpinca** [comment]
@utan 4e7c6f31aed33cb3197c28904a0ac56e83791d68. If you think it's not clear enough please let me know how it can be improved or send a PR 😉.

**Comment by utan** [comment]
I think that would be enough.. thanks mate again
