### ISSUE TITLE
req.headers.cookie undefined at authz method

### ISSUE THREAD

**Issue by utan** [primus/primus#526]
**Version:**
Latest Primus as of todays date
**Environment:**
  - **Operating system:**
 Ubuntu 14.04
  - **Browser:**
  - **Node.js:**
V5.11
**Expected result:**
 Spects req.header to have cookie propertie
**Actual result
 req.header.cookie is undefined
**Steps to reproduce:**
Cannot reproduce

So i got that
```javascript
var cookies 	= req.headers.cookie.split(';')
	            	                    ^
TypeError: Cannot read property 'split' of undefined

```

Quick workaround since i am not at computer is:
```javascript
var cookies 	= (req.headers.cookie && req.headers.cookie.split(';'))
```
I guess is on use to test for valid var..
Just wanted to share this error.

Happy new year.

**Comment by lpinca** [comment]
I don't think this is a Primus issue, the request object is passed "as is" to the auth hook.

**Comment by utan** [comment]
Well I can't reproduce , but it was live and the allowed domain are set and working property,

Must be some user sending payloads by URI GET,

But dunno how they do it since i am proxing tru nginx and origin is trusted..

Maybe i am wrong or missunderstood.

**Comment by utan** [comment]
oh, so they deleted their cookie when in the browser and then reconnected and had no cookies anymore..

I get it how they did it then..

thanks
