### ISSUE TITLE
Strange characters appearing on your github page

### ISSUE THREAD

**Issue by ivanixgames** [primus/primus#535]
several tiny strange characters appear down about the middle of the github page.
Search for "As a rule of thumb" and they appear just right below to the right. seem to be displaying vertically.  I think i was able to paste a sample of them here.

t̙͇͕̺̱̼̤̗̰̬̣͌ͬͧ͊́ͧͩ͌r͌̐̓̃ͥ̄ͤ͑̈ͬ͆ͬ͂̇̿̅ ҉̙̼̳̭̙͍̻̱̠͈̮̺̣̝̱̙̺͉ư̳͎̻͔̯̪̝͕͚̣̜̼̞͇̠̘̠̪c̨̫͙͙̬̰̰̫̐͋͊͑̌̾̉͆t͚̗͕̝̤̗͕̲̮̝̼̺͙͚̟͓̣̥͍ĭ͙̘̩̖͇͎̆̍̿̾ͤ̔̉̈̂̾̈ͭo̬̠̝͈̺̙̮̬̗̪̤͕͇͕̰̮͖͉̬n̙̪̤̝̹͖͖̻̬̹͙̞̗͓̞̭̜̠̟.

**Comment by 3rd-Eden** [comment]
See #468
