### ISSUE TITLE
Using example with typescript

### ISSUE THREAD

**Issue by lholznagel** [primus/primus#536]
**Version: 6.0.8**

**Environment:**
  - **Operating system:** Linux Ubuntu 16.04
  - **npm:** 4.0.5
  - **Node.js:** 7.4.0
  - **Typescript:** 2.1.5

**Expected result:**
When using typescript you should be able to use the example [connecting from server](https://github.com/primus/primus#connecting-from-the-server).

**Actual result:**
When you try the example with typescript you get errors that you can´t access the methods like that.

**Steps to reproduce:**
1. Create a new project that uses typescript
2. install primus
3. try to do the second example of [connection from server](https://github.com/primus/primus#connecting-from-the-server)

After some tinkering, I changed the definition file, which allows to use it like intended. If you are interested I am happy to create a pr.

**Comment by lpinca** [comment]
> After some tinkering, I changed the definition file, which allows to use it like intended.

Do you mean https://github.com/primus/primus/blob/master/primus.d.ts? If so, yeah please create a PR. We are not TypeScript users. Maybe it also makes sense to move the TypeScript definitions to https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by lholznagel** [comment]
Yep, I mean that. Will do the pr.

Moving to definitly typed is a good idea.

**Comment by 3rd-Eden** [comment]
I'm +1 on moving it to the DefinitelyTyped organization as we as authors don't really use TypeScript our selfs so the file that is currently in the root of the repository would remain largely unmaintained.

**Comment by lholznagel** [comment]
Saw that. I use typescript a lot, but definition files are also not really my special area.

**Comment by 3rd-Eden** [comment]
Closing this issue as the discussion continued in form of a PR #537
