### ISSUE TITLE
Primus failing to send/receive on Windows Lumia 920 phone

### ISSUE THREAD

**Issue by c0debreaker** [primus/primus#543]
**Version:** Primus 6.0.9

**Environment:**
  - **Operating system:** Windows Phone Nokia Lumia 920
  - **Browser:** Mozilla/5.0(Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 920) like Gecko
  - **Node.js:**

**Expected result:** Receive messages from other primus client

**Actual result:** Didn't receive messages from any nor it cannot send

**Steps to reproduce:**

I'm using this code on the nodejs side
```
primus.on('connection', function connection(spark) {
  console.log('connection was made from', spark.address);
  spark.on('data', function received(data) {
    console.log(spark.id, 'received message:', data);
   // spark.write(data);
    primus.write(data);
  });
});

primus.save(__dirname +'/public/primus.js');
```

Then I have this code in index.html
```
    <script>
      var output = document.getElementById('output')
        , echo = document.getElementById('echo');

      //
      // Tell primus to create a new connect to the current domain/port/protocol
      //
      var primus = new Primus('http://192.168.1.70:3001');

      //
      // Listen for incoming data and log it in our textarea.
      //
      primus.on('data', function received(data) {
        output.value += data +'\n';
      });

      //
      // Listen for submits of the form so we can send the message to the server.
      //
      document.getElementById('write').onsubmit = function submit(e) {
        if (e && e.preventDefault) e.preventDefault();

        //
        // Write the typed message.
        //
        primus.write(echo.value);
        echo.value = '';
      };
    </script>
```

It works great in Chrome, Firefox, Safari and Vivaldi on my mac osx laptop. Yesterday, I tried it on my Windows Nokia Lumia 920 phone. I saw the chat window. When I send messages, it doesn't get received by other clients. The phone also cannot receive messages from other browser clients. I can see the `echo` application on my phone even if I refresh it so many times.

Does primus support browsers on Windows phone? Is there any code that I need to add?

**Comment by lpinca** [comment]
What transformer are you using? Is the connection established?

**Comment by c0debreaker** [comment]
I was wrong. I have an issue with the ip address. It's working now. :)
