### ISSUE TITLE
Primus clients fail to regain connectivity when primus server has been offline for many more than 3 mins

### ISSUE THREAD

**Issue by c0debreaker** [primus/primus#545]
**Version:** "primus": "^6.0.9",

**Environment:**
  - **Operating system:** Osx
  - **Browser:** Chrome 
  - **Node.js:** 6.9.1

I'm using ReactJS for the client and NodeJS/Primus for the server.

The index.html served by ReactJS contains this code
```
<script>
  window.primus = new Primus('http://localhost:3001');
</script>
```

and in my componentDidMount, it just waits for updates
```
  componentDidMount() {
    window.primus.on('data', (data) => this.setState(data));
  }
```

on my NodeJS server
```
primus.on('connection', function connection(spark) {
  console.log('connection was made from', spark.address);
  spark.on('data', function received(data) {
    console.log(spark.id, 'received message:', data);
   // spark.write(data);
    primus.write(data);
  });
});
```

I also have a setInterval in the NodeJS server that calls primus.write,
```
setInterval(function() {
  axios.get('http://backend-api-server/getstatus', {
  }).then((o)=> {
      primus.write(o.data);
      lastStatus = o.data;
  })
  .catch((error) => {
    console.log('[ -=<<< PROMISE ERROR >>>=- ]', error);
  })
}, 5000);

It's working great. However, once I kill the primus server and let it wait for more than 3 mins before I start it again, the browsers who were previously connected cannot regain connectivity to primus server. I waited for 10 mins and it was never able to reconnect. If I refresh the browser, its able to connect again.

Am I missing a configuration or is this a known bug in Primus?

**Comment by lpinca** [comment]
Check the reconnection [events](https://github.com/primus/primus#events). The client will not try to reconnect indefinitely and stops after a maximum number of attempts.

**Comment by lpinca** [comment]
@c0debreaker any update on this?

**Comment by c0debreaker** [comment]
I just saw your messages now. I'll check it tomorrow. However, you answered my question that Primus will not try to reconnect. I had a wrong thinking about Primus. I thought it will keep on trying to connect. 

What is the ideal way to do so that users will be informed that they'll need to refresh their browsers?

**Comment by lpinca** [comment]
You can customize the reconnection procedure in every part and I think you can also make it try to reconnect forever.

> What is the ideal way to do so that users will be informed that they'll need to refresh their browsers?

When the reconnection fails (you have an event for that) tell the user to refresh?

**Comment by c0debreaker** [comment]
Cool! Thanks a lot!
