### ISSUE TITLE
Feature Request: Ability to hook up a custom spark ID generator

### ISSUE THREAD

**Issue by nanowizard** [primus/primus#551]
I noticed that Primus uses [yeast](https://github.com/unshiftio/yeast) in the event that the transformer doesn't provide IDs. In our particular case, we're using the [ws](https://github.com/websockets/ws) implementation, and we'd like to use our own custom ID generator due to particular application requirements. We could, of course, create a mapping of spark IDs to our own generated IDs but that gets messy. It would be nice if we could just plug in our generator into Primus and use that ID.

Is there an easy way to accomplish this currently?

**Comment by lpinca** [comment]
There is no way atm and I think it would be nice to have as yeast does not grant uniqueness across multiple machines/processes.

It shouldn't be hard to add the feature. A new option in the Primus constructor should be sufficient. For a quick workaround you can replace the spark id when the `connection` event is emitted.

**Comment by 3rd-Eden** [comment]
We'll be more than happy to accept a PR for this functionality.

**Comment by nanowizard** [comment]
Sounds great, thanks! If I manage to find some time this weekend I'll tinker with it.

**Comment by lpinca** [comment]
Fixed by #601.
