### ISSUE TITLE
Better typescript support

### ISSUE THREAD

**Issue by reflectiz** [primus/primus#552]
**Version:**
6.1.0

**Environment:**
  - **Operating system:** Any
  - **Browser:** Any
  - **Node.js:** 7.3.0
  - **typescript** 2.2.1.0

**Expected result:**
The typescript definition file should be recognized automatically.

**Actual result:**
We need to add `/// <reference path="./node_modules/primus/primus.d.ts" />` to every file

**Steps to solve it:**
Add the following row to the package.json file
`"typings": "primus.d.ts"`

**Comment by lpinca** [comment]
Yes, take a look at #537.

**Comment by ad-venture** [comment]
You want me to open the PR?

**Comment by lpinca** [comment]
I think @lholznagel is preparing a new PR to fix everything. If you want to submit a PR to fix the package.json go ahead but it will not be in release immediately.

**Comment by lholznagel** [comment]
Targeting tomorrow for the pr :+1: 

The adding of `"typings": "primus.d.ts"` will be a part of it.

**Comment by lholznagel** [comment]
@ad-venture if you are interested in helping, I have a repo for testing my current stand of the definition files.
https://github.com/lholznagel/primus-test
In the code there are some `TODO` fields, I am glad for every help :).

Thanks to all the examples it takes much longer than I thought :D

**Comment by gurt-il** [comment]
Now I'm getting `primus_1.Primus is not a constructor` on the node window.
My code looks like this:
```
import { Primus, ISpark } from "primus"

var primus = new Primus(this.httpServer, { transformer: "uws", pathname: "/ws" });
```

Anybody has similar problem? Am I doing something wrong?

Thanks

**Comment by harangue** [comment]
@gurt-il Did you ever figure out how to fix this?

**Comment by gurt-il** [comment]
Nop. :(
I'm using `require("primus")` now so the .d.ts is not affecting, but sure it's not the real solution
