### ISSUE TITLE
Cutting internet never causes disconnect on server

### ISSUE THREAD

**Issue by goldfire** [primus/primus#553]
**Version:** 6.1.0

**Environment:**
  - **Operating system:** Linux/Unix
  - **Browser:** Any
  - **Node.js:** 7.5.0

**Expected result:**
The `end` event should fire on the server for the spark.

**Actual result:**
This event is never fired, so tracking which users are actually still online becomes unreliable.

**Steps to reproduce:**
Open a connection to the server and then either turn off your internet or in Chrome check the "offline" box in the network tab of dev tools.

Is it possible that https://github.com/primus/primus/pull/534 will fix this issue? If so then this may not be a valid issue any longer once that is merged.

**Comment by lpinca** [comment]
Did you mean `ws@2.0.2` in version? [`primus@2.0.2`](https://github.com/primus/primus/releases/tag/2.0.2) is very old.

**Comment by goldfire** [comment]
@lpinca Sorry, I looked at releases and saw the 2.0.2 in the title of the latest release and wrote that down without thinking. I've corrected the issue.

**Comment by goldfire** [comment]
And to that point, we are using the uws transformer on the latest version.

**Comment by lpinca** [comment]
@goldfire when the heartbeat timeout [expires](https://github.com/primus/primus/blob/4b8e57d87afe10befcf852547d2937470301ebf4/spark.js#L120) `spark.end()` is called so you should receive the `end` event on the spark.

Can you track the [`heartbeat`](https://github.com/primus/primus/blob/4b8e57d87afe10befcf852547d2937470301ebf4/spark.js#L126) event to see if everything work as expected?

**Comment by lpinca** [comment]
@goldfire I cannot reproduce. The spark is disconnected as soon as the offline box is checked as per https://github.com/primus/primus/blob/4b8e57d87afe10befcf852547d2937470301ebf4/primus.js#L599.

**Comment by goldfire** [comment]
Yes, we've just found an unrelated issue in our environment that was making it look like this was the issue. Sorry about that and thanks for your work on this fantastic project!
