### ISSUE TITLE
Debugging messages from frameworks

### ISSUE THREAD

**Issue by tcdaly** [primus/primus#561]
Does Primus have the ability to capture and/or configure debugging messages generated by the underlying framework?  Is there any way of routing such messages through a preferred node.js logging module such as [Winston](https://github.com/winstonjs/winston)?

**Comment by lpinca** [comment]
You can probably use the `DEBUG` env variable when it is supported (Engine.IO/SockJS) but we strip the debug statements from the clients to reduce the size so I'm not sure if it is very useful.

>  Is there any way of routing such messages through a preferred node.js logging module such as Winston?

No, unless it is supported by the underlying framework. In that case you can just forward the configuration options.

**Comment by tcdaly** [comment]
Thank you for the clarification.
