### ISSUE TITLE
Invalid HTTP version string: HTTP/1.0

### ISSUE THREAD

**Issue by peacemakr** [primus/primus#565]
**Version:**
7.0.0

**Environment:**
  - Mac OS X
  - Safari
  - 5.12.0

**Expected result:**
Connection should be made without any issues

**Actual result:**
Getting this error in Safari
```
WebSocket connection to 'wss://<domain name>/primus/?isapp=false&_mirage=90rqrqew432&_primuscb=LiPtb_J&EIO=3&transport=websocket&sid=oLp9L-EBnJ--2CtOAAAA&t=LiPtc2f&b64=1' failed: Invalid HTTP version string: HTTP/1.0
```

**Steps to reproduce:**
I don't know how to reproduce but here is what I did that may have caused issues.

- upgraded engine.io and primus to latest
- started using actual domain names with proper SSL certificate

I should also mention that I upgraded to 7.0.0 and only disabled ping and pong settings in client. Is that enough?

**Comment by peacemakr** [comment]
Please note that Chrome is working fine.

**Comment by lpinca** [comment]
What version of Safari are you using? Can you show us the request as it appears in dev tools tab?
My guess is that Safari is sending the `connection: upgrade` header with HTTP 1.0 which is not valid as it required HTTP 1.1.

**Comment by peacemakr** [comment]
Version 10.0.3 (12602.4.8)

Looks like these HAProxy auth settings are messing with Safari (only).

```
  acl auth_ok http_auth(developers)
  http-request auth unless auth_ok
```

Is there a sample HAproxy config hat works best with Primus somewhere?

**Comment by lpinca** [comment]
Not that I know of. Configurations are generally bound to a specific use case.

**Comment by peacemakr** [comment]
ok thanks.

**Comment by lbdremy** [comment]
@peacemakr did you find a fix ?

**Comment by spinus** [comment]
@peacemakr the info about basic auth finished my few days debugging of that issue and saved long days, thank you very much.
