### ISSUE TITLE
Needless request when use Primus as pure WebSocket request (need help).

### ISSUE THREAD

**Issue by CrisLi** [primus/primus#583]
**Version: 7.0.1**

**Environment:**
  - **Operating system: MacOS**
  - **Node.js: v7.5.0**

**Expected result:**

I am using `Primus` as a pure WebSocket client to connect an existing WebSocket server.

If I use `ws` directly, everything is fine. 403 will be returned if via `Primus`.

**Actual result:**

There is a needless request before the real request. Then my server will response 403 back. According to the error log, the request URL is:

```
url: 'wss://myserver:port/primus?watch=true&access_token=xxx&_primuscb=Llc1CS0'
```

Apparently, my server will return 403 if any request to the `/primus`.

**Steps to reproduce:**

Run the below code, I get the 403 error.

```js
const Primus = require('primus');
const url = 'wss://myserver:port/apis?watch=true&access_token=xxx';

const options = {
  transformer: 'websockets',
  transport: {
    rejectUnauthorized: false,
    origin: 'https://localhost'
  }
};

const Socket = Primus.createSocket();

const client = new Socket(url, options);

client.on('open', () => {
  console.log('openned');
});

client.on('data', (data) => {
  console.log(data);
});

client.on('error', (err) => {
  console.error(err);
});

```

**Comment by lpinca** [comment]
Set the `pathname` option to `/`, it should work.

```js
const options = {
  pathname: '/',
  transformer: 'websockets',
  transport: {
    rejectUnauthorized: false,
    origin: 'https://localhost'
  }
};
```

**Comment by CrisLi** [comment]
@lpinca Add `pathname` did not work. There is still a request to the `/primus?watch=true&access_token=xxx&_primuscb=Llmvja2`.

It seems like the `pathname` did not change the default value (`/primus`) of URL namespace that Primus can own.

**Comment by lpinca** [comment]
You should pass the option to `Primus.createSocket()` not the `Socket` constructor.

```js
'use strict';

const Primus = require('.');

const Socket = Primus.createSocket({
  transformer: 'websockets',
  pathname: '/apis'
});

const client = new Socket({
  url: 'https://example.com/?watch=true&access_token=xxx',
  transport: {
    rejectUnauthorized: false,
    origin: 'https://localhost'
  }
});

client.on('outgoing::url', (url) => console.log(url));
```

**Comment by CrisLi** [comment]
@lpinca  It works, thanks a lot.
