### ISSUE TITLE
Chaning the query string

### ISSUE THREAD

**Issue by jerome724** [primus/primus#585]
**Version:** 7.0.1

**Environment:**
  - **Operating system:** Win 10
  - **Browser:** Chrome
  - **Node.js:** 7.10.0

Is it possible to change the query string? So instead of ``/primus?_primuscb=Lm5zLJ_`` something like ``primus?_websocket=Lm5zLJ_``?

**Comment by lpinca** [comment]
Do you want to change the name of the `_primuscb` argument? If so there is no way atm.
I think it's safe to move this [`emit`](https://github.com/primus/primus/blob/b5ca35e22fd4ca29cfed7aaf9345f664b0bd8a82/primus.js#L1060) few lines below, just after updating [`options.query`](https://github.com/primus/primus/blob/b5ca35e22fd4ca29cfed7aaf9345f664b0bd8a82/primus.js#L1069).

This will allow you to change the name of the cache busting argument.
