### ISSUE TITLE
Android/iOS support?

### ISSUE THREAD

**Issue by nanom1t** [primus/primus#593]
Hi,

A Primus library looks pretty interesting for me. However I have a few questions about it.

1) Does Primus support Android/iOS? Are there any suitable plugins in Java / Objective-C / Swift, which allow to connect to Primus servers?

2) Is there a way to organize chat rooms with Primus as Socket.io does? Is it supports scaling onto few servers?

Thanks

**Comment by lpinca** [comment]
1. There is this lib https://github.com/cine-io/primus-android for Android but I think it's a bit outdated. Anyway it may be good as a starting point. I honestly don't know if there is a client for iOS.

2. There are some plugins like https://github.com/cayasso/primus-rooms/ and https://github.com/fadeenk/primus-rooms-redis-adapter.

**Comment by lpinca** [comment]
Forgot about this client for in Objective-C: https://github.com/seegno/primus-objc

**Comment by nanom1t** [comment]
Thanks for your response. I will try to check these solutions.

**Comment by lpinca** [comment]
Closing this, feel free to reopen if needed.
