### ISSUE TITLE
question about primus connection attempts status on client

### ISSUE THREAD

**Issue by siddo420** [primus/primus#594]
**Version:**
latest (As of this writing)
**Environment:**
  - **Operating system:**
Mac OS X
  - **Browser:**
Laest Chrome
  - **Node.js:**
7.x

I wanted to know the client events that should be used to display reconnection attempts on the browser (like Gmail, Slack etc). I'm currently using "reconnection scheduled" event to display when the next attempt will be made. However, I also want to give an option for user to force a reconnect right now (using primus.open()). 

However, I'm not sure which event to use next for the next status update. It seems readyStateChange is triggered but there are many states that client can be in while triggering this event (for example this is also triggered right at the beginning when app is loaded at which point I dont want to display anything (status updates are for reconnection attempts only)).

**Comment by lpinca** [comment]
I'm not sure I understand but you can force a reconnect by closing and reopening the connection.

```js
primus.end();
primus.open();
```

At this point you can use the regular `open` and `reconnect*` events.

**Comment by siddo420** [comment]
Sorry, I wasn't clear enough I think. I will explain below.

However, the solution you proposed could be one option, but as soon as I end the connection (primus.end()), primus stops and never opens with primus.open(). If I go through primus.connect etc then I need to add events again on the new conn (too much code change reqd).

So basically, what I want is that when a reconnection attempt is ongoing and a user clicks on that "Reconnect Now" or "Try now" button, instead of waiting for the next scheduled autoreconnect attempt (which was going to happen in 'x' seconds), the reconnection attempt should be made now. 
I guess, I need to know if there is a primus.reconnect({ "do_not_wait_for_next_attempt": true }) function. I tried primus.open() already(seems wrong approach now??) that triggers the "readyStateChange" event.

I'd be happy to answer your questions.

**Comment by siddo420** [comment]
my primus config:

```
{
reconnect: { max: 500 * _.random( 60, 100 ) * 1, min: _.random( 2000, 3000 ), retries: 10 },
timeout:   10000,
manual: true,
transport: {},
queueSize: Infinity
}
```

**Comment by lpinca** [comment]
> However, the solution you proposed could be one option, but as soon as I end the connection (primus.end()), primus stops and never opens with primus.open(). 

This is weird as `primus.open()` emits the `outgoing::open` event, which is the same event emitted when a reconnection is attempted.

**Comment by siddo420** [comment]
no, its just ends and I think the reason is "error" event is called.

**Comment by lpinca** [comment]
It seems to work fine on my machine. I tried with a simple test that simulates the "Try now" when the fifth reconnection attempt is scheduled. 

```js
(function () {
  var primus = new Primus();

  primus.on('open', function () {
    console.log('open');
  });

  primus.on('reconnect scheduled', function (opts) {
    console.log(Date.now(), opts.attempt + '/' + opts.retries);

    if (opts.attempt === 5) {
      console.log(Date.now(), 'Try now');
      primus.recovery.reset();
      primus.end();
      primus.open();
    }
  });
})();
```

![screen shot 2017-06-08 at 08 46 13](https://user-images.githubusercontent.com/1443911/26915674-4c894060-4c27-11e7-8b55-71acff386d8e.png)

**Comment by lpinca** [comment]
You can also try with

```js
if (primus.recovery.reconnecting()) {
  primus.recovery.reset();
  primus.recovery.reconnect();
}
```

**Comment by siddo420** [comment]
how did you mimic a network disruption? In my case, I was shutting down my server and was receiving err code 503 on client (in "error" event).
I'm going to try what you just mentioned.

**Comment by lpinca** [comment]
Yes, I simply killed the server process with Ctrl-c.

**Comment by siddo420** [comment]
only below seems to work for me:

```
if (primus.recovery.reconnecting()) {
  primus.recovery.reset();
  primus.recovery.reconnect();
}
```
I will reopen if something comes up.

After dealing with several modules, I'm pretty sure Primus is probably the best supported project on github.

Thanks man.
