### ISSUE TITLE
Is the latency property set with SockJS?

### ISSUE THREAD

**Issue by giggsey** [primus/primus#599]
**Version:** Primus: 7.0.2 / SockJS: 0.3.18

**Environment:**
  - **Operating system:** Ubuntu 17.04
  - **Browser:** Chrome stable
  - **Node.js:** 6.10.2

**Expected result:**

latency property on the client should be populated.

**Actual result:**

latency: 0. There is nothing changing latency in the generated primus.js

**Comment by lpinca** [comment]
It has been removed in `primus@7`. See https://github.com/primus/primus/releases/tag/7.0.0.
I see we have a leftover in the code. Feel free to open a PR to remove that.

**Comment by giggsey** [comment]
Ahh, I didn't see that.

Is there something that provides similar functionality ?

**Comment by lpinca** [comment]
You can write a plugin taking advantage of the heartbeat messages. Take a look at https://github.com/Fishrock123/primus-spark-latency to get an idea.
