### ISSUE TITLE
Primus on Laravel Projects

### ISSUE THREAD

**Issue by yovanoc** [primus/primus#600]
**Version:** Latest

**Environment:**
  - **Operating system:** macOS Sierra 10.12.4 (16E195)
  - **Browser:** Chrome Canary
  - **NPM:** 4.2.0
  - **Node.js:** v7.9.0

**Expected result:** I just want to connect to a primus server on a Laravel Project. Exactly on VueJS files. And when I import Primus from 'primus'  I always have error like "can't resolve fs" or "can't resolve net" ... i see that i have to add something in the webpack config ... I tried :

`mix.webpackConfig({
  //target: 'node'
  /* node: {
    fs: "empty",
    net: "empty" 
  } 
*/
 });`

the target, and the fs and net things... but nothing work... Thanks for your help

**Comment by lpinca** [comment]
I think you have to build the client then bundle it with webpack as an external library.
I never used this plugin: https://github.com/kkemple/primus-webpack-plugin but maybe it helps.

**Comment by yovanoc** [comment]
Thanks for your answer but I know that the server is built with primus, but i don't know the configuration about the server exactly... I try to replace in my laravel project primus by socket.io client, and its working but isn't nice with the primus::ping etc .. and I don't understand why there is no client in primus directly and I don't know how to do it

**Comment by lpinca** [comment]
If it hasn't been disabled/removed, there is a middleware which can be used to know the server config. Try to send a GET request to the `/<pathname>/spec` endpoint. `pathname` is `primus` by default.

**Comment by yovanoc** [comment]
Thanks, I received this reponse: what should I do now?

`{"version":"5.2.1","pathname":"/primus","timeout":35000,"parser":"json","transformer":"engine.io"}`

**Comment by yovanoc** [comment]
So, I just done a node server with : 

`'use strict';

var Primus = require('primus')
  , http = require('http');

var server = http.createServer(/* request handler */)
  , primus = new Primus(server, {
      transformer: 'engine.io'
  });

  primus.save(__dirname +'/primus.js', function save(err) {
      console.log(err);
  });
`

and after i load the js in a normal script tag on html, and after i instanciate like this 

`this.primus = new Primus(endpoint, {
                    timeout: 35000
                })`

and it seems to work, but there is no simple way? thanks

**Comment by lpinca** [comment]
Yes that's it. You can use a simple `EventEmitter` instance instead of a HTTP server.

```js
const EventEmitter = require('events');
const Primus = require('primus');

const primus = new Primus(new EventEmitter(), {
  transformer: 'engine.io'
});

primus.save('client.js');
```

You should then also be able to bundle the client.

**Comment by yovanoc** [comment]
Oh thanks, but then, I have to load it in a simple script tag on html or there is a way to load it with import ?

**Comment by lpinca** [comment]
It should work with `import`.

```
import Primus from './client.js'
```

or at least it works with `require` and browserify.

If it doesn't, try the solution suggested here https://github.com/primus/primus/issues/390#issuecomment-145094080 or here https://github.com/kkemple/primus-webpack-plugin#caveats.

**Comment by yovanoc** [comment]
is working great without the kkemple primus plugin, thanks for you ! you can close this, a lot of luck for continuing your beautiful library, thanks !
