### ISSUE TITLE
Conflict with qaap/rpc-websockets

### ISSUE THREAD

**Issue by ulion** [primus/primus#604]
**Version:**
npm newest

**Environment:**
  - **Operating system:**
OSX EL Caption
  - **Browser:**
N/A
  - **Node.js:**
v6.11.1

**Expected result:**
Work as use primus only

**Actual result:**
Report timeout then reconnect and keep failing (it reported that, but indeed the connection looks ok by checking the real network connection)

**Steps to reproduce:**
import qaap/rpc-websockets into the same node app, and probably also use qaap/rpc-websockets to connect to somewhere, then the original primus working code will report failure because of some hidden conflict.

**Comment by lpinca** [comment]
Are you using  Primus to connect to a plain WebSocket server? If so, you have to take into account:

- The heartbeats. The Primus client expects ping messages to be sent by the server. If no ping is received the connection gets closed.
- The parser. You must ensure that messages are encoded/decoded with the same parser used by Primus.

**Comment by ulion** [comment]
Yes, I use it with a plain websocket server.

is there a way to turn off the heartbeats?

and I do use json parser, so this is not the problem.

but the case I encountered is not in above 2 cases, it's clearly if I import rpc-websockets (which uses uws in its implement), the primus will fail to connect. else it has no problem.

**Comment by ulion** [comment]
it's in a complex app, I tried, but failed to reproduce it with a simple short code. what I can tell, in my env, if I does included rpc-websockets, even does not really call the Websocket (of rpc-websockets), it will cause primus failure. and if I comment out the require line of importing rpc-websockets, the primus will works.

**Comment by lpinca** [comment]
Heartbeats can be disabled by setting the `pingInterval` option to `false`. You have to rebuild the client for changes to take effect.

What I can suggest is to start a plain uws server, build the Primus client using the `websockets` transformer and use it to connect to the uws server to see if the connection can be established.

**Comment by ulion** [comment]
the connection is indeed connected, but the primus think it's not, due to
some strange conflict between the other library. either websockets or uws
as transformer results same.

2017-08-15 18:25 GMT+08:00 Luigi Pinca <notifications@github.com>:

**Comment by lpinca** [comment]
> either websockets or uws as transformer results same.

Yes this is expected as the uws transformer uses the websockets transformer as client.
Anyway this is odd as all tests pass and the uws transformer just starts a plain uws server. The only difference is that we are using the native interface.

**Comment by ulion** [comment]
which indicated that I used wrong url in the case, sorry for the noise.
