### ISSUE TITLE
Spark is writing only after 5-30 sec after connection.

### ISSUE THREAD

**Issue by hkrawczyk** [primus/primus#609]
**Version:** latest (7.1.0)

**Environment:**
  - **Operating system:** Windows 10
  - **Browser:** Chrome, FF
  - **Node.js:** 6.9.5

**What I'm trying to do:**
Basically I'm using Primus wiith BrowserChannel transformer along with cookies and session from pgStore (Postgress Store). As I want to make app "real life" I've created "TheGreatLoop.js" where I can get Primus instance by using "getIO()" function.

initializing:
```
const app = express();
const http = require('http');
const server = require('http').createServer(app);
const Primus = require('primus');
const primusRooms = require('primus-rooms');
const primusSession = require('./primus/utils/session');
var io = new Primus(server, { transformer: 'browserchannel' });
const TheGreatLoop = require("./primus/TheGreatLoop.js");
```

session:
```
const cookies = cookieParser(secrets.sessionSecret);
app.use(cookies);

const pgStore = new pgSession({
    conString: secrets.postgres,
    tableName: secrets.sessionTable
});

app.use(session({
  store: pgStore,
  secret: secrets.sessionSecret,
  saveUninitialized: true,
  resave: false,
  cookie: {
    maxAge: 30 * 24 * 60 * 60 * 1000, // 30 days
    httpOnly: true
    //, secure: true // only when on HTTPS
  }
}));
```
primus config:
```
io.use('cookies', cookies);
io.use('session', primusSession, { store: pgStore });
io.plugin('rooms', primusRooms);
TheGreatLoop.setIO(io);
io.library();
io.save(__dirname +'/public/primus.js');

```

content of "TheGreatLoop.js"
```
var io;

module.exports.setIO = function(app_io) {
    io = app_io;

    function TheGreatLoop() {
        io.room('offers').write(getOffersToSend());
    }
    setInterval(TheGreatLoop, 1000);



    io.on('connection', function connection(spark) {

        spark.join("offers", function () {//it's not corelated to anything, just example
            spark.write({register:"offers"});
        });

    });

};


module.exports.getIO = function () {
    return io;
};
```

And require in any other file:
```
var tgl = require('../primus/TheGreatLoop');
tgl.getIO().forEach(function (spark, id, connections) {
            if (spark.request.session.passport.user === req.userId) {
                   console.log("got him!");
                    spark.write({
                        notification: {
                            data: req.data
                        }
                    });
                }
         

        });
```

**Expected result:**
1. If I'm registering user to room "Offers" he will get the 
> {register:"offers"}
2. After that, if user have to get some notification I'm searching through all connected users, get "got him!" console log and the notif is sent

**Actual result:**
1. I'm registering user to room "Offers" and user gets the 
> {register:"offers"}
2. If page is refreshed user get's the register notice but won't get any notification. If user will stay on website for like 5-30 seconds without refershing, the notification message will start working (only for new requests, old won't be fullfiled). 
I'm having the "got him!" console log but spark.write is just not sending anything or client isn't recieving it. 

It would be understandable that it might be some connection issue but right after website refersh, user get's message about being registered to room so there is already the connection! How it's possible that using Primus by "getIO();" have to wait few seconds before it will even work? After those 5-30sec everything is working perfectly but there is no sign what caused that.

**Comment by lpinca** [comment]
I don't know, did you try with one of the WebSocket transformers?

**Comment by Hoax00** [comment]
@lpinca no, but actually I want to use BrowserChannel so it would be pointless anyway. If I won't make it work, I will have to switch to dedicated solution but we (my team) really want to stick with Primus

**Comment by lpinca** [comment]
It's not pointless, it will be useful to understand if it is a BrowserChannel issue or a Primus issue.

**Comment by 3rd-Eden** [comment]
I agree with @lpinca that would give is a direction we need to search at. Also which Primus version and BrowserChannel versions are you using?

**Comment by Hoax00** [comment]
@3rd-Eden  @lpinca 
I will try with websockets at home. Meanwhile:
`"browserchannel": "^2.1.0"`
and 
`"primus-rooms": "^3.4.1"`

**Comment by Hoax00** [comment]
@3rd-Eden @lpinca it's working well with sockets. Looks like browser channel issue. Any ideas?

**Comment by lpinca** [comment]
@Hoax00 no, what strikes me odd is that you get the `{register:"offers"}` message when you refresh the page and then no more data is sent for that amount of time.

**Comment by Hoax00** [comment]
@lpinca yep, thats true - any idea? :D

**Comment by lpinca** [comment]
@Hoax00 no idea. If you can try to create a minimal (no primus-rooms) reproducible test case and share it so we can investigate further.

**Comment by lpinca** [comment]
@Hoax00 I can't reproduce the issue. Here is my test case:

<details>
<summary>server.js</summary>

```js
const Primus = require('primus');
const http = require('http');
const path = require('path');
const fs = require('fs');

const server = http.createServer((req, res) => {
  if (req.url === '/client.js') {
    res.setHeader('Content-Type', 'application/javascript');
    fs.createReadStream(path.join(__dirname, '/client.js')).pipe(res);
    return;
  }
  res.setHeader('Content-Type', 'text/html');
  fs.createReadStream(path.join(__dirname, '/index.html')).pipe(res);
});

const primus = new Primus(server, {
  transformer: 'browserchannel'
});

primus.on('connection', (spark) => {
  console.log(spark.id, 'connected');
  spark.write({ register: 'offers' });

  setTimeout(() => {
    spark.write({
      notification: { data: 'foo' }
    });
  }, 5000);
});
primus.on('disconnection', (spark) => {
  console.log(spark.id, 'disconnected');
});

server.listen(3000, () => console.log('listening on port 3000'));
```
</details>

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script src="/primus/primus.js"></script>
    <script src="/client.js"></script>
  </body>
</html>
```
</details>

<details>
<summary>client.js</summary>

```js
(function () {
  var primus = new Primus({ strategy: false });

  primus.on('open', function () {
    console.log('open');
  });

  primus.on('data', function (data) {
    console.log(data);
  });
})();

```
</details>

What I noticed is that the connection is not immediately closed when the page is refreshed but that is a different issue. All data is received as expected on the new connection.

**Comment by Hoax00** [comment]
@lpinca thank you for example, I will test it today and post the results ;) if something will be still wrong I'll prepare the test case.

**Comment by Hoax00** [comment]
@lpinca looks like exmple works perfectly. I'm wondering where the issue is? Express?
Btw. why do we have 
` var primus = new Primus({ strategy: false });`
on frontend?

**Comment by lpinca** [comment]
@Hoax00 I don't know, try to add `express` and see it makes any difference.

> why do we have `var primus = new Primus({ strategy: false });` on frontend?

Copy/paste leftover 😄.

**Comment by jsdream** [comment]
Hello guys,

I'm having the same problem after upgrading Primus from 6.1.0 to 7.1.1 (latest).
So any connection is being closed within 30 seconds after connection has been established.
In my case I'm using Primus with `engine.io` transformer, so it doesn't seem to be a transformer issue.
I'm also using primus-emit and primus-rooms plugins.

Downgrading back to 6.1.0 resolves the problem, thus I suspect the issue might be in Primus itself.

I have no time today, but tomorrow I will try to create a separate test case reproducing this bug.

Anyway, @hkrawczyk what you ended up with?

**Comment by lpinca** [comment]
@jsdream in version 7 we changed the heartbeat system by using server sent pings. See https://github.com/primus/primus/releases/tag/7.0.0

Make sure to update your code accordingly. If I have to guess the client is not responding to ping message in your case.

**Comment by jsdream** [comment]
@lpinca Thanks for your response. You are right that the client was not responding to ping messages. It was due to the fact I'm using client side library generated using `primus.save()` and I simply forgot to regenerate it after the upgrade to version 7 (although I read about breaking changes).

Sorry for the noise. Seems to be working fine after I've regenerated the client side library.

**Comment by 3rd-Eden** [comment]
Thanks for confirming a fix.
