### ISSUE TITLE
TypeScript problem?

### ISSUE THREAD

**Issue by yovanoc** [primus/primus#614]
Primus 7.1.0

Environment:
  - macOS High Sierra
  - Google Chrome Canary
  - Node.js: 8.8.0

I've just created a main.ts file with : 
```ts
import { app, BrowserWindow } from "electron";
import { Primus } from "primus";

let mainWindow: BrowserWindow;

function createWindow() {
  mainWindow = new BrowserWindow({width: 1200, height: 800});

  mainWindow.loadURL("file://" + __dirname + "/index.html");

  mainWindow.webContents.openDevTools();

  const Socket = Primus.createSocket({ transformer: "engine.io", plugin: "primus-emit" });
  const primus = new Socket("http://localhost:2121");

  primus.on("open", () => {
    this.log("Connection opened !");
  });

  mainWindow.on("closed", () => {
    mainWindow = null;
});
}

app.on("ready", createWindow);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (mainWindow === null) {
    createWindow();
  }
});
```

And I have a compile error with tsc : 

```bash
$ tsc
src/main.ts(14,18): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
```

It is on the Socket but in plain vanilla javascript it is working, i can't understand? thanks

**Comment by lpinca** [comment]
TypeScript support is kinda broken, we don't use TypeScript. The definition file is maintained by the community. See https://github.com/primus/primus/issues/552.

**Comment by yovanoc** [comment]
Oh okay, too bad... but in the declaration file I see that the createSocket return a Socket from « net » ... why typescript don’t let me construct this?

**Comment by lpinca** [comment]
I don't know. The value returned by `Primus.createSocket()` is not a `net.Socket` but it's still a constructor.

**Comment by yovanoc** [comment]
Okay, i will take a look closer and open a PR if we have to change the declaration file so

**Comment by yovanoc** [comment]
```js
Primus.createSocket = function createSocket(options) {
  // Make sure the temporary Primus we create below doesn't start a heartbeat
  options = Object.assign({}, options, { pingInterval: false });

  var primus = new Primus(new EventEmitter(), options);
  return primus.Socket;
};
```

```ts
socket: Socket;
static createSocket(options?: IPrimusOptions): Socket;
```

I don't know if this is the problem but in ts the "socket" variable begin with a lowercase letter but not  in the return createSocket method

**Comment by yovanoc** [comment]
Or it could be related to something like this? https://stackoverflow.com/questions/40599069/node-js-net-socket-is-not-a-constructor

**Comment by lpinca** [comment]
Not on the latest version of Node.js:

```
$ node
> var s = new net.Socket();
undefined
```

**Comment by yovanoc** [comment]
I can't figure it out :/ if it can helps, on a really blank  yarn init project I add a index.ts instead of js and yarn add primus, in the top of the ts file: import { Primus } from "primus"; and if I `tsc` it tells me that : 

```
node_modules/primus/primus.d.ts(1,23): error TS2307: Cannot find module 'http'.
node_modules/primus/primus.d.ts(2,24): error TS2307: Cannot find module 'net'.
```

**Comment by lpinca** [comment]
This is why I wanted to remove the definition file in https://github.com/primus/primus/pull/537 :)

**Comment by yovanoc** [comment]
I have some news.

For this code in a .ts file:

<img width="706" alt="screen shot 2017-11-01 at 4 24 11 pm" src="https://user-images.githubusercontent.com/7302317/32282208-456c6ce0-bf21-11e7-9c36-41124a39dfe3.png">

it's working, but there are some errors dues to the definition file I think:

<img width="1104" alt="screen shot 2017-11-01 at 4 24 34 pm" src="https://user-images.githubusercontent.com/7302317/32282316-8adf0260-bf21-11e7-9258-8661a8a74d81.png">
