### ISSUE TITLE
Cluster with websokets transformer not works.

### ISSUE THREAD

**Issue by Valentinishe** [primus/primus#624]
**Version:** 7.1.0

**Environment:**
  - **Operating system:** Ubuntu 16.04
  - **Browser:** Google Chrome 63.0.3239.108 (Official Build) (64-bit)
  - **Node.js:** 8.9.1
  -  **npm:** 5.6.0

**Expected result:**

Primus with `websokets` transformer will work as expected while using nodejs `cluster` module.

**Actual result:**

Broadcasting does not work and console shows this output
```
Primus: 
Primus: 
Primus: The `cluster` module does not implement sticky sessions. Learn more about
Primus: this issue at:
Primus: 
Primus: http://github.com/primus/primus#can-i-use-cluster
Primus: 
```

**What I tried to do:**

```
'use strict';

const cluster = require('cluster');
const os = require('os');
const http = require('http');
const Primus = require('primus');

if (cluster.isMaster) {
  for (let index = 0; index < os.cpus().length; index++) {
    cluster.fork();
  }
}

else {
  const server = http.createServer().listen(3000, function () {
    console.log('Listening on 3000 port.');
  });
  const primus = new Primus(server, {
    transformer: 'websockets'
  });

  server.on('request', function (req, res) {
    if (req.url === '/') {
      res.end(`
        <script src="/primus/primus.js"></script>
        <script>
          const primus = new Primus();
          
          primus.on("data", function (data) {
            if (data === "hello") {
              alert("hello");
            }
          });
      </script>
    `);
    }

    if (req.url === '/broadcast') {
      primus.write('hello');

      res.end('broadcasted');
    }

    res.statusCode = 404;
    res.end();
  });
}
```

**Comment by lpinca** [comment]
Your example will only broadcast messages to clients connected to the same server. Broadcasting to all clients in the cluster is no supported out of the box.

**Comment by Valentinishe** [comment]
Sry, I said not exactly what I wanted. I tried send some message by `primus.write()` and on not clustered process it worked. But then I used cluster and message was not accepted by client, even using `ws`, as said in docs.

**Comment by Valentinishe** [comment]
I found my error, it was in client script. I forgot about `websockets: true` in client connection.
