### ISSUE TITLE
Consider using a different id generator by default

### ISSUE THREAD

**Issue by deje1011** [primus/primus#639]
**Version:**
3.2.1
**Environment:**
  - **Node.js:**

**Expected result:**
Unique spark ids across multiple servers.

**Actual result:**
Identical spark ids if two clients connect on two servers at the exact same time.

**Steps to reproduce:**
* Include primus rooms (https://github.com/cayasso/primus-rooms) in combination with redis
* Connect 2 clients at the same time on 2 different servers
=> They both have the same spark id
=> The rooms are a collection of spark ids, so both clients get messages as long as one of them is subscribed to the room.

In yeast, the current date is encoded and the result is compared to the last generated result. 
https://github.com/unshiftio/yeast/blob/master/index.js#L54
This only works as expected in a single server environment though. 

How about one of these?
https://github.com/kelektiv/node-uuid
https://github.com/dylang/shortid

It's awesome that you can already set a custom generator yourself but I think this risk should either be taken care of by default or at least mentioned in the documentation. 

Cheers,
Jesse

**Comment by lpinca** [comment]
There is also https://github.com/ai/nanoid which is faster than shortid.
Feel free to open a PR, I'm fine with either options (replace the id generator or document yeast limitations).

**Comment by deje1011** [comment]
@lpinca Okay cool. Switching to `nanoid` should be trivial as there are [only a few places `yeast` is used](https://github.com/primus/primus/search?utf8=%E2%9C%93&q=yeast&type=).
I'm just not sure when I'll find the time to setup the repo locally and test the changes. I'll add a comment here once I start. But if anyone who already has this setup is willing to do make the changes earlier that would be great.

**Comment by lpinca** [comment]
Indeed, the only thing to do is changing `yeast()` with `nanoid()` here:

https://github.com/primus/primus/blob/80c56c9589e4ef5f2f49cbe49d4543927433af95/spark.js#L35
