### ISSUE TITLE
Enhance documentation "Connect from React Native"?

### ISSUE THREAD

**Issue by djamalouch** [primus/primus#645]
I was wondering, whether primus works on React Native, but I couldn't find information regarding that. Did anybody try it? Would be great to have that inside the documentation I think.

**Comment by lpinca** [comment]
It should work, just build the client for "Node.js" and use it:

```js
const EventEmitter = require('events');
const Primus = require('primus');

const primus = new Primus(new EventEmitter(), {
  transformer: 'websockets'
  pingInterval: false
});

primus.save('/path/to/primus.js');
```

**Comment by djamalouch** [comment]
I totally missed that point... that's actually a great feature! I think it even belongs into the advantages section. 

"Easy to run on any JavaScript enabled platform. Just setup the library and retrieve its source code by .library() or .save() and do whatever you like - deploy it minified, recompile it or just run it."

Thanks a lot!

**Comment by evantahler** [comment]
Here's a whole example project doing this https://github.com/actionhero/actionhero-react-native
