### ISSUE TITLE
Broken heartbeat protocol

### ISSUE THREAD

**Issue by tejohnso** [primus/primus#646]
**Version:**
7.0.2

**Environment:**
  - any os

**Expected result:**
Client side attempts reconnect on broken connection (missed pingInterval)

**Actual result:**
Client does not attempt reconnect - silently accepts a broken connection

**Steps to reproduce:**
Create a socket with a default pingInterval of 45s and connect to a server that has heartbeat disabled to simulate a broken connection. The client doesn't attempt to reconnect as of 7.0.2

----

#580  breaks the heartbeat protocol. The client no longer disconnects/reconnects if a ping is not received within the timeout. 

> You might need to connect from a different node process where you don't have access to your primus instance and the compatible Socket instance. For these cases there a special createSocket method ...

There's no indication that processes created with the `createSocket` method should automatically exit when the connection is broken. The documentation suggests that the `createSocket` client behaves the same as any other. 

Maybe that's not the intention, but if that's the case, I think the change should at least have been part of a major version tick, and the documentation should be updated to clearly indicate that clients created through `createSocket` don't behave the same as clients created by the "from the browser" method.

Is the intention not to use `createSocket` in node processes? 
Why not set pingInterval to false as part of the createSocket option object if that's what is desired, rather than unexpectedly overriding the documented default of 30s, or worse, the user supplied preferred value?

**Comment by lpinca** [comment]
The `pingInterval` option is overridden by `Primus.createSocket()` to prevent the interval from keeping the process open.

The desired behaviour can be achieved using the `pingTimeout` option on the client constructor:

```js
const Primus = require('primus');

const Socket = Primus.createSocket();

const socket = new Socket(url, {
  pingTimeout: 45000
});
```
