### ISSUE TITLE
Enable compression for uws

### ISSUE THREAD

**Issue by ghost** [primus/primus#649]
Next version of uws will have an option to send compressed. You would pass bool compress as last option to native.server.send:

native.server.send(socket, message, opcode, undefined, compress).

I don't know how you want to expose this in Primis itself (let the user pass this compress boolean manually or always have it true). Undefined is the send callback which you currently ignore.

µWS itself does not compress unless the user explicitly pass true when sending but like said I don't know how you want to solve it here.

**Comment by lpinca** [comment]
There is a boolean server option in primus called `compression`. We can probably just forward that to `native.server.send()`.

**Comment by alexhultman** [comment]
So you want to always compress if it is possible? You don't have any per-send knobs?

This would be send(socket, message, opcode, undefined, true) - it won't compress unless in permessage-deflate so just pass constant true then.

**Comment by lpinca** [comment]
Yes, it's all or nothing for all transformers.

**Comment by lpinca** [comment]
The only other transformers that would support this per message is ws and in turn engine.io but we currently don't have an interface to support per message compression in primus so it's not a problem.
