### ISSUE TITLE
spark does not use eventemitter3

### ISSUE THREAD

**Issue by gaufqwi** [primus/primus#650]
**Version:**
7.1.1
**Environment:**
  - **Node.js:**

**Expected result:**
spark.once() takes a context argument per eventemitter3

**Actual result:**
spark.once() ignores context argument

Not sure whether or not this is intended. It would be nice to have the extra eventemitter3 functionality in spark.

**Comment by lpinca** [comment]
Yes because `Spark` does not inherit from `EventEmitter3` but from `Stream` to support `Spark.prototype.pipe()`. This is by design, use `Function.prototype.bind()` for a custom context in this case.
