### ISSUE TITLE
WS Error: Server specified Sec-WebSocket-Protocol that wasn't requested (iOS)

### ISSUE THREAD

**Issue by caciobanita** [primus/primus#668]
**Version:**
v7.2.2
**Environment:**
  - **Operating system:**
  - **Browser:**
  - **Node.js:**

iOS: 11.4
react-native: v0.55.4
node: 10.4.0

**Expected result:**

**Actual result:**

WS error: Server specified Sec-WebSocket-Protocol that wasn't requested

**Steps to reproduce:**

Generate primus: 

<pre>

const EventEmitter = require('events')
const Primus = require('primus')
const path = require('path')

const primus = new Primus(new EventEmitter(), {
  transformer: 'websockets',
  pingInterval: false
})

primus.save(path.join(__dirname, '..', 'lib', 'primus.js'))
</pre>

ActionHeorCLient:
<pre>
import { API_WS_URL } from '../config/index'

import Primus from './primus.js'

class ActionheroClient extends Primus.EventEmitter {
  constructor(options, client) {
    super(options, client)
    this.callbacks = {}
    this.id = null
    this.events = {}
    this.rooms = []
    this.state = 'disconnected'
    this.options = this.defaults()
  }

  defaults() {
    return { url: API_WS_URL, websockets: true }
  }

  // //////////////
  // CONNECTION //
  // //////////////
  connect(callback) {
    this.client = new Primus(this.options.url, { websockets: true })
    this.messageCount = 0

    this.client.on('open', () => {
      this.configure((details) => {
        if (this.state === 'connected') {
          //
        } else {
          this.state = 'connected'
          if (typeof callback === 'function') {
            callback(null, details)
          }
        }
        this.emit('connected')
      })
    })

    this.client.on('error', (error) => {
      console.log(error)
      this.emit('error', error)
    })

    this.client.on('reconnect', () => {
      this.messageCount = 0
      this.emit('reconnect')
    })

    this.client.on('reconnecting', () => {
      this.emit('reconnecting')
      this.state = 'reconnecting'
      this.emit('disconnected')
    })

    this.client.on('timeout', () => {
      this.state = 'timeout'
      this.emit('timeout')
    })

    this.client.on('close', () => {
      this.messageCount = 0
      if (this.state !== 'disconnected') {
        this.state = 'disconnected'
        this.emit('disconnected')
      }
    })

    this.client.on('end', () => {
      this.messageCount = 0
      if (this.state !== 'disconnected') {
        this.state = 'disconnected'
        this.emit('disconnected')
      }
    })

    this.client.on('data', (data) => {
      this.handleMessage(data)
    })
  }

  configure(callback) {
    this.rooms.forEach((room) => {
      this.send({ event: 'roomAdd', room: room })
    })

    this.detailsView((details) => {
      this.id = details.data.id
      this.fingerprint = details.data.fingerprint
      this.rooms = details.data.rooms
      callback(details)
    })
  }

  // /////////////
  // MESSAGING //
  // /////////////
  send(args, callback) {
    // primus will buffer messages when not connected
    this.messageCount++
    if (typeof callback === 'function') {
      this.callbacks[this.messageCount] = callback
    }
    // console.log(this.client.write(args))
    this.client.write(args)
  }

  handleMessage(message) {
    this.emit('message', message)
    if (message.context === 'response') {
      if (typeof this.callbacks[message.messageCount] === 'function') {
        this.callbacks[message.messageCount](message)
      }
      delete this.callbacks[message.messageCount]
    } else if (message.context === 'user') {
      this.emit('say', message)
    } else if (message.context === 'alert') {
      this.emit('alert', message)
    } else if (message.welcome && message.context === 'api') {
      this.welcomeMessage = message.welcome
      this.emit('welcome', message)
    } else if (message.context === 'api') {
      this.emit('api', message)
    }
  }

  // ///////////
  // ACTIONS //
  // ///////////

  action(action, params, callback) {
    if (!callback && typeof params === 'function') {
      callback = params
      params = null
    }
    if (!params) {
      params = {}
    }
    params.action = action
    this.send({ event: 'action', params: params }, callback)
  }

  // ////////////
  // COMMANDS //
  // ////////////
  say(room, message, callback) {
    this.send({ event: 'say', room: room, message: message }, callback)
  }

  file(file, callback) {
    this.send({ event: 'file', file: file }, callback)
  }

  detailsView(callback) {
    this.send({ event: 'detailsView' }, callback)
  }

  roomView(room, callback) {
    this.send({ event: 'roomView', room: room }, callback)
  }

  roomAdd(room, callback) {
    this.send({ event: 'roomAdd', room: room }, (data) => {
      this.configure(() => {
        if (typeof callback === 'function') {
          callback(data)
        }
      })
    })
  }

  roomLeave(room, callback) {
    var index = this.rooms.indexOf(room)
    if (index > -1) {
      this.rooms.splice(index, 1)
    }
    this.send({ event: 'roomLeave', room: room }, (data) => {
      this.configure(() => {
        if (typeof callback === 'function') {
          callback(data)
        }
      })
    })
  }

  documentation(callback) {
    this.send({ event: 'documentation' }, callback)
  }

  disconnect() {
    this.state = 'disconnected'
    this.client.end()
    this.emit('disconnected')
  }
}

export default ActionheroClient

</pre>

On Android is working as expected, but on iOS i get that error.

Any suggestions?

**Comment by lpinca** [comment]
Check if the client is sending a `Sec-WebSocket-Protocol` header. To do that you can use a middleware:

```js
primus.use('log', function (req, res) {
  console.log(req.headers);
});
```

**Comment by caciobanita** [comment]
Hello @lpinca 

I have tried to generate primus.js file using:

<pre>
#!/usr/bin/env node

const EventEmitter = require('events')
const Primus = require('primus')
const path = require('path')

const primus = new Primus(new EventEmitter(), {
  transformer: 'websockets',
  pingInterval: false,
})

primus.use('log', function (req, res) {
  console.log(req)
  console.log(res)
})

primus.save(path.join(__dirname, '..', 'lib', 'primus.js'))
</pre>

No success to see the request.

**Comment by lpinca** [comment]
Hi, you should use the middleware on the server, not the client.

**Comment by lpinca** [comment]
Ok, closing then.
