### ISSUE TITLE
Upgrade to latest version of primus

### ISSUE THREAD

**Issue by ravi-gyrix** [primus/primus#673]
**Version:** 7.2.2

**Environment:**
  - **Operating system:** Windows
  - **Browser:** Chrome
  - **Node.js:** 6.10.2

**Expected result:** Working ping/pong.

**Actual result:** server-side ping not initialized.

How to use ping/pong?

Server side code: 
        spark.on('incoming::pong', function () {});
        spark.on('outgoing::pong', function () {});

Client side code: 
      primus.on('incoming::ping', function (){});
      primus.on('outgoing::ping', function () {});

**Comment by lpinca** [comment]
See the release notes for version 7.0.0: https://github.com/primus/primus/releases/tag/7.0.0

**Comment by ravi-gyrix** [comment]
@lpinca  Thanks for your help. Ping/pong issue is solved.

Is there any way to detect slow internet connection?

**Comment by lpinca** [comment]
> Is there any way to detect slow internet speed connection?

No, not really, if you just want the latency you can get a realistic approximation.

**Comment by lpinca** [comment]
Closing, discussion can continue if needed.
