### ISSUE TITLE
Use proxy on client

### ISSUE THREAD

**Issue by yovanoc** [primus/primus#676]
Hello, can we use a proxy client-side with primus? I don't find a way

thanks

**Comment by lpinca** [comment]
There is no proper support for it but you can use transformer specific options via the `transport` option where possible. For example with the `websockets` transformer you can specify a [custom agent](https://github.com/websockets/ws#how-to-connect-via-a-proxy).
Similarly with `faye` you can specify the [`proxy`](https://github.com/faye/faye-websocket-node#using-the-websocket-client) option.

**Comment by lpinca** [comment]
Closing as answered, discussion can continue if necessary.

**Comment by Bojack92160** [comment]
How did you manage to do it? I tried to use https-proxy-agent and set forceNode option to true but I wasn't able to connect via proxy. (I use electron btw)
