### ISSUE TITLE
401 on UPGRADE request doesn't send headers

### ISSUE THREAD

**Issue by davedoesdev** [primus/primus#691]
**Version:** 7.2.2

**Environment:**
  - **Operating system:** Ubuntu 18.04
  - **Browser:** Chrome 69.0.3497.92
  - **Node.js:** 10.10.0

**Expected result:** 401 on upgrade requests and browser reads response

**Actual result:**

"Error during WebSocket handshake: net::ERR_RESPONSE_HEADERS_TRUNCATED"

**Steps to reproduce:** 

- Using Primus client, set user:pass in URL
- Chrome initially sends an UPGRADE request with no Authorization header
- Have some authorizer code on server check for Authorization header and callback with an error with statusCode 401

What happens is we `destroy()` the socket:

https://github.com/primus/primus/blob/master/middleware/authorization.js#L55

and the socket gets terminated before the headers get away.

If I replace that line with `res.end()` then it works as expected.

IIRC I wrote that code a few years ago. Would you like me to make a PR?

**Comment by davedoesdev** [comment]
Ah: https://github.com/primus/primus/pull/95/files

The `destroy()` was there before and I left in it in there.

I'm guessing Node is more aggressive with `destroy()` now, or due to timing the headers no longer get written.

**Comment by davedoesdev** [comment]
Should we close the connection or keep it open having sent the response?

**Comment by lpinca** [comment]
> I'm guessing Node is more aggressive with destroy() now, or due to timing the headers no longer get written.

AFAIK nothing changed in this regard.
I would close the connection.

**Comment by davedoesdev** [comment]
Closed by #692 
Thanks @lpinca for your input
