### ISSUE TITLE
Impossible to lock sockjs version

### ISSUE THREAD

**Issue by bard** [primus/primus#717]
**Version: 7.3.2**

**Environment:**
  - **Operating system: Android**
  - **Browser: AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1**
  - **Node.js: 10.15.2**

I'm seeing the following in the console:

```
E/browser ( 2462): Console: Uncaught Error: Incompatible SockJS! Main site
uses: "1.3.0", the iframe: "1.1.4". https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js:2
```

If I understand the flow correctly, this is what happens:

1. on this device/browser combination, SockJS tries various transport strategies and eventually picks the `iframe` 
2. it requests the iframe from the server
3. in https://github.com/sockjs/sockjs-node/blob/4c9f3009be13962b0785138ccdf527c5abe925f6/lib/iframe.js, the server generates the iframe, embedding the `sockjs_url` argument so the iframe knows where it has to load the library from
4. here: https://github.com/primus/primus/blob/bfc3f3180aeebe0c45019b8ec86b260935011e52/transformers/sockjs/server.js#L43 primus does not specify a `sockjs_url`, so
5. at https://github.com/sockjs/sockjs-node/blob/e2369c3d02c7e285ecbac409f3a4d0c8b72c39d3/lib/server.js#L31, sockjs picks the latest from jsdelivr as default

Unfortunately that means that sockjs client updates my happen at any time on end users' devices, with no way for the developer to first test them.

I fixed this (perhaps simplistically) in https://github.com/sockjs/sockjs-node/blob/e2369c3d02c7e285ecbac409f3a4d0c8b72c39d3/lib/server.js#L31 by changing:

```js
  this.service = sockjs.createServer();
```

Into:

```js
  const SOCKJS_CLIENT_VERSION = require('sockjs-client/package.json').version
  this.service = sockjs.createServer({
    sockjs_url: 'https://cdn.jsdelivr.net/npm/sockjs-client@' + SOCKJS_CLIENT_VERSION + '/dist/sockjs.min.js'
  });
```

If that sounds like a good approach, I'll prepare a PR.

**Comment by bard** [comment]
On second look, the mismatch isn't between the sockjs-client library loaded from CDN and the one I installed under node_modules, it's between the sockjs-client library loaded from CDN and the one bundled with primus (`node_modules/primus/transformers/sockjs/library.js`). Not sure how to extract the version from there in a non-hacky way.

**Comment by bard** [comment]
...and on third look, it seems that everything will go right by itself when the following change in `sockjs-node` gets released: https://github.com/sockjs/sockjs-node/commit/dc5a3d9ce809ed5e692bc1a5159546aa4824ee31

Currently, it's the link `https://cdn.jsdelivr.net/sockjs/1/sockjs.min.js` that keeps resolving to sockjs-client 1.1.4 even when `sockjs-node` expects 1.3.0. The commit above changes the CDN link to `https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js` which correctly resolves to `sockjs-client` 1.3.0.

Pinging @brycekahle ... any chance for a release?

**Comment by broakenmedia** [comment]
Not sure what to do here? SockJS cannot be used on the client at this time? I'm not sure i can use any transport other than sock to fulfill the same needs.

**Comment by brycekahle** [comment]
@bard @broakenmedia You should be able to use the transport specific options until a release happens. Example:

`new Primus(server, { transport: { sockjs_url: 'https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js' } });`

See https://github.com/primus/primus/blob/a1832daf7ac5de45c61349d960bac9975a409048/transformers/sockjs/server.js#L78-L83 for how those options are passed to SockJS.

**Comment by broakenmedia** [comment]
> transport: { sockjs_url: 'https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js' }

Perfect! Thank you!

**Comment by lpinca** [comment]
Thank you @brycekahle.
I'm closing as there is a workaround until a new release is cut.
