### ISSUE TITLE
reconnect question

### ISSUE THREAD

**Issue by davidmoshal** [primus/primus#720]
Hi, am replacing a Faye version that has been in production for about 8 years.
Have a question about reconnects.
From what I can see, the 'end' event is received on the server each time there is a reconnect attempt, so is isn't possible to detect when the client has given up re-connects, correct?

**Comment by lpinca** [comment]
Yes correct, every reconnect is a new connection.

**Comment by davidmoshal** [comment]
thanks, so on reconnect client needs to re-subscribe to rooms (ie: with primus-rooms)

**Comment by lpinca** [comment]
Correct.

**Comment by davidmoshal** [comment]
thanks.

**Comment by lpinca** [comment]
I'm closing this. Discussion can continue if needed.
