### ISSUE TITLE
React can't resolve errors

### ISSUE THREAD

**Issue by gateaubleu** [primus/primus#736]
Hey,

**Version**: 7.3.3

Today i would like implement primus to my ReactJs app, I install via 

> npm install primus

App is made by this simple command line:

> npm init react-app my-app

But after 1 hour of breaking my head, I don't understand why I got multiple "can't resolve" error, only when import like 

`import {createSocket} from 'primus';`

Many errors, I have:

> index.js:1375 ./node_modules/primus/parsers/binary.js
Module not found: Can't resolve 'binary-pack' in 'D:\Developpement\ReactJs\primus-app\node_modules\primus\parsers'
console.<computed> @ index.js:1375
index.js:1375 ./node_modules/primus/transformers/browserchannel/index.js
Module not found: Can't resolve 'browserchannel' in 'D:\Developpement\ReactJs\primus-app\node_modules\primus\transformers\browserchannel'
console.<computed> @ index.js:1375
index.js:1375 ./node_modules/primus/transformers/browserchannel/server.js
Module not found: Can't resolve 'browserchannel' in 'D:\Developpement\ReactJs\primus-app\node_modules\primus\transformers\browserchannel'
console.<computed> @ index.js:1375
index.js:1375 ./node_modules/primus/index.js
Module not found: Can't resolve 'cluster' in 'D:\Developpement\ReactJs\primus-app\node_modules\primus'
console.<computed> @ index.js:1375
index.js:1375 ./node_modules/primus/parsers/ejson.js
Module not found: Can't resolve 'ejson' in 'D:\Developpement\ReactJs\primus-app\node_modules\primus\parsers'
console.<computed> @ index.js:1375
index.js:1375 ./node_modules/primus/parsers/ejson.js
Module not found: Can't resolve 'ejson/source' in 'D:\Developpement\ReactJs\primus-app\node_modules\primus\parsers'
console.<computed> @ index.js:1375
index.js:1375 ./node_modules/primus/transformers/engine.io/server.js
Module not found: Can't resolve 'engine.io' in 'D:\Developpement\ReactJs\primus-app\node_modules\primus\transformers\engine.io'
console.<computed> @ index.js:1375
index.js:1375 ./node_modules/primus/parsers/msgpack.js
Module not found: Can't resolve 'primus-msgpack' in 'D:\Developpement\ReactJs\primus-app\node_modules\primus\parsers'
console.<computed> @ index.js:1375
index.js:1375 ./node_modules/primus/transformers/uws/server.js
Module not found: Can't resolve 'uws' in 'D:\Developpement\ReactJs\primus-app\node_modules\primus\transformers\uws'

Thanks for all of your help, have a good day.

**Comment by roelvan** [comment]
Instructions can be found here: https://github.com/primus/primus#client-library

**Comment by gateaubleu** [comment]
1 year ago

**Comment by roelvan** [comment]
Just started using Primus myself and ran into this issue too.
