### ISSUE TITLE
Problem using primus with electron framework

### ISSUE THREAD

**Issue by Bojack92160** [primus/primus#746]
Hello, I want to use primus to connect to a distant server. In nodejs, I make it work with:
```
      var Primus = require("primus");
      const PrimusSocket =  Primus.createSocket({transformer: "engine.io"});
      const primus = new PrimusSocket(myurl);
```
this work pretty well. But I want to make a desktop application with the framework electron, and the trouble begin. Here is how I include my code in electron:

```
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
   <script>
      const myurl="https://myurl.com";
      var Primus = require("primus");
      const PrimusSocket =  Primus.createSocket({transformer: "engine.io"});
      const primus = new PrimusSocket(myurl);

   </script>
</body>
</html>
```
when I use the 'createSocket' methode, my app don't work and I can't write anything in the console. I have no error message. I have tried using type="application/javascript", ou "text/javascript" in the <script> balise but it doesn't help. I also tried to use 'Primus.connect(url, { options });' but it doesn't change anything.

I think i'm missing something but I don't know what, and I don't understand why it work in nodejs and not in electron.

**Comment by almamlaka** [comment]
@Bojack92160 did you solve it ?

**Comment by Bojack92160** [comment]
Yep. Due to my Electron environnement (Chromium with NodeIntegration set to TRUE), I can't use Primus.createSocket() function (the app crash). What you need to do is to get the primus library generated by the server. You should find it at something like 'YourServerURL/primus/primus.js'. If you don't find it, you can create it yourself in a full nodejs environnement:
```
var primus = Primus.createServer(function connection(spark) {

}, { port: 8080, transformer: 'engine.io'}); 

  let x = primus.library(); //x contain the library

/*  fs.writeFile('persoPrimus.js', x, function(err) {
    if (err) {
      return console.log(err);
    }
    //console.log("File saved successfully!");
  });

```

Once you have the primus.js library, you require in your project and use it like so:

```
var Primus = require("./Primus.js");
primus = new Primus(ServerURL, options); //options is optional
```

**Comment by lilian131** [comment]
Yes this is exact! I wrote a solution here for anyone that need: https://stackoverflow.com/a/59373306/9840385
