### ISSUE TITLE
Does the primus web client work with a non-primus  websocket server?

### ISSUE THREAD

**Issue by mark-hahn** [primus/primus#765]
I apologize if this isn't the correct place to ask usage questions.  If there is a better place like a forum let me know.

I have scoured the docs and the web and cannot figure out if primus is required on the server.  I am starting a web app that needs to use a websocket to an esp8266 arduino server.  I am 99.99% sure the primus server can't run on an arduino.  :-)

I have used primus in the past with primus on both the node-server side and the web client side.  It was extremely solid and persistent.  I had a client that ran for many months even through server outages.  Can I get this same performance with a non-primus server?

**Comment by lpinca** [comment]
It is technically possible but it's not trivial because the Primus client  is designed to talk to a Primus server. You basically have to rebuild:

- The message protocol
- The serialization format
- The plugin system
- Something I can't think of at the moment

on the server.

I think it will be easier to use a pure WebSocket client.

**Comment by mark-hahn** [comment]
Thanks, even though I don't like the answer :-)  I was hoping to avoid writing my own persistent session code.  I don't need any message protocol, serialization, or plugins.  I just want the equivalent of a websocket that lasts forever like I had with Primus..  Unfortunately when I google "persistent websocket" I get a ton of hits telling me how websockets are persistent.

**Comment by lpinca** [comment]
The WebSocket connection is persistent, you just need a reconnection mechanism. There are some wrappers that do this automatically like https://github.com/lukeed/sockette.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
