### ISSUE TITLE
How can I know if a connection has been upgraded or not?

### ISSUE THREAD

**Issue by zen0wu** [primus/primus#766]
**Version:** 7.2.3

**Environment:**
  - **Operating system:** MacOS
  - **Browser:** Chrome
  - **Node.js:** 12.16.3

**Expected result:**

Basically I'm looking for a way to tell if a connection has been upgraded to websocket.
This is useful to control some behavior on the load balancer side, but I didn't find any API in the doc that seems to do this?

**Actual result:**

**Steps to reproduce:**

**Comment by lpinca** [comment]
It depends on the transformer used. The `websockets` and `faye` transformers only use the WebSocket protocol. I don't there is a way to know what transport is used with the `engine.io` and `sockjs` transformer.

Try to ask the same question in the [engine.io](https://github.com/socketio/engine.io) and [sockjs](https://github.com/sockjs/sockjs-node) repositories.

**Comment by zen0wu** [comment]
@lpinca Thanks for the response. We're using engine.io. I wonder how can I properly access the underlying engine.io (or other transformer)'s server? Is it `primus.transformer.something`? Or maybe there's some other API I should use? Thanks again!

**Comment by lpinca** [comment]
If I remember correctly on the server it should be `primus.transformer.service` but I think you can't do much with it. The `socket` property of a `Spark` holds a reference to the transformer "socket" (the engine.io "socket" in your case) which might have more details.

**Comment by zen0wu** [comment]
Thanks for the help! I'll look into that. Closing
