### ISSUE TITLE
Primus with Koa and websockets transport

### ISSUE THREAD

**Issue by PlkMarudny** [primus/primus#772]
I am unable to get Primus server working with [Koa](https://koajs.com/) using websockets transformer. It works with Socksjs, however.
The basic application is below:
````
'use strict';

const http = require('http');
const Primus = require('primus');

const Koa = require('koa');
const bodyParser = require('koa-bodyparser');
const serve = require('koa-static');
const router = require('koa-router');

const port = process.argv[2] || 8080;

// Koa stuff
const app = new Koa();
app.use(bodyParser());
app.use(serve('src'));

const server = http.createServer(app.callback());
const primus = new Primus(server, { transformer: 'websockets', parser: 'JSON' });

primus.on("connection", function (spark) {
  console.log('client connected');
  spark.write("Hello, world!");
})

console.log(`Server listening on port ${port}`);
app.listen(port);
````

What should I do (required dependency "ws" is installed)

**Comment by lpinca** [comment]
`app.listen()` creates a [new HTTP server](https://github.com/koajs/koa/blob/2.13.1/lib/application.js#L81) which is different from the one passed to the `Primus` constructor.

Use `server.listen(port, function() { console.log(`Server listening on port ${port}`); })` instead of `app.listen(port)`.

**Comment by PlkMarudny** [comment]
Will give it a try, many thanks!

**Comment by PlkMarudny** [comment]
Works. Thank you very much.
