### ISSUE TITLE
Server Side Events (SSE) source

### ISSUE THREAD

**Issue by strarsis** [primus/primus#778]
Does Primus also support Server Side Events (SSE) out of the box?
It is also a (unidirectional) realtime protocol and has its own set of strengths, it is very handy for change notifications by an API or server.

**Comment by lpinca** [comment]
No, it does not. There is no support for SSE.

**Comment by strarsis** [comment]
@lpinca: It would be great if this can be added!

**Comment by lpinca** [comment]
It does not make much sense in primus because the every transformer offers a bidirectional channel.

**Comment by strarsis** [comment]
@lpinca: Well, this makes sense. Would it be easier to add SSE to FeathersJS or to the underlying Primus provider?

**Comment by lpinca** [comment]
I don't know but it might be easier to use something like https://github.com/MatthewWid/better-sse directly.

**Comment by strarsis** [comment]
Thanks. I will use a FeathersJS event/hook and signal the clients over SSE that new entities have been added.
I need this signaling only for one specific entity. The react-admin enterprise edition also supports realtime, but this would be overkill.

**Comment by strarsis** [comment]
Though Primus could still have a one-directional SSE IMHO - that informs about changes/additions... 🐱
