### ISSUE TITLE
Consider alternative to deprecated navigator.userAgent getter.

### ISSUE THREAD

**Issue by tejohnso** [primus/primus#780]
Given [deprecation](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html) of `navigator.userAgent`, perhaps switch to `navigator.userAgentData`

**Comment by lpinca** [comment]
It is used to work around a bug in Safari 5.1.3 or earlier.

https://github.com/primus/primus/blob/552b2f4ff692e223bffc016d8c561e920d7d2b1d/primus.js#L1184-L1194

`navigator.userAgentData` is not even supported by Safari 16.

I think no one is using Safari 5.1.3 or earlier nowadays and I don't even know if Primus still works there so I think it might make more sense to remove the workaround completely.
