### ISSUE TITLE
Add authentication info in the Spark object.

### ISSUE THREAD

**Issue by legege** [primus/primus#84]
There is a need to identify who the user is behind a Spark object, that was previously authorized. We cannot authenticate the user with the current architecture. This is needed for two-way SSL. See issue #70 for reference.

The root of this problem is that we don't have access to the HTTP request object from the Spark, only the headers. Would it be possible to keep a reference to the request object? Is it dangerous in terms of leaks? This way, when we see a new Spark, we could check who the connection is.

**Comment by ddennis** [comment]
If i am understanding this correctly, putting the decoded token on the request is a valid solutions
    req.decoded_token = decoded;

I have modified the authorization example to use jsonwebtokens:


primus.authorize(authorize);

    var db = require('./db')
    , jwt = require('jsonwebtoken');
    var secret = 'shhhh, very secret';
    module.exports = function authorize(req, authorized) {
    var token = req.query.token;
      jwt.verify(token, secret, function(err, decoded) {
         if(err ){
              console.log (" authorize.js > err " , err)
         }else{
          // console.log (" authorize.js > ++ decoded " , decoded)
          req.decoded_token = decoded;
           authorized();
         }
      })
    };

And then in the connection:
    spark.request.decoded_token
